/* Username/password access to shared test records, using the existing portal screens and API. */
(function(){'use strict';
const U=window.UKRPortal;if(!U)return;const {state,$,t,raw,copy,button,field,data,submit,dialog,clear,empty,panel,table,request}=U;
const order=['en','ar','ru','fr','ur','hi','zh'];
const rows=[
['Username','اسم المستخدم','Имя пользователя','Nom d’utilisateur','صارف نام','उपयोगकर्ता नाम','用户名'],
['Use the test username and password.','استخدم اسم المستخدم وكلمة المرور للاختبار.','Используйте тестовые имя и пароль.','Utilisez les identifiants de test.','ٹیسٹ صارف نام اور پاس ورڈ استعمال کریں۔','टेस्ट उपयोगकर्ता नाम और पासवर्ड डालें।','请使用测试用户名和密码。'],
['Shared test workspace. Test data only; do not enter real customer information.','مساحة اختبار مشتركة. بيانات تجريبية فقط؛ لا تُدخل معلومات عملاء حقيقية.','Общая тестовая среда. Не вводите реальные данные клиентов.','Espace de test partagé. Ne saisissez pas de vraies données clients.','مشترکہ ٹیسٹ جگہ۔ صرف ٹیسٹ ڈیٹا؛ اصل کسٹمر کی معلومات درج نہ کریں۔','साझा टेस्ट कार्यक्षेत्र। वास्तविक ग्राहक जानकारी न डालें।','共享测试空间。仅限测试数据，请勿输入真实客户信息。'],
['Invalid username or password.','اسم المستخدم أو كلمة المرور غير صحيحة.','Неверное имя пользователя или пароль.','Nom d’utilisateur ou mot de passe incorrect.','صارف نام یا پاس ورڈ غلط ہے۔','उपयोगकर्ता नाम या पासवर्ड गलत है।','用户名或密码错误。'],
['This action is unavailable in the shared test workspace.','هذا الإجراء غير متاح في مساحة الاختبار المشتركة.','Действие недоступно в общей тестовой среде.','Cette action est indisponible dans l’espace de test partagé.','یہ کارروائی مشترکہ ٹیسٹ جگہ میں دستیاب نہیں ہے۔','यह कार्रवाई साझा टेस्ट कार्यक्षेत्र में उपलब्ध नहीं है।','此操作在共享测试空间中不可用。'],
['Test access has expired.','انتهت صلاحية الوصول التجريبي.','Срок тестового доступа истёк.','L’accès de test a expiré.','ٹیسٹ رسائی کی مدت ختم ہو گئی ہے۔','टेस्ट पहुँच की अवधि समाप्त हो गई है।','测试访问已过期。'],
['New booking','حجز جديد','Новое бронирование','Nouvelle réservation','نئی بکنگ','नई बुकिंग','新建预订'],
['Details','التفاصيل','Подробности','Détails','تفصیلات','विवरण','详情'],
['Update ETA','تحديث وقت الوصول المتوقع','Изменить ETA','Modifier l’arrivée estimée','متوقع آمد اپ ڈیٹ کریں','अनुमानित आगमन बदलें','更新预计到达时间'],
['Reason for ETA change','سبب تغيير وقت الوصول المتوقع','Причина изменения ETA','Motif du changement','متوقع آمد میں تبدیلی کی وجہ','अनुमानित आगमन बदलने का कारण','更改预计到达时间的原因'],
['ETA uses your device time zone.','وقت الوصول المتوقع يستخدم المنطقة الزمنية لجهازك.','ETA использует часовой пояс вашего устройства.','Le fuseau horaire de votre appareil est utilisé.','متوقع آمد آپ کے آلے کے ٹائم زون میں ہے۔','अनुमानित आगमन आपके डिवाइस के समय क्षेत्र में है।','预计到达时间采用您设备的时区。'],
['Booking saved.','تم حفظ الحجز.','Бронирование сохранено.','Réservation enregistrée.','بکنگ محفوظ ہو گئی۔','बुकिंग सहेज दी गई।','预订已保存。'],
['Legal owner name','اسم المالك القانوني','Имя законного владельца','Nom du propriétaire légal','قانونی مالک کا نام','कानूनी मालिक का नाम','合法货主名称'],
['Origin country code','رمز بلد المنشأ','Код страны отправления','Code du pays d’origine','روانگی کے ملک کا کوڈ','प्रस्थान देश कोड','始发国家代码'],
['Destination country code','رمز بلد الوجهة','Код страны назначения','Code du pays de destination','منزل کے ملک کا کوڈ','गंतव्य देश कोड','目的国家代码'],
['Cargo summary','وصف البضاعة','Описание груза','Description des marchandises','کارگو کی تفصیل','माल का विवरण','货物描述'],
['Timeline','الخط الزمني','История','Historique','ٹائم لائن','समयरेखा','时间线'],
['Open bookings','الحجوزات المفتوحة','Открытые бронирования','Réservations ouvertes','کھلی بکنگ','खुली बुकिंग','进行中的预订']
];
for(const row of rows)order.forEach((lang,i)=>window.UKRPortalMessages[lang][row[0]]=row[i]);
for(const lang of order)for(const [code,key]of Object.entries({invalid_credentials:'Invalid username or password.',demo_action_unavailable:'This action is unavailable in the shared test workspace.',demo_expired:'Test access has expired.'}))window.UKRPortalMessages[lang][code]=window.UKRPortalMessages[lang][key];
const services=[['air_ddp','Air DDP Consolidation'],['sea_ddp','Sea DDP Consolidation'],['air_express','Air Express'],['sea_lcl','LCL'],['sea_fcl','FCL'],['land','Truck'],['storage','Storage & Fulfilment'],['customs','Customs Clearance']];
const label=s=>services.find(x=>x[0]===s)?.[1]||s;
const status=s=>({submitted:'Booking submitted',accepted:'Booking accepted',in_transit:'In transit',arrived:'Arrived at destination',delivered:'Delivered'}[s]||s);
async function details(id){const result=await request('/bookings/'+id),b=result.booking;dialog('Details',box=>{box.append(raw('h3',b.code),raw('p',b.origin+' → '+b.destination),raw('p',b.cargo_summary),raw('p',t('Status')+': '+t(status(b.status))),raw('p','ETA: '+U.formatDate(b.eta)));const section=panel(box,'Timeline');for(const e of result.events)section.append(raw('p',U.formatDate(e.occurred_at)+' · '+t(e.note||status(e.to_status||e.status))));if(!result.events.length)empty(section);});}
function editETA(b){dialog('Update ETA',box=>{const f=raw('form');field(f,'eta','ETA',{type:'datetime-local',required:true});field(f,'reason','Reason for ETA change',{type:'textarea',required:true,maxLength:500});f.append(copy('p','ETA uses your device time zone.'));submit(f,'Save',()=>request('/bookings/'+b.id+'/eta',{version:b.version,eta:new Date(f.elements.eta.value).toISOString(),reason:f.elements.reason.value},'PUT'));box.append(f);});}
async function bookingForm(selected='air_ddp'){
 const staff=state.kind==='staff',customer=staff?await request('/demo/customer'):null;
 dialog('New booking',box=>{const f=raw('form',null,'form-grid');field(f,'service','Service',{value:selected,options:services.map(([value,label])=>({value,label})),required:true});
 for(const [name,title,value]of [['legal_owner_name','Legal owner name',customer?.legal_name||'Demo customer company'],['phone','Phone',''],['origin','Origin',''],['destination','Destination',''],['origin_country','Origin country code','CN'],['destination_country','Destination country code','AE']])field(f,name,title,{value,required:true,maxLength:name.endsWith('country')?2:200});
 field(f,'cargo_summary','Cargo summary',{type:'textarea',required:true,maxLength:2000});const requestKey=crypto.randomUUID();
 submit(f,'Submit',()=>request('/bookings',{...data(f),origin_country:f.elements.origin_country.value.toUpperCase(),destination_country:f.elements.destination_country.value.toUpperCase(),...(staff?{customer_id:customer.id}:{}),request_key:requestKey}),async out=>{$('editor').close();await U.refresh(false);await U.render(state.kind==='staff'?selected:'shipments');$('message').textContent=t('Booking saved.')+' '+out.booking.code;});box.append(f);});
}
async function list(title,service=null,offset=0){const box=clear(title),out=await request('/bookings?limit=25&offset='+offset+(service?'&service='+encodeURIComponent(service):''));box.append(button('New booking',()=>bookingForm(service||'air_ddp')));table(box,out.items,[['code','Reference'],[b=>t(label(b.service)),'Service'],[b=>b.origin+' → '+b.destination,'Route'],[b=>t(status(b.status)),'Status'],[b=>U.formatDate(b.eta),'ETA']],(td,b)=>{td.append(button('Details',()=>details(b.id)));if(state.kind==='staff')td.append(button('Update ETA',()=>editETA(b)));});if(offset>0)box.append(button('Previous',()=>list(title,service,offset-25)));if(offset+25<out.total)box.append(button('Next',()=>list(title,service,offset+25)));}
U.register('customer:dashboard',()=>list('Dashboard'));U.register('customer:shipments',()=>list('My Shipments'));U.register('customer:booking',async()=>{clear('Booking').append(button('New booking',()=>bookingForm()));});
for(const [id,title]of services)U.register('staff:'+id,()=>list(title,id));
U.register('staff:customers',async()=>{const box=clear('Customers'),c=await request('/demo/customer');table(box,[c],[['legal_name','Legal company name'],['email','Email']]);});
document.addEventListener('submit',async event=>{if(event.target.id!=='loginForm')return;event.preventDefault();event.stopImmediatePropagation();const f=event.target,b=f.querySelector('button[type=submit]');b.disabled=true;$('authError').textContent='';try{const out=await request('/demo/login',{username:f.elements.username.value,password:f.elements.password.value});f.elements.password.value='';state.csrf=out.csrf;await U.refresh(false);$('authView').hidden=true;$('appView').hidden=false;await U.render(state.kind==='staff'?'overview':'dashboard');}catch(e){U.error(e,$('authError'));}finally{b.disabled=false;}},true);
document.addEventListener('DOMContentLoaded',()=>{const f=$('loginForm');$('passwordLabel').hidden=false;f.elements.password.required=true;f.elements.password.minLength=4;f.elements.password.maxLength=128;$('otpForm').hidden=true;$('testMail').hidden=true;$('authIntro').dataset.t='Use the test username and password.';const note=copy('p','Shared test workspace. Test data only; do not enter real customer information.','demo-notice');note.setAttribute('role','note');document.body.prepend(note);const help=raw('p',(state.kind==='staff'?'Admin':'customer')+' / 1234');help.id='demoLoginHint';f.after(help);U.translate();}, {once:true});
})();
