/* Shared staff/customer application shell. User content is rendered as text, not HTML. */
(function(){'use strict';
const $=id=>document.getElementById(id),state={kind:document.body.dataset.portal,locale:'en',me:null,csrf:null,page:''},screens=new Map();
const languages=[['en','English'],['ar','العربية'],['ru','Русский'],['fr','Français'],['ur','اردو'],['hi','हिन्दी'],['zh','简体中文']];
const supported=v=>languages.some(([id])=>id===v);
let saved='';try{saved=localStorage.getItem('ukr-language')||'';}catch{}
const explicit=new URLSearchParams(location.search).get('lang');state.locale=supported(explicit)?explicit:supported(saved)?saved:(navigator.languages||['en']).map(l=>l.split('-')[0]).find(supported)||'en';
const t=(key,args={})=>String(window.UKRPortalMessages?.[state.locale]?.[key]??key).replace(/\{([a-zA-Z_]+)\}/g,(_,name)=>String(args[name]??'{'+name+'}'));
const raw=(tag,value=null,cls='')=>{const n=document.createElement(tag);if(value!=null)n.textContent=String(value);if(cls)n.className=cls;return n;};
const copy=(tag,source,cls='')=>{const n=raw(tag,t(source),cls);n.dataset.t=source;return n;};
function translate(){document.documentElement.lang=state.locale==='zh'?'zh-Hans':state.locale;document.documentElement.dir=['ar','ur'].includes(state.locale)?'rtl':'ltr';for(const n of document.querySelectorAll('[data-t]'))n.textContent=t(n.dataset.t);for(const n of document.querySelectorAll('[data-t-label]'))n.setAttribute('aria-label',t(n.dataset.tLabel));for(const n of document.querySelectorAll('[data-t-placeholder]'))n.placeholder=t(n.dataset.tPlaceholder);document.querySelectorAll('[data-language-picker]').forEach(n=>n.value=state.locale);}
function error(e,target=null){const n=target||($('editor').open?$('editorError'):state.me?$('error'):$('authError'));n.textContent=t(e.code||e.message||'service_unavailable');if(e.status===401&&state.me){state.me=null;$('appView').hidden=true;$('authView').hidden=false;$('authError').textContent=t('Your session has expired. Sign in again.');}}
async function request(path,data,method=data?'POST':'GET',options={}){let response;try{response=await fetch('/api/portal'+path,{method,credentials:'same-origin',headers:{...(data instanceof FormData?{}:{'Content-Type':'application/json'}),...(state.csrf?{'X-CSRF-Token':state.csrf}:{}),...options.headers},body:data?(data instanceof FormData?data:JSON.stringify(data)):undefined,signal:AbortSignal.timeout(30000)});}catch{throw Object.assign(Error('service_unavailable'),{code:'service_unavailable'});}if(options.binary&&response.ok)return response.blob();let out;try{out=await response.json();}catch{out={error:'service_unavailable'};}if(!response.ok)throw Object.assign(Error(out.error||'service_unavailable'),{code:out.error||'service_unavailable',status:response.status,details:out.details});return out;}
function button(label,action,cls='secondary'){const b=copy('button',label,cls);b.type='button';b.addEventListener('click',async()=>{b.disabled=true;try{await action(b);}catch(e){error(e);}finally{if(b.isConnected)b.disabled=false;}});return b;}
function clear(title){$('pageTitle').dataset.t=title;$('pageTitle').textContent=t(title);$('content').replaceChildren();$('error').textContent='';return $('content');}
function empty(box,message='No records yet'){box.append(copy('p',message,'empty'));}
function panel(box,title){const p=raw('section',null,'panel');p.append(copy('h2',title));box.append(p);return p;}
function table(box,items,columns,action=null){if(!items.length){empty(box);return;}const wrap=raw('div',null,'table-wrap'),table=raw('table'),head=raw('thead'),row=raw('tr'),body=raw('tbody');for(const [,label]of columns)row.append(copy('th',label));if(action)row.append(copy('th','Actions'));head.append(row);for(const item of items){const tr=raw('tr');for(const [key]of columns){const value=typeof key==='function'?key(item):item[key];const td=raw('td');if(value instanceof Node)td.append(value);else td.textContent=value==null?'':String(value);tr.append(td);}if(action){const td=raw('td');action(td,item);tr.append(td);}body.append(tr);}table.append(head,body);wrap.append(table);box.append(wrap);return table;}
function field(form,name,label,opts={}){const {value='',type='text',required=false,options=null,min=null,max=null}=opts,lab=raw('label',null,type==='checkbox'?'checkbox':''),caption=copy('span',label);let input;
if(options){input=raw('select');for(const o of options){const option=opts.rawOptions?raw('option',o.label):copy('option',o.label);option.value=String(o.value);input.append(option);}}else if(type==='textarea'||type==='json'){input=raw('textarea');}else{input=raw('input');input.type=type;}
input.name=name;input.required=required;if(min!==null)input.min=String(min);if(max!==null)input.max=String(max);if(opts.step)input.step=opts.step;if(opts.placeholder){input.dataset.tPlaceholder=opts.placeholder;input.placeholder=t(opts.placeholder);}if(opts.maxLength)input.maxLength=opts.maxLength;
if(type==='checkbox'){input.checked=!!value;lab.append(input,caption);}else{input.value=type==='json'?JSON.stringify(value??{},null,2):String(value??'');lab.append(caption,input);}form.append(lab);return input;}
const data=form=>Object.fromEntries(new FormData(form));
function dialog(title,build){$('editorTitle').textContent=t(title);$('editorTitle').dataset.t=title;$('editorContent').replaceChildren();$('editorError').textContent='';build($('editorContent'));if(!$('editor').open)$('editor').showModal();translate();}
function submit(form,label,action,after=null){const b=copy('button',label);b.type='submit';form.append(b);form.addEventListener('submit',async e=>{e.preventDefault();b.disabled=true;try{const result=await action();if(after)await after(result);else{$('editor').close();await refresh(false);await render(state.page);$('message').textContent=t('Saved.');}}catch(e){error(e);}finally{if(b.isConnected)b.disabled=false;}});return b;}
const has=(module,action='view')=>state.me?.capabilities?.[module]?.includes(action)||false;
function applyTheme(){const p=state.me?.preferences;if(!p)return;for(const [key,value]of Object.entries(p.tokens||{}))if(['background','surface','text','muted','accent','border'].includes(key)&&/^#[a-fA-F0-9]{6}$/.test(value))document.documentElement.style.setProperty('--'+key,value);const accent=p.accent||p.tokens.accent;if(/^#[a-fA-F0-9]{6}$/.test(accent)){document.documentElement.style.setProperty('--accent',accent);const values=[1,3,5].map(i=>parseInt(accent.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);const lum=values[0]*.2126+values[1]*.7152+values[2]*.0722;document.documentElement.style.setProperty('--on-accent',lum>.4?'#071d31':'#ffffff');}document.documentElement.style.fontSize=p.font_size+'px';document.body.classList.toggle('compact',p.density==='compact');}
async function setLanguage(locale){if(!supported(locale))return;state.locale=locale;try{localStorage.setItem('ukr-language',locale);}catch{}if(state.me){try{const p=state.me.preferences;state.me.preferences=await request('/preferences',{language:locale,theme_id:p.theme_id,accent:p.accent,font_size:p.font_size,density:p.density,version:p.version},'PUT');}catch(e){error(e);}}translate();window.dispatchEvent(new CustomEvent('ukr:portal-language',{detail:{language:locale}}));}
function picker(container){container.replaceChildren();const s=raw('select',null,'language-select');s.dataset.languagePicker='';s.setAttribute('aria-label',t('Language'));s.dataset.tLabel='Language';for(const [id,name]of languages){const o=raw('option',name+' · '+id.toUpperCase());o.value=id;s.append(o);}s.value=state.locale;s.addEventListener('change',()=>setLanguage(s.value));container.append(s);}
const customerMenu=[['dashboard','Dashboard'],['shipments','My Shipments'],['booking','Booking'],['requests','Request Service'],['pricing','Pricing'],['china_payment','Pay for my cargo in China'],['invoices','Invoices & Payments'],['fulfilment','Fulfilment'],['documents','Documents'],['feedback','Feedback'],['profile','Profile & Settings'],['company','Company account'],['members','Authorised users'],['appearance','Appearance']];
function navigation(){const nav=$('nav');nav.replaceChildren();let list=state.kind==='staff'?[...(state.me.menu||[]).map(m=>[m.id,m.label]),...(has('exchange_rates')?[['exchange_rates','Currencies & Exchange Rates']]:[]),...(has('customers')?[['customers','Customers']]:[]),['appearance','Appearance']]:customerMenu;
for(const [key,label]of list){const b=button(label,async()=>{state.page=key;await render(key);nav.querySelectorAll('button').forEach(n=>n.removeAttribute('aria-current'));b.setAttribute('aria-current','page');document.querySelector('.sidebar').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');},'');if(key===state.page)b.setAttribute('aria-current','page');nav.append(b);}picker($('appLanguage'));$('identity').textContent=state.me.user.name+' · '+state.me.user.email;}
async function refresh(useSaved=true){const result=await request('/me');if(result.user.kind!==state.kind)throw Object.assign(Error('wrong_portal'),{code:'wrong_portal'});state.me=result;state.csrf=result.csrf;if(useSaved)state.locale=result.preferences?.language||state.locale;applyTheme();translate();navigation();return result;}
async function render(page){state.page=page;const screen=screens.get((state.kind==='customer'?'customer:':'staff:')+page)||screens.get(page);if(!screen){const box=clear(customerMenu.find(([id])=>id===page)?.[1]||state.me?.menu?.find(m=>m.id===page)?.label||page);empty(box,'This service is not available. Contact UKR.');return;}await screen();translate();}
async function entered(){await refresh();$('authView').hidden=true;$('appView').hidden=false;state.page=state.kind==='staff'?'overview':'dashboard';await render(state.page);}
async function testMail(){try{const result=await request('/auth/test-outbox');$('testMail').hidden=false;$('testBody').textContent=result.messages.map(m=>m.text).join('\n');}catch{$('testMail').hidden=true;}}
let action=null,actionToken=null,cooldownTimer=null;const fragment=location.hash.match(/^#(setup|invite|reset)=([A-Za-z0-9_-]+)$/);if(fragment&&state.kind==='staff'){action=fragment[1];actionToken=fragment[2];history.replaceState(null,'',location.pathname);}
function cooldown(seconds=60){if(cooldownTimer)clearInterval(cooldownTimer);const end=Date.now()+seconds*1000;const update=()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));$('resend').disabled=left>0;$('resend').textContent=left?t('Request another code')+' ('+left+')':t('Request another code');if(!left){clearInterval(cooldownTimer);cooldownTimer=null;}};update();cooldownTimer=setInterval(update,1000);}
async function start(){translate();picker($('languagePicker'));$('passwordLabel').hidden=state.kind!=='staff';$('loginForm').elements.password.required=state.kind==='staff';if(action){$('setupNameLabel').hidden=action!=='setup';$('loginForm').elements.name.required=action==='setup';$('authTitle').textContent=action==='setup'?'Set up owner access':action==='invite'?'Activate staff account':'Reset password';}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector('button[type=submit]');b.disabled=true;$('authError').textContent='';try{const values=data(form);if(action){const response=await fetch('/api/'+({setup:'setup',invite:'accept-invite',reset:'reset-password'}[action]),{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,token:actionToken})});const out=await response.json();if(!response.ok)throw Error(out.error||'service_unavailable');action=null;actionToken=null;form.reset();$('authMessage').textContent=t('Account updated. Sign in again.');$('setupNameLabel').hidden=true;return;}
await request('/auth/start',{kind:state.kind,email:values.email,password:state.kind==='staff'?values.password:undefined,language:state.locale});form.elements.password.value='';form.hidden=true;$('otpForm').hidden=false;$('authMessage').textContent=t('verification_requested');cooldown(60);await testMail();$('otpForm').elements.code.focus();}catch(e){error(e);}finally{b.disabled=false;}});
$('otpForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector('button[type=submit]');b.disabled=true;try{const result=await request('/auth/verify',{code:form.elements.code.value});form.reset();state.csrf=result.csrf;if(result.kind!==state.kind){location.href=result.kind==='staff'?'/staff/':'/customer/';return;}await entered();}catch(e){error(e);}finally{b.disabled=false;}});
$('resend').addEventListener('click',async()=>{try{await request('/auth/resend',{});cooldown(60);await testMail();}catch(e){error(e);}});$('changeEmail').addEventListener('click',()=>{$('otpForm').hidden=true;$('loginForm').hidden=false;$('testMail').hidden=true;$('authError').textContent='';});$('closeEditor').addEventListener('click',()=>$('editor').close());$('menuToggle').addEventListener('click',()=>{const open=document.querySelector('.sidebar').classList.toggle('open');$('menuToggle').setAttribute('aria-expanded',String(open));});$('logout').addEventListener('click',async()=>{try{await request('/logout',{});}finally{location.reload();}});
document.addEventListener('invalid',event=>{const n=event.target;if(n.setCustomValidity)n.setCustomValidity(t(n.validity.typeMismatch?'Enter a valid email address.':'Complete this field.'));},true);document.addEventListener('input',event=>event.target.setCustomValidity?.(''),true);document.addEventListener('change',event=>event.target.setCustomValidity?.(''),true);
if(!action)try{await entered();}catch(e){if(e.status!==401)error(e);}}
window.UKRPortal=Object.freeze({state,$,t,raw,copy,button,field,data,submit,dialog,clear,empty,panel,table,has,request,refresh,render,translate,languages,register:(name,fn)=>screens.set(name,fn),error,formatDate:value=>value?new Intl.DateTimeFormat(state.locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):t('Not available')});
window.addEventListener('unhandledrejection',e=>{error(e.reason||Error('service_unavailable'));});document.addEventListener('DOMContentLoaded',start,{once:true});
})();
