import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {addLanguageShell} from '../site/i18n/build.mjs';
import {addDraftCopy,columns,rows} from '../preview/language-copy.mjs';
const require=createRequire(import.meta.url),L=require('../site/i18n/languages.js');
test('approved order and native names',()=>{assert.deepEqual(L.languages.map(l=>l.id),['en','ar','ru','fr','ur','hi','zh']);assert.ok(L.languages.every(l=>l.name&&l.flag&&l.code));});
test('only Arabic and Urdu are RTL',()=>assert.deepEqual(L.languages.filter(l=>l.dir==='rtl').map(l=>l.id),['ar','ur']));
test('normalizes supported browser regional and script tags',()=>{for(const [input,id]of [['en-GB','en'],['ar-AE','ar'],['ru-RU','ru'],['fr-CA','fr'],['ur-PK','ur'],['hi-IN','hi'],['zh-Hans-CN','zh'],['zh_Hant_TW','zh'],['en-US-u-nu-latn','en']])assert.equal(L.normalize(input),id);});
test('rejects unsupported and malicious identifiers',()=>{for(const value of ['de-DE','xx','../../ru','en<script>','',null,{},'en;x=1'])assert.equal(L.normalize(value),null);});
test('explicit query wins over saved/browser',()=>assert.equal(L.resolve({search:'?lang=en',pathname:'/ar/',saved:'ru',browser:['hi']}).id,'en'));
test('explicit localized path wins over saved/browser',()=>assert.equal(L.resolve({pathname:'/fr/contact.html',saved:'ru',browser:['ar']}).id,'fr'));
test('manual preference wins over browser',()=>assert.deepEqual(L.resolve({saved:'ur',browser:['en-GB']}),{id:'ur',source:'saved'}));
test('unsupported first browser choice falls through list',()=>assert.deepEqual(L.resolve({browser:['de-DE','zh-CN','en']}),{id:'zh',source:'browser'}));
test('English fallback',()=>assert.deepEqual(L.resolve({browser:['de-DE']}),{id:'en',source:'fallback'}));
test('storage disabled is nonfatal and stores only locale',()=>{const failing={getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}};assert.equal(L.readSaved(failing),null);assert.equal(L.save(failing,'fr'),false);const entries=[];assert.equal(L.save({setItem(...args){entries.push(args);}},'hi'),true);assert.deepEqual(entries,[[L.storageKey,'hi']]);});
test('public URLs preserve path, query and hash',()=>{const next=new URL(L.urlFor('https://ukr.test/ar/shipping.html?origin=China&weight=20#review','fr'));assert.equal(next.pathname,'/fr/shipping.html');assert.equal(next.searchParams.get('origin'),'China');assert.equal(next.searchParams.get('weight'),'20');assert.equal(next.searchParams.get('lang'),'fr');assert.equal(next.hash,'#review');});
test('English switch explicitly remains English',()=>assert.equal(L.urlFor('https://ukr.test/hi/','en'),'https://ukr.test/?lang=en'));
test('inline switch keeps knowledge article path and CBM query',()=>{const next=new URL(L.urlFor('https://ukr.test/knowledge/cbm-calculator.html?cbm=5#result','ar','inline'));assert.equal(next.pathname,'/knowledge/cbm-calculator.html');assert.equal(next.searchParams.get('cbm'),'5');assert.equal(next.hash,'#result');});
test('invalid locale and protocols cannot become navigation',()=>{assert.throws(()=>L.urlFor('https://ukr.test/','de'));assert.throws(()=>L.urlFor('javascript:alert(1)','en'));});
test('page injection idempotent and explicitly scoped',()=>{const html='<html lang="en"><head></head><body>Keep original artwork</body></html>';const out=addLanguageShell(html,{mode:'inline',preview:true});assert.equal(addLanguageShell(out),out);assert.ok(out.includes('data-ukr-language-mode="inline"'));assert.ok(out.includes('Keep original artwork'));assert.ok(out.includes('/i18n/preview-ui.js'));});
test('all new draft strings have all seven translations',()=>{const catalog={},keys={};addDraftCopy(catalog,keys);assert.deepEqual(columns,['en','ar','ru','fr','ur','hi','zh']);assert.ok(rows.length>=70);for(const id of columns)assert.equal(Object.keys(catalog[id]).length,rows.length);assert.equal(keys['Company name'],'field.company');});
