import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {randomBytes,createHash} from 'node:crypto';
import {reviewConfig,issueGate,validGate,initializeReview,reviewHandler,REVIEW_SCHEMA} from '../services/staff/review-gateway.mjs';
import {openDatabase} from '../services/staff/phase1/db.mjs';
import {createHandler,hashPassword,verifyPassword} from '../services/staff/server.mjs';
const key=randomBytes(32).toString('base64url'),digest=v=>createHash('sha256').update(v).digest('hex');
const configuration=(origin='http://127.0.0.1:4799')=>({NODE_ENV:'test',AUTH_TEST_MODE:'true',PORTAL_REVIEW_ENABLED:'true',APP_ORIGIN:origin,DATABASE_URL:process.env.TEST_DATABASE_URL,PORTAL_REVIEW_SCHEMA:REVIEW_SCHEMA,PORTAL_REVIEW_ACCESS_HASH:digest(key),PORTAL_REVIEW_KEY:randomBytes(32).toString('hex'),PORTAL_REVIEW_EXPIRES_AT:new Date(Date.now()+86400000).toISOString()});
test('fixed review authentication cannot activate in production or an arbitrary host',()=>{const env=configuration();for(const change of [{NODE_ENV:'production'},{AUTH_TEST_MODE:'false'},{PORTAL_REVIEW_SCHEMA:'public'},{APP_ORIGIN:'https://ukrshipping.com'},{PORTAL_REVIEW_EXPIRES_AT:'2000-01-01'},{PORTAL_REVIEW_ACCESS_HASH:''}])assert.throws(()=>reviewConfig({...env,...change}));});
test('gate expires, detects tampering and is not code 1234',()=>{const c=reviewConfig(configuration()),gate=issueGate(c);assert.equal(validGate(c,gate),true);for(const value of ['1234',key,gate+'x','not.a.gate',''])assert.equal(validGate(c,value),false);assert.equal(validGate(c,gate,c.expires+1),false);});
test('private review uses real isolated SQL and test login journey',async t=>{
 const url=process.env.TEST_DATABASE_URL;if(!url||!new URL(url).pathname.includes('test'))throw Error('Disposable test database is required');
 const root=await openDatabase(url);await root.query('DROP SCHEMA IF EXISTS '+REVIEW_SCHEMA+' CASCADE');await root.query('CREATE SCHEMA '+REVIEW_SCHEMA);await root.query('CREATE TABLE IF NOT EXISTS public.review_public_sentinel(value TEXT)');await root.query("INSERT INTO public.review_public_sentinel VALUES('keep')");
 const store=await openDatabase(url,{options:'-c search_path='+REVIEW_SCHEMA});const server=http.createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port,env=configuration(origin),c=reviewConfig(env);
 const jars={staff:{},customer:{},outsider:{}};let csrfStaff,csrfCustomer,booking;
 const send=async(jar,path,data,csrf)=>{const r=await fetch(origin+path,{method:data?'POST':'GET',headers:{Origin:origin,...(data?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),Cookie:Object.entries(jar).map(([k,v])=>k+'='+v).join('; ')},body:data?JSON.stringify(data):undefined});for(const cookie of r.headers.getSetCookie()){const value=cookie.split(';')[0],at=value.indexOf('=');jar[value.slice(0,at)]=value.slice(at+1);}return {status:r.status,body:await r.json()};};
 try{
  await t.test('migrations only run in the fixed isolated schema and are idempotent',async()=>{await assert.rejects(initializeReview(root),/isolated schema/);await initializeReview(store);await initializeReview(store);assert.equal((await root.query('SELECT count(*)::int n FROM public.review_public_sentinel')).rows[0].n,1);assert.equal((await store.query('SELECT count(*)::int n FROM staff_users')).rows[0].n,0);});
  const handler=await reviewHandler({store,c,env,passwords:{hashPassword,verifyPassword},legacyFactory:createHandler});server.on('request',handler);
  await t.test('anonymous email plus 1234 never opens a session or private API',async()=>{assert.equal((await send(jars.outsider,'/api/portal/auth/start',{kind:'customer',email:'customer@ukr.test'})).status,401);assert.equal((await send(jars.outsider,'/api/portal/auth/verify',{code:'1234'})).status,401);assert.equal((await send(jars.outsider,'/api/review/unlock',{key:'1234'})).status,403);assert.equal((await send(jars.outsider,'/api/portal/bookings')).status,401);});
  await t.test('private key grants access but creates no account until owner setup',async()=>{const r=await send(jars.staff,'/api/review/unlock',{key});assert.equal(r.status,200);assert.equal(r.body.needsSetup,true);assert.equal((await store.query('SELECT count(*)::int n FROM staff_users')).rows[0].n,0);assert.equal((await send(jars.staff,'/api/review/setup',{token:key,email:'bayan@ukrshipping.com',name:'Isolated review owner',password:'Testing-owner-password-48269'})).status,201);});
  await t.test('staff password and code are both checked',async()=>{await send(jars.outsider,'/api/review/unlock',{key});await send(jars.outsider,'/api/portal/auth/start',{kind:'staff',email:'bayan@ukrshipping.com',password:'Wrong-password-4812'});assert.equal((await send(jars.outsider,'/api/portal/auth/verify',{code:'1234'})).status,400);await store.query("UPDATE otp_codes SET resend_after=now()-interval '1 second' WHERE kind='staff'");assert.equal((await send(jars.staff,'/api/portal/auth/start',{kind:'staff',email:'bayan@ukrshipping.com',password:'Testing-owner-password-48269'})).status,202);assert.equal((await send(jars.staff,'/api/portal/auth/verify',{code:'9999'})).status,400);const r=await send(jars.staff,'/api/portal/auth/verify',{code:'1234'});assert.equal(r.status,200);csrfStaff=r.body.csrf;assert.equal((await send(jars.staff,'/api/portal/me')).body.user.kind,'staff');assert.equal((await send(jars.staff,'/api/portal/auth/verify',{code:'1234'})).status,400);});
  await t.test('customer test sign-in refuses real customer addresses and requires the gate',async()=>{await send(jars.customer,'/api/review/unlock',{key});assert.equal((await send(jars.customer,'/api/portal/auth/start',{kind:'customer',email:'real@example.com'})).status,400);assert.equal((await send(jars.customer,'/api/portal/auth/start',{kind:'customer',email:'customer@ukr.test'})).status,202);const r=await send(jars.customer,'/api/portal/auth/verify',{code:'1234'});assert.equal(r.status,200);csrfCustomer=r.body.csrf;assert.equal((await send(jars.customer,'/api/portal/settings/users')).status,403);});
  await t.test('test booking is durable and visible through the shared customer and staff APIs',async()=>{assert.equal((await send(jars.customer,'/api/portal/customer/company',{legal_name:'Review test company',phone:'+000000000',country_code:'AE',address:'Test address',domain:'',tax_number:''},csrfCustomer)).status,200);const r=await send(jars.customer,'/api/portal/bookings',{service:'air_ddp',origin:'China',destination:'UAE',origin_country:'CN',destination_country:'AE',legal_owner_name:'Review test company',phone:'+000000000',cargo_summary:'Synthetic test cartons',request_key:randomBytes(18).toString('hex')},csrfCustomer);assert.equal(r.status,200,JSON.stringify(r.body));booking=r.body.booking;assert.match(booking.code,/^UKR-/);assert.equal((await send(jars.staff,'/api/portal/bookings')).body.total,1);assert.equal((await send(jars.customer,'/api/portal/bookings/'+booking.id)).body.booking.code,booking.code);assert.equal((await root.query('SELECT count(*)::int n FROM public.review_public_sentinel')).rows[0].n,1);});
  await t.test('another customer cannot read the booking; no outbox message is actually sent',async()=>{await send(jars.outsider,'/api/portal/auth/start',{kind:'customer',email:'second.customer@ukr.test'});await send(jars.outsider,'/api/portal/auth/verify',{code:'1234'});assert.notEqual((await send(jars.outsider,'/api/portal/bookings/'+booking.id)).status,200);const n=await store.query("SELECT count(*)::int n FROM email_outbox WHERE status='sent'");assert.equal(n.rows[0].n,0);});
 }finally{await new Promise(resolve=>server.close(resolve));await store.close();await root.query('DROP SCHEMA '+REVIEW_SCHEMA+' CASCADE');await root.query('DROP TABLE public.review_public_sentinel');await root.close();}
});
