import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {writeFile,mkdir} from 'node:fs/promises';
import {testStore} from '../services/staff/store.mjs';
import {createHandler,hashPassword} from '../services/staff/server.mjs';
import {today} from '../services/staff/rates.mjs';
import {makeWorkbook,parseWorkbook} from '../services/staff/rate-workbook.mjs';
import {validateRoute,resolveRoutes,magicCosts} from '../services/staff/routes.mjs';
const require=createRequire(new URL('../services/staff/package.json',import.meta.url));const ExcelJS=require('exceljs');
process.env.NODE_ENV='test';
const routeData={origin:'Ningbo, China',destination:'Jebel Ali, UAE',originCountry:'China',destinationCountry:'UAE',originAliases:['Ningbo'],destinationAliases:['Dubai','Dubai, UAE'],airOrigin:'NGB Airport',airDestination:'DXB Airport',active:true,products:['AIR','LCL','LCL_DDP','FCL20','FCL40','FCL45']};
test('route matching uses explicit aliases, exposes ambiguity and requires enabled services',()=>{const r={...validateRoute(routeData),id:'one'};assert.equal(resolveRoutes([r],{origin:'ningbo',destination:'Dubai'}).length,1);assert.equal(resolveRoutes([r],{origin:'Shanghai',destination:'Dubai'}).length,0);assert.equal(resolveRoutes([r,{...r,id:'two',origin:'Shanghai'}],{origin:'China',destination:'UAE'}).length,2);assert.throws(()=>validateRoute({...routeData,products:['bad']}));});
test('route catalog, Excel preview/commit, estimates and import economics',async t=>{
  const store=await testStore(),hash=await hashPassword('Local-test-only-482!');for(const role of ['super_admin','accounts'])await store.query('INSERT INTO staff_users (id,email,name,role,password_hash,active,created_at) VALUES ($1,$2,$1,$1,$3,1,$4)',[role,role+'@example.test',hash,Date.now()]);
  const server=http.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,publicOrigin='https://public.example.test';server.on('request',await createHandler({store,origin,publicOrigin,secure:false}));t.after(async()=>{await new Promise(r=>server.close(r));await store.close();});
  async function req(path,method='GET',data,account){const r=await fetch(origin+'/api'+path,{method,headers:{Origin:path.startsWith('/public')?publicOrigin:origin,...(data?{'Content-Type':'application/json'}:{}),...(account?{Cookie:account.cookie,'X-CSRF-Token':account.csrf}:{})},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')};}
  async function login(role){const r=await req('/login','POST',{email:role+'@example.test',password:'Local-test-only-482!'});return {cookie:r.cookie.split(';')[0],csrf:r.data.csrf};}const owner=await login('super_admin'),accounts=await login('accounts');
  let route,base64,wb,preview;
  await t.test('permanent route exists without any rates and roles restrict edits',async()=>{assert.equal((await req('/routes','POST',routeData,accounts)).status,403);const saved=await req('/routes','POST',routeData,owner);assert.equal(saved.status,200);route={...routeData,id:saved.data.id};const catalog=await req('/public/catalog');assert.equal(catalog.data.routes.length,1);const quick=await req('/public/quick','POST',{search:{origin:'Ningbo',destination:'Dubai',ready:today()}});assert.equal(quick.data.routes[0].options.length,6);assert.ok(quick.data.routes[0].options.every(x=>!x.available));});
  await t.test('Excel round trip preserves route IDs and rejects formulas',async()=>{const download=await req('/rate-workbook?week='+today(),'GET',null,owner);assert.equal(download.status,200);wb=new ExcelJS.Workbook();await wb.xlsx.load(Buffer.from(download.data.base64,'base64'));const ws=wb.getWorksheet('Rates');assert.equal(ws.rowCount,7);for(let n=2;n<=7;n++){const r=ws.getRow(n);r.getCell(10).value=n===2?10:100;r.getCell(12).value=20;r.getCell(13).value=25;r.getCell(17).value=30000;r.getCell(18).value=200;r.getCell(19).value=n===5?33:n===6?67:n===7?85:0;r.getCell(20).value='Freight only';r.getCell(21).value='Duty VAT delivery';r.getCell(22).value='auto';if(n===4){r.getCell(24).value='Dubai city; goods value subject to final approval';r.getCell(25).value='YES';}}const bytes=Buffer.from(await wb.xlsx.writeBuffer());base64=bytes.toString('base64');assert.equal((await parseWorkbook(bytes)).length,6);ws.getRow(2).getCell(10).value={formula:'1+1',result:2};await assert.rejects(()=>wb.xlsx.writeBuffer().then(b=>parseWorkbook(Buffer.from(b))),/Formulas/);ws.getRow(2).getCell(10).value=10;await mkdir('test-output',{recursive:true});await writeFile('test-output/UKR-routes-test.xlsx',bytes);});
  await t.test('invalid rows do not save; valid preview is private and atomic publish is idempotent',async()=>{assert.equal((await req('/rate-workbook?week='+today(),'GET',null,accounts)).status,403);const ws=wb.getWorksheet('Rates');ws.getRow(3).getCell(12).value=-1;const bad=await req('/rate-workbook/preview','POST',{base64:Buffer.from(await wb.xlsx.writeBuffer()).toString('base64')},owner);assert.equal(bad.data.errors[0].row,3);assert.equal((await req('/rates','GET',null,owner)).data.rates.length,0);ws.getRow(3).getCell(12).value=20;preview=await req('/rate-workbook/preview','POST',{base64},owner);assert.equal(preview.data.rows.length,6);assert.equal(preview.data.rows[0].unitPrice,12);assert.equal((await req('/rates','GET',null,owner)).data.rates.length,0);const publish=await req('/rate-workbook/commit','POST',{importId:preview.data.importId,publish:true},owner);assert.equal(publish.status,200,JSON.stringify(publish.data));assert.equal(publish.data.saved,6);assert.equal((await req('/rate-workbook/commit','POST',{importId:preview.data.importId,publish:true},owner)).data.alreadySaved,true);});
  await t.test('quick comparison never leaks cost and AIR enforces 5 kg; EXW is included once',async()=>{const quick=await req('/public/quick','POST',{search:{origin:'Ningbo',destination:'Dubai',ready:today()}});assert.equal(quick.data.routes[0].options.length,6);assert.equal(quick.data.routes[0].options[0].minimumUnits,5);assert.equal(JSON.stringify(quick.data).includes('buyRate'),false);const search={origin:'Ningbo',destination:'Dubai',ready:today(),mode:'air',cargoType:'cartons',weight:1,cbm:.01,exw:true};const res=await req('/public/estimate','POST',{search});assert.equal(res.status,200);assert.equal(res.data.offers[0].quantity,5);assert.equal(res.data.offers[0].total,85);assert.equal(res.data.offers[0].bookingMode,'review');});
  await t.test('DDP final goods-value approval prevents automatic acceptance; 40ft sizes share tariff',async()=>{const search={origin:'Ningbo',destination:'Dubai',ready:today(),mode:'sea',cargoType:'cartons',weight:100,cbm:1};const offers=(await req('/public/estimate','POST',{search})).data.offers,ddp=offers.find(o=>o.product==='LCL_DDP');assert.equal(ddp.bookingMode,'review');assert.match(ddp.approvalNote,/goods value/);const booking=await req('/public/bookings','POST',{search,details:{commodity:'test',packages:'1',contactName:'Test',contactEmail:'ddp@example.test',consent:true,stackable:true,batteries:false,dangerous:false,oversized:false},rateId:ddp.rateId,rateVersion:ddp.rateVersion,requestKey:randomUUID()});assert.equal(booking.data.status,'requested');for(const size of ['40GP','40HC','45HC']){const r=await req('/public/estimate','POST',{search:{...search,cargoType:'container',containerSize:size,containers:1}});assert.equal(r.data.offers.length,1);assert.equal(r.data.offers[0].product,size==='45HC'?'FCL45':'FCL40');}});
  await t.test('Magic tool compares actual route rates, currency, profit and 85% container threshold',async()=>{const search={routeId:route.id,origin:route.origin,destination:route.destination,ready:today()},items={itemCost:5,quantity:29,length:100,width:100,height:100,weight:1,currency:'USD',selling:50,extras:29};const out=await req('/public/magic','POST',{search,items});assert.equal(out.status,200);assert.equal(out.data.cbm,29);const fcl=out.data.options.find(o=>o.product==='FCL20');assert.equal(fcl.fill,87.9);assert.equal(fcl.shippedPerItem,10.14);assert.equal(fcl.profitPerItem,39.86);const smaller=await req('/public/magic','POST',{search,items:{...items,quantity:28}});assert.equal(smaller.data.options.some(o=>o.product.startsWith('FCL')),false);const different=await req('/public/magic','POST',{search,items:{...items,currency:'AED'}});assert.equal(different.data.options.length,0);});
  await t.test('stale Excel update fails; deactivating route removes discovery and estimate availability',async()=>{const downloaded=await req('/rate-workbook?week='+today(),'GET',null,owner);const prev=await req('/rate-workbook/preview','POST',{base64:downloaded.data.base64},owner);const old=(await req('/rates','GET',null,owner)).data.rates[0];assert.equal((await req('/rates/'+old.id,'PATCH',{...old,buyRate:old.buyRate+1},owner)).status,200);const stale=await req('/rate-workbook/commit','POST',{importId:prev.data.importId,publish:true},owner);assert.equal(stale.status,409);assert.equal((await req('/routes/'+route.id,'PATCH',{...routeData,active:false,version:1},owner)).status,200);const quick=await req('/public/quick','POST',{search:{origin:'Ningbo',destination:'Dubai'}});assert.equal(quick.data.routes.length,0);const quote=await req('/public/estimate','POST',{search:{origin:route.origin,destination:route.destination,ready:today(),mode:'sea',cargoType:'cartons',weight:100,cbm:1}});assert.equal(quote.data.offers.length,0);});
});
