-- Additive portal foundation. Applied files are checked by the migration ledger.
DO $migration$
DECLARE definition RECORD;
 common TEXT := $metadata$id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by UUID REFERENCES users(id) ON DELETE RESTRICT, deleted_at TIMESTAMPTZ$metadata$;
BEGIN
 FOR definition IN SELECT * FROM (VALUES
(0,'users',$columns$email TEXT NOT NULL UNIQUE CHECK (email = lower(email) AND length(email) <= 254), display_name TEXT NOT NULL DEFAULT '', kind TEXT NOT NULL CHECK (kind IN ('staff','customer')), state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','invited','active','disabled')), staff_user_id TEXT UNIQUE REFERENCES staff_users(id) ON DELETE RESTRICT, legacy_customer_id TEXT UNIQUE REFERENCES booking_lab_customers(id) ON DELETE RESTRICT, department TEXT NOT NULL DEFAULT '', country_code CHAR(2) CHECK (country_code ~ '^[A-Z]{2}$'), preferred_language TEXT NOT NULL DEFAULT 'en' CHECK (preferred_language IN ('en','ar','ru','fr','ur','hi','zh')), auth_version INTEGER NOT NULL DEFAULT 1 CHECK (auth_version > 0), last_login_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1, CHECK (kind='staff' OR staff_user_id IS NULL)$columns$),
(1,'roles',$columns$code TEXT NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]{1,50}$'), name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', system_role BOOLEAN NOT NULL DEFAULT false, version INTEGER NOT NULL DEFAULT 1$columns$),
(2,'permissions',$columns$code TEXT NOT NULL UNIQUE, module TEXT NOT NULL, action TEXT NOT NULL CHECK (action IN ('view','create','edit','approve','delete','export')), UNIQUE(module,action)$columns$),
(3,'role_permissions',$columns$role_id UUID NOT NULL REFERENCES roles(id) ON DELETE RESTRICT, permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE RESTRICT, scope TEXT NOT NULL CHECK (scope IN ('all','assigned','warehouse','self')), UNIQUE(role_id,permission_id)$columns$),
(4,'user_roles',$columns$user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, role_id UUID NOT NULL REFERENCES roles(id) ON DELETE RESTRICT, UNIQUE(user_id,role_id)$columns$),
(5,'currencies',$columns$code CHAR(3) NOT NULL UNIQUE CHECK (code ~ '^[A-Z]{3}$'), name TEXT NOT NULL, symbol TEXT NOT NULL DEFAULT '', minor_units INTEGER NOT NULL DEFAULT 2 CHECK (minor_units BETWEEN 0 AND 4), active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1$columns$),
(6,'companies',$columns$code TEXT NOT NULL UNIQUE, legal_name TEXT NOT NULL, licence_number TEXT NOT NULL DEFAULT '', trn TEXT NOT NULL DEFAULT '', address TEXT NOT NULL DEFAULT '', country_code CHAR(2) NOT NULL CHECK (country_code ~ '^[A-Z]{2}$'), phone TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', sales_email TEXT NOT NULL DEFAULT '', website TEXT NOT NULL DEFAULT '', logo_path TEXT NOT NULL DEFAULT '/logo.svg', bank_accounts JSONB NOT NULL DEFAULT '[]', base_currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK (base_currency ~ '^[A-Z]{3}$'), financial_year_start_month INTEGER NOT NULL DEFAULT 1 CHECK (financial_year_start_month BETWEEN 1 AND 12), invoice_prefix TEXT NOT NULL DEFAULT 'UKR', pdf_footer TEXT NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1$columns$),
(7,'customers',$columns$user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT, phone TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','declined','disabled')), account_owner_id UUID REFERENCES users(id) ON DELETE RESTRICT, version INTEGER NOT NULL DEFAULT 1$columns$),
(8,'customer_companies',$columns$legal_name TEXT NOT NULL, owner_customer_id UUID REFERENCES customers(id) ON DELETE RESTRICT, status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','declined','disabled')), domain TEXT NOT NULL DEFAULT '', domain_verified_at TIMESTAMPTZ, domain_verified_by UUID REFERENCES users(id) ON DELETE RESTRICT, phone TEXT NOT NULL DEFAULT '', address TEXT NOT NULL DEFAULT '', country_code CHAR(2) CHECK (country_code ~ '^[A-Z]{2}$'), tax_number TEXT NOT NULL DEFAULT '', account_owner_id UUID REFERENCES users(id) ON DELETE RESTRICT, legacy_company_id TEXT UNIQUE REFERENCES booking_lab_companies(id) ON DELETE RESTRICT, version INTEGER NOT NULL DEFAULT 1$columns$),
(9,'customer_memberships',$columns$customer_id UUID NOT NULL UNIQUE REFERENCES customers(id) ON DELETE RESTRICT, customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, role TEXT NOT NULL CHECK (role IN ('owner','staff','view_only')), status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','disabled')), approved_by UUID REFERENCES users(id) ON DELETE RESTRICT, approved_at TIMESTAMPTZ, invited_by UUID REFERENCES users(id) ON DELETE RESTRICT, version INTEGER NOT NULL DEFAULT 1, UNIQUE(customer_id,customer_company_id)$columns$),
(10,'customer_invitations',$columns$customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, email TEXT NOT NULL CHECK(email=lower(email)), member_role TEXT NOT NULL CHECK(member_role IN ('staff','view_only')), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','revoked')), expires_at TIMESTAMPTZ NOT NULL, UNIQUE(customer_company_id,email)$columns$),
(11,'warehouses',$columns$code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, country_code CHAR(2) NOT NULL CHECK (country_code ~ '^[A-Z]{2}$'), city TEXT NOT NULL, address TEXT NOT NULL DEFAULT '', operator_name TEXT NOT NULL DEFAULT '', services JSONB NOT NULL DEFAULT '[]', tabs JSONB NOT NULL DEFAULT '[]', active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1$columns$),
(12,'user_warehouses',$columns$user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, UNIQUE(user_id,warehouse_id)$columns$),
(13,'user_currencies',$columns$user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), UNIQUE(user_id,currency)$columns$),
(14,'accounts',$columns$code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, parent_id UUID REFERENCES accounts(id) ON DELETE RESTRICT, account_type TEXT NOT NULL CHECK(account_type IN ('asset','liability','equity','income','expense')), currency CHAR(3) REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1, CHECK(parent_id IS NULL OR parent_id <> id)$columns$),
(15,'products_services',$columns$code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, parent_id UUID REFERENCES products_services(id) ON DELETE RESTRICT, account_id UUID REFERENCES accounts(id) ON DELETE RESTRICT, kind TEXT NOT NULL CHECK(kind IN ('group','service','charge','product')), unit TEXT NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1, CHECK(parent_id IS NULL OR parent_id <> id)$columns$),
(16,'services',$columns$code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, configuration JSONB NOT NULL DEFAULT '{}', active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1$columns$),
(17,'routes',$columns$code TEXT NOT NULL UNIQUE, service_id UUID NOT NULL REFERENCES services(id) ON DELETE RESTRICT, origin_country CHAR(2) NOT NULL CHECK(origin_country ~ '^[A-Z]{2}$'), destination_country CHAR(2) NOT NULL CHECK(destination_country ~ '^[A-Z]{2}$'), origin TEXT NOT NULL, destination TEXT NOT NULL, origin_locode CHAR(5), destination_locode CHAR(5), status TEXT NOT NULL DEFAULT 'request_only' CHECK(status IN ('request_only','online_rate','staff_confirm','suspended','unavailable')), rules JSONB NOT NULL DEFAULT '{}', version INTEGER NOT NULL DEFAULT 1$columns$),
(18,'themes',$columns$code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, tokens JSONB NOT NULL, active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1$columns$),
(19,'user_preferences',$columns$user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT, language TEXT NOT NULL DEFAULT 'en' CHECK(language IN ('en','ar','ru','fr','ur','hi','zh')), theme_id UUID NOT NULL REFERENCES themes(id) ON DELETE RESTRICT, accent CHAR(7) CHECK(accent ~ '^#[a-fA-F0-9]{6}$'), font_size INTEGER NOT NULL DEFAULT 16 CHECK(font_size BETWEEN 12 AND 24), density TEXT NOT NULL DEFAULT 'comfortable' CHECK(density IN ('compact','comfortable')), version INTEGER NOT NULL DEFAULT 1$columns$),
(20,'settings',$columns$key TEXT NOT NULL UNIQUE, value JSONB NOT NULL, version INTEGER NOT NULL DEFAULT 1$columns$),
(21,'sessions',$columns$user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, kind TEXT NOT NULL CHECK(kind IN ('staff','customer')), token_hash CHAR(64) NOT NULL UNIQUE, csrf_hash CHAR(64) NOT NULL, csrf_token_ciphertext TEXT NOT NULL, auth_version INTEGER NOT NULL, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, legacy_token_hash TEXT UNIQUE REFERENCES staff_sessions(token_hash) ON DELETE SET NULL$columns$),
(22,'otp_codes',$columns$challenge_hash CHAR(64) NOT NULL UNIQUE, email TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('staff','customer')), user_id UUID REFERENCES users(id) ON DELETE RESTRICT, code_hash CHAR(64) NOT NULL, auth_version INTEGER, credential_hash CHAR(64), language TEXT NOT NULL DEFAULT 'en' CHECK(language IN ('en','ar','ru','fr','ur','hi','zh')), eligible BOOLEAN NOT NULL DEFAULT true, attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts BETWEEN 0 AND 5), expires_at TIMESTAMPTZ NOT NULL, resend_after TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ, invalidated_at TIMESTAMPTZ, test_mode BOOLEAN NOT NULL DEFAULT false$columns$),
(23,'auth_limits',$columns$key TEXT NOT NULL UNIQUE, hits INTEGER NOT NULL CHECK(hits>0), window_end TIMESTAMPTZ NOT NULL$columns$),
(24,'audit_log',$columns$actor_id UUID REFERENCES users(id) ON DELETE RESTRICT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, before_data JSONB, after_data JSONB, reason TEXT NOT NULL DEFAULT '', request_id UUID, status TEXT NOT NULL DEFAULT 'recorded' CHECK(status='recorded')$columns$),
(25,'email_templates',$columns$code TEXT NOT NULL, language TEXT NOT NULL CHECK(language IN ('en','ar','ru','fr','ur','hi','zh')), subject TEXT NOT NULL, body TEXT NOT NULL, variables JSONB NOT NULL DEFAULT '[]', approved BOOLEAN NOT NULL DEFAULT false, version INTEGER NOT NULL DEFAULT 1, UNIQUE(code,language)$columns$),
(26,'email_outbox',$columns$template_id UUID REFERENCES email_templates(id) ON DELETE RESTRICT, template_code TEXT NOT NULL, recipient TEXT NOT NULL, subject TEXT NOT NULL, body_ciphertext TEXT NOT NULL, language TEXT NOT NULL DEFAULT 'en', languages JSONB NOT NULL DEFAULT '["en"]', status TEXT NOT NULL DEFAULT 'held' CHECK(status IN ('held','queued','sending','accepted','failed','uncertain','cancelled')), sensitive BOOLEAN NOT NULL DEFAULT false, test_mode BOOLEAN NOT NULL DEFAULT false, dedupe_key TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ, available_at TIMESTAMPTZ NOT NULL DEFAULT now(), provider_message_id TEXT, claimed_at TIMESTAMPTZ, error_code TEXT$columns$),
(27,'mail_accounts',$columns$email TEXT NOT NULL UNIQUE, provider TEXT NOT NULL DEFAULT 'imap_smtp' CHECK(provider='imap_smtp'), imap_host TEXT NOT NULL DEFAULT '', imap_port INTEGER NOT NULL DEFAULT 993 CHECK(imap_port BETWEEN 1 AND 65535), smtp_host TEXT NOT NULL DEFAULT '', smtp_port INTEGER NOT NULL DEFAULT 465 CHECK(smtp_port BETWEEN 1 AND 65535), tls_mode TEXT NOT NULL DEFAULT 'tls' CHECK(tls_mode IN ('tls','starttls')), credentials_ciphertext TEXT, encryption_key_id TEXT, mode TEXT NOT NULL DEFAULT 'read_only' CHECK(mode IN ('read_only','disabled')), active BOOLEAN NOT NULL DEFAULT false, version INTEGER NOT NULL DEFAULT 1$columns$),
(28,'mail_account_users',$columns$mail_account_id UUID NOT NULL REFERENCES mail_accounts(id) ON DELETE RESTRICT, user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, access TEXT NOT NULL DEFAULT 'read' CHECK(access IN ('read','reply')), UNIQUE(mail_account_id,user_id)$columns$),
(29,'mail_messages',$columns$mail_account_id UUID NOT NULL REFERENCES mail_accounts(id) ON DELETE RESTRICT, provider_id TEXT NOT NULL, from_address TEXT NOT NULL, subject TEXT NOT NULL DEFAULT '', body_ciphertext TEXT NOT NULL, received_at TIMESTAMPTZ NOT NULL, UNIQUE(mail_account_id,provider_id)$columns$),
(30,'exchange_rate_rules',$columns$code TEXT NOT NULL UNIQUE, base_currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(base_currency ~ '^[A-Z]{3}$'), quote_currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(quote_currency ~ '^[A-Z]{3}$'), rate_type TEXT NOT NULL, timezone TEXT NOT NULL DEFAULT 'Asia/Dubai', due_time TIME NOT NULL DEFAULT '09:00', cutoff_time TIME NOT NULL DEFAULT '12:00', threshold_percent NUMERIC(18,4) NOT NULL DEFAULT 5 CHECK(threshold_percent>=0 AND threshold_percent<=100), fee_rules JSONB NOT NULL DEFAULT '[]', approver_role_id UUID NOT NULL REFERENCES roles(id) ON DELETE RESTRICT, active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1, CHECK(base_currency<>quote_currency), CHECK(cutoff_time>due_time), UNIQUE(base_currency,quote_currency,rate_type)$columns$),
(31,'rate_confirmations',$columns$rule_id UUID NOT NULL REFERENCES exchange_rate_rules(id) ON DELETE RESTRICT, proposed_rate NUMERIC(18,8) NOT NULL CHECK(proposed_rate>0), rate_date DATE NOT NULL, previous_id UUID, previous_rate NUMERIC(18,8), rule_version INTEGER NOT NULL, expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ$columns$),
(32,'exchange_rates',$columns$rule_id UUID NOT NULL REFERENCES exchange_rate_rules(id) ON DELETE RESTRICT, confirmation_id UUID NOT NULL UNIQUE REFERENCES rate_confirmations(id) ON DELETE RESTRICT, rate NUMERIC(18,8) NOT NULL CHECK(rate>0), rate_date DATE NOT NULL, valid_until TIMESTAMPTZ NOT NULL, status TEXT NOT NULL CHECK(status IN ('pending','active','returned','superseded','expired')), previous_id UUID REFERENCES exchange_rates(id) ON DELETE RESTRICT, approved_by UUID REFERENCES users(id) ON DELETE RESTRICT, approved_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1$columns$),
(33,'tax_rates',$columns$code TEXT NOT NULL UNIQUE, country_code CHAR(2) NOT NULL CHECK(country_code ~ '^[A-Z]{2}$'), region TEXT NOT NULL DEFAULT '', label TEXT NOT NULL, rate NUMERIC(18,4) NOT NULL CHECK(rate BETWEEN 0 AND 100), treatment TEXT NOT NULL CHECK(treatment IN ('standard','zero','exempt')), valid_from DATE NOT NULL, valid_to DATE, active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1, CHECK(valid_to IS NULL OR valid_to>=valid_from)$columns$),
(34,'bookings',$columns$code TEXT NOT NULL UNIQUE, source TEXT NOT NULL CHECK(source IN ('customer_portal','online_booking','staff_booking')), customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT, customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, service_id UUID NOT NULL REFERENCES services(id) ON DELETE RESTRICT, route_id UUID REFERENCES routes(id) ON DELETE RESTRICT, origin TEXT NOT NULL, destination TEXT NOT NULL, origin_country CHAR(2), destination_country CHAR(2), cargo_summary TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'submitted' CHECK(status IN ('submitted','accepted','goods_received','ready_to_ship','consolidated','ready_for_collection','in_transit','on_hold','arrived','customs_cleared','ready_for_delivery','out_for_delivery','delivered','cancelled','declined')), assignee_id UUID REFERENCES users(id) ON DELETE RESTRICT, agreement_snapshot JSONB, agreed_amount NUMERIC(18,4), currency CHAR(3) REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), rate_locked_at TIMESTAMPTZ, rate_change_reason TEXT NOT NULL DEFAULT '', eta TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1, CHECK((agreed_amount IS NULL)=(currency IS NULL)), CHECK(agreed_amount IS NULL OR agreed_amount>=0)$columns$),
(35,'booking_items',$columns$booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT, box_code TEXT NOT NULL UNIQUE, description TEXT NOT NULL DEFAULT '', quantity INTEGER NOT NULL CHECK(quantity>0), gross_kg NUMERIC(18,4) CHECK(gross_kg>=0), length_cm NUMERIC(18,4) CHECK(length_cm>0), width_cm NUMERIC(18,4) CHECK(width_cm>0), height_cm NUMERIC(18,4) CHECK(height_cm>0), hs_code TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1$columns$),
(36,'consolidations',$columns$code TEXT NOT NULL UNIQUE, service_id UUID NOT NULL REFERENCES services(id) ON DELETE RESTRICT, origin_warehouse_id UUID REFERENCES warehouses(id) ON DELETE RESTRICT, destination_warehouse_id UUID REFERENCES warehouses(id) ON DELETE RESTRICT, status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','ready','in_transit','arrived','closed')), version INTEGER NOT NULL DEFAULT 1$columns$),
(37,'consolidation_bookings',$columns$consolidation_id UUID NOT NULL REFERENCES consolidations(id) ON DELETE RESTRICT, booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT, UNIQUE(consolidation_id,booking_id)$columns$),
(38,'shipments',$columns$code TEXT NOT NULL UNIQUE, consolidation_id UUID REFERENCES consolidations(id) ON DELETE RESTRICT, booking_id UUID REFERENCES bookings(id) ON DELETE RESTRICT, carrier TEXT NOT NULL DEFAULT '', container_number TEXT NOT NULL DEFAULT '', vessel_flight TEXT NOT NULL DEFAULT '', carrier_reference TEXT NOT NULL DEFAULT '', origin TEXT NOT NULL, destination TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'planned' CHECK(status IN ('planned','in_transit','on_hold','arrived','delivered','cancelled')), etd TIMESTAMPTZ, atd TIMESTAMPTZ, eta TIMESTAMPTZ, ata TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1, CHECK(consolidation_id IS NOT NULL OR booking_id IS NOT NULL)$columns$),
(39,'shipment_events',$columns$shipment_id UUID NOT NULL REFERENCES shipments(id) ON DELETE RESTRICT, status TEXT NOT NULL CHECK(status IN ('planned','in_transit','on_hold','arrived','delivered','cancelled')), note TEXT NOT NULL DEFAULT '', occurred_at TIMESTAMPTZ NOT NULL, customer_visible BOOLEAN NOT NULL DEFAULT false$columns$),
(40,'files',$columns$storage_key TEXT NOT NULL UNIQUE CHECK(storage_key ~ '^[a-f0-9-]{36}$'), original_name TEXT NOT NULL, sha256 CHAR(64) NOT NULL CHECK(sha256 ~ '^[a-f0-9]{64}$'), byte_size BIGINT NOT NULL CHECK(byte_size>=0), media_type TEXT NOT NULL, owner_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, status TEXT NOT NULL DEFAULT 'quarantined' CHECK(status IN ('quarantined','available','deleted')), storage_backend TEXT NOT NULL DEFAULT 'disk' CHECK(storage_backend IN ('disk','object'))$columns$),
(41,'goods_in_receipts',$columns$booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, pieces INTEGER NOT NULL CHECK(pieces>=0), gross_kg NUMERIC(18,4) CHECK(gross_kg>=0), collected_at TIMESTAMPTZ, collection_amount NUMERIC(18,4), currency CHAR(3) REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), status TEXT NOT NULL DEFAULT 'received' CHECK(status IN ('received','checked','returned')), version INTEGER NOT NULL DEFAULT 1, CHECK((collection_amount IS NULL)=(currency IS NULL))$columns$),
(42,'goods_in_photos',$columns$receipt_id UUID NOT NULL REFERENCES goods_in_receipts(id) ON DELETE RESTRICT, file_id UUID NOT NULL REFERENCES files(id) ON DELETE RESTRICT, UNIQUE(receipt_id,file_id)$columns$),
(43,'documents',$columns$file_id UUID NOT NULL REFERENCES files(id) ON DELETE RESTRICT, booking_id UUID REFERENCES bookings(id) ON DELETE RESTRICT, customer_company_id UUID REFERENCES customer_companies(id) ON DELETE RESTRICT, kind TEXT NOT NULL, visibility TEXT NOT NULL DEFAULT 'internal' CHECK(visibility IN ('internal','customer')), expires_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1$columns$),
(44,'task_rules',$columns$code TEXT NOT NULL UNIQUE, trigger_event TEXT NOT NULL, conditions JSONB NOT NULL DEFAULT '[]', title_template TEXT NOT NULL, owner_source TEXT NOT NULL DEFAULT 'rule' CHECK(owner_source IN ('rule','event_user','event_role')), owner_role_id UUID REFERENCES roles(id) ON DELETE RESTRICT, owner_user_id UUID REFERENCES users(id) ON DELETE RESTRICT, due_minutes INTEGER NOT NULL DEFAULT 1440 CHECK(due_minutes BETWEEN 0 AND 525600), repeat_minutes INTEGER CHECK(repeat_minutes>=60), suggested BOOLEAN NOT NULL DEFAULT false, auto_close_event TEXT, template_code TEXT, active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1, CHECK(owner_role_id IS NOT NULL OR owner_user_id IS NOT NULL)$columns$),
(45,'workflow_events',$columns$event_key TEXT NOT NULL UNIQUE, event_type TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id UUID, warehouse_id UUID REFERENCES warehouses(id) ON DELETE RESTRICT, payload JSONB NOT NULL DEFAULT '{}', occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()$columns$),
(46,'approvals',$columns$reference TEXT NOT NULL UNIQUE, kind TEXT NOT NULL CHECK(kind IN ('general','exchange_rate','customer_company','customer_membership','credit_line','step_skip')), entity_type TEXT NOT NULL, entity_id UUID, payload JSONB NOT NULL DEFAULT '{}', reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','returned','approved','cancelled')), approver_role_id UUID NOT NULL REFERENCES roles(id) ON DELETE RESTRICT, approver_user_id UUID REFERENCES users(id) ON DELETE RESTRICT, warehouse_id UUID REFERENCES warehouses(id) ON DELETE RESTRICT, version INTEGER NOT NULL DEFAULT 1, submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(), decided_at TIMESTAMPTZ$columns$),
(47,'approval_steps',$columns$approval_id UUID NOT NULL REFERENCES approvals(id) ON DELETE RESTRICT, action TEXT NOT NULL CHECK(action IN ('submitted','returned','resubmitted','approved','cancelled')), note TEXT NOT NULL DEFAULT '', revision INTEGER NOT NULL CHECK(revision>0)$columns$),
(48,'booking_status_events',$columns$booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT, approval_id UUID REFERENCES approvals(id) ON DELETE RESTRICT, from_status TEXT, to_status TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', customer_visible BOOLEAN NOT NULL DEFAULT false, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()$columns$),
(49,'tasks',$columns$rule_id UUID REFERENCES task_rules(id) ON DELETE RESTRICT, event_id UUID REFERENCES workflow_events(id) ON DELETE RESTRICT, booking_id UUID REFERENCES bookings(id) ON DELETE RESTRICT, approval_id UUID REFERENCES approvals(id) ON DELETE RESTRICT, warehouse_id UUID REFERENCES warehouses(id) ON DELETE RESTRICT, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('suggested','open','in_progress','submitted','completed','dismissed','cancelled')), assignee_id UUID REFERENCES users(id) ON DELETE RESTRICT, owner_role_id UUID REFERENCES roles(id) ON DELETE RESTRICT, entity_type TEXT, entity_id UUID, due_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ, dedupe_key TEXT UNIQUE, version INTEGER NOT NULL DEFAULT 1, CHECK(assignee_id IS NOT NULL OR owner_role_id IS NOT NULL)$columns$),
(50,'task_comments',$columns$task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE RESTRICT, body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 4000)$columns$),
(51,'task_events',$columns$task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE RESTRICT, action TEXT NOT NULL, before_data JSONB, after_data JSONB, reason TEXT NOT NULL DEFAULT ''$columns$),
(52,'invoices',$columns$code TEXT NOT NULL UNIQUE, company_id UUID NOT NULL REFERENCES companies(id) ON DELETE RESTRICT, customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, booking_id UUID REFERENCES bookings(id) ON DELETE RESTRICT, currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), total NUMERIC(18,4) NOT NULL CHECK(total>=0), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','approved','issued','paid','cancelled')), due_date DATE, issued_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1$columns$),
(53,'invoice_lines',$columns$invoice_id UUID NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT, product_service_id UUID REFERENCES products_services(id) ON DELETE RESTRICT, tax_rate_id UUID REFERENCES tax_rates(id) ON DELETE RESTRICT, description TEXT NOT NULL, quantity NUMERIC(18,4) NOT NULL CHECK(quantity>0), unit_price NUMERIC(18,4) NOT NULL CHECK(unit_price>=0), tax_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK(tax_amount>=0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$')$columns$),
(54,'payments',$columns$code TEXT NOT NULL UNIQUE, invoice_id UUID REFERENCES invoices(id) ON DELETE RESTRICT, customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT, amount NUMERIC(18,4) NOT NULL CHECK(amount>0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','confirmed','rejected','cancelled')), paid_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1$columns$),
(55,'payment_proofs',$columns$payment_id UUID NOT NULL REFERENCES payments(id) ON DELETE RESTRICT, file_id UUID NOT NULL REFERENCES files(id) ON DELETE RESTRICT, UNIQUE(payment_id,file_id)$columns$),
(56,'payment_orders',$columns$code TEXT NOT NULL UNIQUE, booking_id UUID REFERENCES bookings(id) ON DELETE RESTRICT, customer_company_id UUID REFERENCES customer_companies(id) ON DELETE RESTRICT, account_id UUID REFERENCES accounts(id) ON DELETE RESTRICT, approval_id UUID REFERENCES approvals(id) ON DELETE RESTRICT, amount NUMERIC(18,4) NOT NULL CHECK(amount>0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','approved','paid','cancelled')), beneficiary_ciphertext TEXT, version INTEGER NOT NULL DEFAULT 1$columns$),
(57,'receipts',$columns$code TEXT NOT NULL UNIQUE, payment_id UUID NOT NULL REFERENCES payments(id) ON DELETE RESTRICT, amount NUMERIC(18,4) NOT NULL CHECK(amount>0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), issued_at TIMESTAMPTZ NOT NULL, version INTEGER NOT NULL DEFAULT 1$columns$),
(58,'journal_entries',$columns$code TEXT NOT NULL UNIQUE, company_id UUID NOT NULL REFERENCES companies(id) ON DELETE RESTRICT, booking_id UUID REFERENCES bookings(id) ON DELETE RESTRICT, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','posted','reversed')), posting_date DATE NOT NULL, posted_at TIMESTAMPTZ, reason TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1$columns$),
(59,'journal_lines',$columns$journal_entry_id UUID NOT NULL REFERENCES journal_entries(id) ON DELETE RESTRICT, account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT, currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), debit NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK(debit>=0), credit NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK(credit>=0), CHECK((debit>0 AND credit=0) OR (credit>0 AND debit=0))$columns$),
(60,'purchase_rates',$columns$service_id UUID NOT NULL REFERENCES services(id) ON DELETE RESTRICT, route_id UUID REFERENCES routes(id) ON DELETE RESTRICT, product_service_id UUID REFERENCES products_services(id) ON DELETE RESTRICT, amount NUMERIC(18,4) NOT NULL CHECK(amount>=0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), unit TEXT NOT NULL, valid_from TIMESTAMPTZ NOT NULL, valid_to TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','withdrawn')), rules JSONB NOT NULL DEFAULT '{}', version INTEGER NOT NULL DEFAULT 1, CHECK(valid_to>valid_from)$columns$),
(61,'selling_rates',$columns$service_id UUID NOT NULL REFERENCES services(id) ON DELETE RESTRICT, route_id UUID REFERENCES routes(id) ON DELETE RESTRICT, product_service_id UUID REFERENCES products_services(id) ON DELETE RESTRICT, customer_company_id UUID REFERENCES customer_companies(id) ON DELETE RESTRICT, amount NUMERIC(18,4) NOT NULL CHECK(amount>=0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), unit TEXT NOT NULL, valid_from TIMESTAMPTZ NOT NULL, valid_to TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','withdrawn')), rules JSONB NOT NULL DEFAULT '{}', version INTEGER NOT NULL DEFAULT 1, CHECK(valid_to>valid_from)$columns$),
(62,'delivery_rates',$columns$service_id UUID NOT NULL REFERENCES services(id) ON DELETE RESTRICT, route_id UUID REFERENCES routes(id) ON DELETE RESTRICT, product_service_id UUID REFERENCES products_services(id) ON DELETE RESTRICT, amount NUMERIC(18,4) NOT NULL CHECK(amount>=0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), unit TEXT NOT NULL, valid_from TIMESTAMPTZ NOT NULL, valid_to TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','withdrawn')), rules JSONB NOT NULL DEFAULT '{}', version INTEGER NOT NULL DEFAULT 1, CHECK(valid_to>valid_from)$columns$),
(63,'purchase_rate_rules',$columns$purchase_rate_id UUID NOT NULL REFERENCES purchase_rates(id) ON DELETE RESTRICT, rule_type TEXT NOT NULL, configuration JSONB NOT NULL, version INTEGER NOT NULL DEFAULT 1$columns$),
(64,'purchase_invoices',$columns$code TEXT NOT NULL UNIQUE, supplier_name TEXT NOT NULL, currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), amount NUMERIC(18,4) NOT NULL CHECK(amount>=0), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','approved','paid','cancelled')), invoice_date DATE NOT NULL, version INTEGER NOT NULL DEFAULT 1$columns$),
(65,'purchase_invoice_bookings',$columns$purchase_invoice_id UUID NOT NULL REFERENCES purchase_invoices(id) ON DELETE RESTRICT, booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT, amount NUMERIC(18,4) NOT NULL CHECK(amount>=0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), UNIQUE(purchase_invoice_id,booking_id)$columns$),
(66,'storage_contracts',$columns$code TEXT NOT NULL UNIQUE, customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','active','ended','cancelled')), pricing_basis TEXT NOT NULL CHECK(pricing_basis IN ('fixed','cbm_day','cbm_month')), amount NUMERIC(18,4) NOT NULL CHECK(amount>=0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), start_date DATE NOT NULL, end_date DATE, version INTEGER NOT NULL DEFAULT 1$columns$),
(67,'inventory_items',$columns$box_code TEXT NOT NULL UNIQUE, customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, storage_contract_id UUID REFERENCES storage_contracts(id) ON DELETE RESTRICT, contents TEXT NOT NULL DEFAULT '', quantity NUMERIC(18,4) NOT NULL CHECK(quantity>=0), status TEXT NOT NULL DEFAULT 'expected' CHECK(status IN ('expected','received','reserved','dispatched')), version INTEGER NOT NULL DEFAULT 1$columns$),
(68,'fulfilment_orders',$columns$code TEXT NOT NULL UNIQUE, customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, status TEXT NOT NULL DEFAULT 'requested' CHECK(status IN ('requested','approved','picking','dispatched','cancelled')), destination TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1$columns$),
(69,'fulfilment_order_items',$columns$order_id UUID NOT NULL REFERENCES fulfilment_orders(id) ON DELETE RESTRICT, inventory_item_id UUID NOT NULL REFERENCES inventory_items(id) ON DELETE RESTRICT, quantity NUMERIC(18,4) NOT NULL CHECK(quantity>0), UNIQUE(order_id,inventory_item_id)$columns$),
(70,'credit_lines',$columns$customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), limit_amount NUMERIC(18,4) NOT NULL CHECK(limit_amount>=0), used_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK(used_amount>=0), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','suspended','closed')), approval_id UUID REFERENCES approvals(id) ON DELETE RESTRICT, expires_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1, CHECK(used_amount<=limit_amount), UNIQUE(customer_company_id,currency)$columns$),
(71,'trucks',$columns$code TEXT NOT NULL UNIQUE, plate TEXT NOT NULL, country_code CHAR(2) NOT NULL CHECK(country_code ~ '^[A-Z]{2}$'), truck_type TEXT NOT NULL, max_kg NUMERIC(18,4) CHECK(max_kg>0), length_cm NUMERIC(18,4), width_cm NUMERIC(18,4), height_cm NUMERIC(18,4), active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1$columns$),
(72,'truck_documents',$columns$truck_id UUID NOT NULL REFERENCES trucks(id) ON DELETE RESTRICT, file_id UUID NOT NULL REFERENCES files(id) ON DELETE RESTRICT, kind TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL$columns$),
(73,'drivers',$columns$user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT, phone TEXT NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT true, version INTEGER NOT NULL DEFAULT 1$columns$),
(74,'delivery_orders',$columns$code TEXT NOT NULL UNIQUE, booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, driver_id UUID REFERENCES drivers(id) ON DELETE RESTRICT, truck_id UUID REFERENCES trucks(id) ON DELETE RESTRICT, destination TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','assigned','out_for_delivery','delivered','cancelled')), due_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1$columns$),
(75,'delivery_proofs',$columns$delivery_order_id UUID NOT NULL REFERENCES delivery_orders(id) ON DELETE RESTRICT, file_id UUID NOT NULL REFERENCES files(id) ON DELETE RESTRICT, recipient_name TEXT NOT NULL, delivered_at TIMESTAMPTZ NOT NULL$columns$),
(76,'feedback',$columns$booking_id UUID NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE RESTRICT, customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT, rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5), ratings JSONB NOT NULL DEFAULT '{}', comment TEXT NOT NULL DEFAULT ''$columns$),
(77,'inquiries',$columns$code TEXT NOT NULL UNIQUE, customer_id UUID REFERENCES customers(id) ON DELETE RESTRICT, assignee_id UUID REFERENCES users(id) ON DELETE RESTRICT, email TEXT NOT NULL, source TEXT NOT NULL CHECK(source IN ('website','email','phone','staff','whatsapp')), status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','assigned','quoted','closed')), summary TEXT NOT NULL, due_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1$columns$),
(78,'quotations',$columns$code TEXT NOT NULL UNIQUE, customer_company_id UUID NOT NULL REFERENCES customer_companies(id) ON DELETE RESTRICT, inquiry_id UUID REFERENCES inquiries(id) ON DELETE RESTRICT, booking_id UUID REFERENCES bookings(id) ON DELETE RESTRICT, currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$'), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','approved','sent','accepted','declined','expired')), valid_until TIMESTAMPTZ NOT NULL, amount NUMERIC(18,4) NOT NULL CHECK(amount>=0), version INTEGER NOT NULL DEFAULT 1$columns$),
(79,'quotation_lines',$columns$quotation_id UUID NOT NULL REFERENCES quotations(id) ON DELETE RESTRICT, product_service_id UUID REFERENCES products_services(id) ON DELETE RESTRICT, selling_rate_id UUID REFERENCES selling_rates(id) ON DELETE RESTRICT, description TEXT NOT NULL, amount NUMERIC(18,4) NOT NULL CHECK(amount>=0), currency CHAR(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT CHECK(currency ~ '^[A-Z]{3}$')$columns$),
(80,'employees',$columns$user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT, employee_code TEXT NOT NULL UNIQUE, department TEXT NOT NULL DEFAULT '', job_title TEXT NOT NULL DEFAULT '', start_date DATE, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','leave','ended')), version INTEGER NOT NULL DEFAULT 1$columns$),
(81,'employee_documents',$columns$employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE RESTRICT, file_id UUID NOT NULL REFERENCES files(id) ON DELETE RESTRICT, kind TEXT NOT NULL, expires_at TIMESTAMPTZ$columns$),
(82,'scheduler_runs',$columns$job_key TEXT NOT NULL, bucket TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('running','completed','failed')), error_code TEXT, completed_at TIMESTAMPTZ, UNIQUE(job_key,bucket)$columns$),
(83,'backup_runs',$columns$backup_date DATE NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('running','completed','failed')), manifest_path TEXT, manifest_sha256 CHAR(64), error_code TEXT, completed_at TIMESTAMPTZ$columns$)
 ) AS definitions(ordinal,name,columns) ORDER BY ordinal LOOP
  EXECUTE format('CREATE TABLE %I (%s, %s)',definition.name,common,definition.columns);
 END LOOP;
END $migration$;
CREATE UNIQUE INDEX exchange_rates_one_active_day ON exchange_rates(rule_id,rate_date) WHERE status='active' AND deleted_at IS NULL;
ALTER TABLE rate_confirmations ADD CONSTRAINT rate_confirmation_previous_fk FOREIGN KEY(previous_id) REFERENCES exchange_rates(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX customer_company_single_owner ON customer_memberships(customer_company_id) WHERE role='owner' AND status='active' AND deleted_at IS NULL;
CREATE UNIQUE INDEX users_legacy_customer_unique ON customers(user_id) WHERE deleted_at IS NULL;
CREATE FUNCTION ukr_touch_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at=clock_timestamp(); RETURN NEW; END $$;
CREATE FUNCTION ukr_append_only() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Append-only history cannot be changed' USING ERRCODE='23514'; END $$;
DO $$
DECLARE tbl TEXT; col RECORD;
BEGIN
 FOREACH tbl IN ARRAY ARRAY['users','roles','permissions','role_permissions','user_roles','currencies','companies','customers','customer_companies','customer_memberships','customer_invitations','warehouses','user_warehouses','user_currencies','accounts','products_services','services','routes','themes','user_preferences','settings','sessions','otp_codes','auth_limits','audit_log','email_templates','email_outbox','mail_accounts','mail_account_users','mail_messages','exchange_rate_rules','rate_confirmations','exchange_rates','tax_rates','bookings','booking_items','consolidations','consolidation_bookings','shipments','shipment_events','files','goods_in_receipts','goods_in_photos','documents','task_rules','workflow_events','approvals','approval_steps','booking_status_events','tasks','task_comments','task_events','invoices','invoice_lines','payments','payment_proofs','payment_orders','receipts','journal_entries','journal_lines','purchase_rates','selling_rates','delivery_rates','purchase_rate_rules','purchase_invoices','purchase_invoice_bookings','storage_contracts','inventory_items','fulfilment_orders','fulfilment_order_items','credit_lines','trucks','truck_documents','drivers','delivery_orders','delivery_proofs','feedback','inquiries','quotations','quotation_lines','employees','employee_documents','scheduler_runs','backup_runs'] LOOP
   EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION ukr_touch_updated_at()',tbl||'_touch',tbl);
   FOR col IN SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=tbl AND (column_name='created_by' OR column_name LIKE '%\_id' ESCAPE '\' OR column_name IN ('status','state','code','email','currency','base_currency','quote_currency','legacy_token_hash') OR data_type IN ('date','timestamp with time zone','timestamp without time zone')) LOOP
     EXECUTE format('CREATE INDEX %I ON %I (%I)',left(tbl||'_'||col.column_name||'_idx',63),tbl,col.column_name);
   END LOOP;
 END LOOP;
 FOREACH tbl IN ARRAY ARRAY['audit_log','approval_steps','task_events','booking_status_events','shipment_events'] LOOP
   EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION ukr_append_only()',tbl||'_immutable',tbl);
 END LOOP;
END $$;
