-- Only approved master definitions. No commercial rates, demo customers or passwords.
INSERT INTO roles(code,name,system_role) VALUES
('super_admin','Super Admin',true),('management','Management',true),('sales_manager','Sales Manager',true),('sales','Sales',true),('operations_manager','Operations Manager',true),('operations','Operations',true),('china_manager','China Manager',true),('china_warehouse','China Warehouse',true),('customs','Customs',true),('transport_manager','Transport Manager',true),('dispatcher','Dispatcher',true),('finance_manager','Finance Manager',true),('accounts','Accounts',true),('warehouse','Warehouse',true),('driver','Driver',true),('purchase_team','Purchase Team',true),('currency_rate_user','Currency Rate User',true),('hr','HR',true);
INSERT INTO permissions(code,module,action) SELECT m||'.'||a,m,a FROM unnest(ARRAY['overview','sales','air_ddp','sea_ddp','air_express','sea_lcl','sea_fcl','land','storage','customs','china_payment','purchase_rates','delivery_rates','finance','purchase_invoices','tasks','delivery','hr','masters','settings','users','roles','templates','outbox','logs','preferences','themes','task_rules','approvals','exchange_rates','customers','mail_accounts']) m CROSS JOIN unnest(ARRAY['view','create','edit','approve','delete','export']) a;
INSERT INTO role_permissions(role_id,permission_id,scope) SELECT r.id,p.id,'all' FROM roles r CROSS JOIN permissions p WHERE r.code='super_admin';
INSERT INTO role_permissions(role_id,permission_id,scope) SELECT r.id,p.id,CASE WHEN p.action='edit' THEN 'self' ELSE 'assigned' END FROM roles r CROSS JOIN permissions p WHERE r.code<>'super_admin' AND (p.code IN ('preferences.view','preferences.edit','overview.view'));
WITH grants(role_code,codes,scope) AS (VALUES
('management',ARRAY['air_ddp.view','air_express.view','approvals.approve','approvals.view','china_payment.view','customers.view','customs.view','delivery.view','delivery_rates.view','exchange_rates.approve','exchange_rates.view','finance.view','hr.view','land.view','logs.view','outbox.view','purchase_invoices.view','purchase_rates.view','sales.view','sea_ddp.view','sea_fcl.view','sea_lcl.view','settings.view','storage.view','tasks.view','templates.view']::TEXT[],'all'),
('sales_manager',ARRAY['air_ddp.view','air_express.view','approvals.approve','approvals.create','approvals.edit','approvals.view','customers.create','customers.edit','customers.export','customers.view','customs.view','land.view','sales.approve','sales.create','sales.edit','sales.export','sales.view','sea_ddp.view','sea_fcl.view','sea_lcl.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'all'),
('sales',ARRAY['air_ddp.view','air_express.view','approvals.create','approvals.edit','approvals.view','customers.create','customers.edit','customers.view','customs.view','land.view','sales.create','sales.edit','sales.view','sea_ddp.view','sea_fcl.view','sea_lcl.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'assigned'),
('operations_manager',ARRAY['air_ddp.approve','air_ddp.create','air_ddp.edit','air_ddp.export','air_ddp.view','air_express.approve','air_express.create','air_express.edit','air_express.export','air_express.view','approvals.approve','approvals.create','approvals.edit','approvals.view','customs.approve','customs.create','customs.edit','customs.export','customs.view','delivery.approve','delivery.create','delivery.edit','delivery.export','delivery.view','land.approve','land.create','land.edit','land.export','land.view','sea_ddp.approve','sea_ddp.create','sea_ddp.edit','sea_ddp.export','sea_ddp.view','sea_fcl.approve','sea_fcl.create','sea_fcl.edit','sea_fcl.export','sea_fcl.view','sea_lcl.approve','sea_lcl.create','sea_lcl.edit','sea_lcl.export','sea_lcl.view','storage.approve','storage.create','storage.edit','storage.export','storage.view','tasks.approve','tasks.create','tasks.edit','tasks.view']::TEXT[],'all'),
('operations',ARRAY['air_ddp.create','air_ddp.edit','air_ddp.view','air_express.create','air_express.edit','air_express.view','approvals.create','approvals.edit','approvals.view','customs.create','customs.edit','customs.view','land.create','land.edit','land.view','sea_ddp.create','sea_ddp.edit','sea_ddp.view','sea_fcl.create','sea_fcl.edit','sea_fcl.view','sea_lcl.create','sea_lcl.edit','sea_lcl.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'assigned'),
('china_manager',ARRAY['air_ddp.approve','air_ddp.create','air_ddp.edit','air_ddp.view','approvals.approve','approvals.create','approvals.edit','approvals.view','sea_ddp.approve','sea_ddp.create','sea_ddp.edit','sea_ddp.view','storage.approve','storage.create','storage.edit','storage.view','tasks.approve','tasks.create','tasks.edit','tasks.view']::TEXT[],'warehouse'),
('china_warehouse',ARRAY['approvals.view']::TEXT[],'assigned'),
('china_warehouse',ARRAY['air_ddp.create','air_ddp.edit','air_ddp.view','sea_ddp.create','sea_ddp.edit','sea_ddp.view','storage.create','storage.edit','storage.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'warehouse'),
('customs',ARRAY['air_ddp.view','approvals.view','customs.create','customs.edit','customs.view','sea_ddp.view','sea_fcl.view','sea_lcl.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'assigned'),
('transport_manager',ARRAY['approvals.approve','approvals.create','approvals.edit','approvals.view','delivery.approve','delivery.create','delivery.edit','delivery.view','land.approve','land.create','land.edit','land.view','tasks.approve','tasks.create','tasks.edit','tasks.view']::TEXT[],'all'),
('dispatcher',ARRAY['approvals.view','delivery.create','delivery.edit','delivery.view','land.create','land.edit','land.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'assigned'),
('finance_manager',ARRAY['approvals.approve','approvals.create','approvals.edit','approvals.export','approvals.view','delivery_rates.view','exchange_rates.approve','exchange_rates.create','exchange_rates.edit','exchange_rates.export','exchange_rates.view','finance.approve','finance.create','finance.edit','finance.export','finance.view','purchase_invoices.approve','purchase_invoices.create','purchase_invoices.edit','purchase_invoices.export','purchase_invoices.view','purchase_rates.view','tasks.approve','tasks.create','tasks.edit','tasks.export','tasks.view']::TEXT[],'all'),
('accounts',ARRAY['approvals.view','finance.create','finance.edit','finance.view','purchase_invoices.create','purchase_invoices.edit','purchase_invoices.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'assigned'),
('warehouse',ARRAY['approvals.view']::TEXT[],'assigned'),
('warehouse',ARRAY['air_ddp.create','air_ddp.edit','air_ddp.view','air_express.create','air_express.edit','air_express.view','sea_ddp.create','sea_ddp.edit','sea_ddp.view','sea_lcl.create','sea_lcl.edit','sea_lcl.view','storage.create','storage.edit','storage.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'warehouse'),
('driver',ARRAY['approvals.view','delivery.edit','delivery.view','tasks.edit','tasks.view']::TEXT[],'assigned'),
('purchase_team',ARRAY['approvals.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'assigned'),
('purchase_team',ARRAY['purchase_invoices.create','purchase_invoices.edit','purchase_invoices.export','purchase_invoices.view','purchase_rates.create','purchase_rates.edit','purchase_rates.export','purchase_rates.view']::TEXT[],'all'),
('currency_rate_user',ARRAY['approvals.view','exchange_rates.create','exchange_rates.edit','exchange_rates.view','tasks.edit','tasks.view']::TEXT[],'assigned'),
('hr',ARRAY['approvals.view','tasks.create','tasks.edit','tasks.view']::TEXT[],'assigned'),
('hr',ARRAY['hr.create','hr.edit','hr.export','hr.view']::TEXT[],'all'))
INSERT INTO role_permissions(role_id,permission_id,scope) SELECT r.id,p.id,g.scope FROM grants g JOIN roles r ON r.code=g.role_code CROSS JOIN LATERAL unnest(g.codes) c JOIN permissions p ON p.code=c ON CONFLICT(role_id,permission_id) DO NOTHING;
INSERT INTO currencies(code,name,symbol,minor_units) VALUES ('AED','UAE dirham','AED',2),('USD','US dollar','$',2),('EUR','Euro','€',2),('GBP','Pound sterling','£',2),('CNY','Chinese yuan','¥',2),('SAR','Saudi riyal','SAR',2),('CAD','Canadian dollar','C$',2),('OMR','Omani rial','OMR',3),('QAR','Qatari riyal','QAR',2),('KWD','Kuwaiti dinar','KWD',3),('BHD','Bahraini dinar','BHD',3);
INSERT INTO themes(code,name,tokens) VALUES
('ukr-blue','UKR Blue','{"background":"#f3f7fb","surface":"#ffffff","text":"#123755","muted":"#526c81","accent":"#0765af","border":"#d6e3ed"}'),
('dark','Dark','{"background":"#111b28","surface":"#1a293b","text":"#f3f6fb","muted":"#bed0e0","accent":"#68b9ff","border":"#435e7b"}'),
('high-contrast','High Contrast','{"background":"#000000","surface":"#000000","text":"#ffffff","muted":"#ffffff","accent":"#ffff00","border":"#ffffff"}'),
('ocean','Ocean','{"background":"#edf8f8","surface":"#ffffff","text":"#103c42","muted":"#42666b","accent":"#006a77","border":"#c5dfe1"}'),
('sand','Sand','{"background":"#faf6ee","surface":"#fffdfa","text":"#423729","muted":"#72634e","accent":"#83561b","border":"#dfd2bd"}'),
('forest','Forest','{"background":"#f1f7f1","surface":"#ffffff","text":"#183e27","muted":"#4d6956","accent":"#246b3c","border":"#caddce"}');
INSERT INTO companies(code,legal_name,address,country_code,phone,email,sales_email,website,base_currency,financial_year_start_month,invoice_prefix) VALUES('UKR-UAE','UKR SEA SHIPPING CO LLC','809 Al Mossa Tower 1, Sheikh Zayed Road, Trade Centre 1, Dubai, UAE','AE','+971 4 3888014','info@ukrshipping.com','sales@ukrshipping.com','https://www.ukrshipping.com','AED',1,'UKR');
INSERT INTO warehouses(code,name,country_code,city,services,tabs) VALUES
('CN-GUANGZHOU','Guangzhou warehouse','CN','Guangzhou','["air_ddp","sea_ddp"]','["goods_in","consolidation","final_check","ready_to_deliver"]'),
('AE-RASALKHOR','Ras Al Khor warehouse','AE','Dubai','["air_ddp","sea_ddp"]','["goods_in","consolidation","final_check","ready_to_deliver"]');
INSERT INTO services(code,name,configuration) VALUES ('air_ddp','Air DDP','{"air_volume_divisor":5000}'),('sea_ddp','Sea DDP','{}'),('air_express','Air Express','{"air_volume_divisor":5000}'),('sea_lcl','LCL','{}'),('sea_fcl','FCL','{}'),('land','Truck','{}'),('storage','Storage & Fulfilment','{}'),('customs','Customs Clearance','{}');
INSERT INTO accounts(code,name,account_type) VALUES ('1000','Assets','asset'),('2000','Liabilities','liability'),('3000','Equity','equity'),('4000','Income','income'),('5000','Expenses','expense');
INSERT INTO products_services(code,name,kind) VALUES ('FREIGHT','Freight services','group'),('HANDLING','Handling charges','group'),('DELIVERY','Delivery charges','group');
INSERT INTO settings(key,value) VALUES
('base_currency','"AED"'),('financial_year_start_month','1'),('quotation_default_days','7'),('air_volume_divisor','5000'),('new_customer_assignment_minutes','30'),('currency_due_time','"09:00"'),('currency_cutoff_time','"12:00"'),('currency_threshold_percent','"5.0000"'),('currency_timezone','"Asia/Dubai"'),('smtp_from','"no-reply@ukrshipping.com"'),('smtp_reply_to','"sales@ukrshipping.com"'),('email_delivery_enabled','false'),('public_email_domains','["gmail.com","googlemail.com","hotmail.com","outlook.com","live.com","yahoo.com","yahoo.co.uk","icloud.com","me.com","aol.com","proton.me","protonmail.com","mail.com","yandex.com","qq.com","163.com"]'),('backup_policy','{"enabled":false,"frequency":"daily","timezone":"Asia/Dubai","at":"02:00","retention_days":14}');
-- Owner-provided tax options; selection is per line, not an automatic place-of-supply determination.
INSERT INTO tax_rates(code,country_code,region,label,rate,treatment,valid_from) VALUES
('AE-VAT-5','AE','','UAE VAT 5%',5,'standard','2026-10-04'),('AE-ZERO','AE','','UAE VAT 0%',0,'zero','2026-10-04'),('AE-EXEMPT','AE','','UAE VAT exempt',0,'exempt','2026-10-04'),('SA-VAT-15','SA','','KSA VAT 15%',15,'standard','2026-10-04'),('SA-EXEMPT','SA','','KSA VAT exempt',0,'exempt','2026-10-04'),('GB-VAT-20','GB','','UK VAT 20%',20,'standard','2026-10-04'),('GB-ZERO','GB','','UK VAT 0%',0,'zero','2026-10-04');
WITH defaults(code,event,title,role_code,due,close_event,suggested) AS (VALUES
('booking-review','booking.submitted','Review booking {code}','sales_manager',30,'booking.accepted',false),
('goods-details','goods.received','Complete cargo details for {code}','sales',1440,'cargo.ready',false),
('status-stale','shipment.status_stale','Update shipment status: {code}','operations_manager',0,'shipment.status_updated',false),
('quote-followup','quotation.followup_due','Follow up quotation {code}','sales',0,'quotation.responded',false),
('document-expiry','document.expiring','Review expiring document {code}','operations_manager',0,NULL,false),
('eta-soon','shipment.eta_soon','Prepare arrival documents: {code}','operations_manager',0,NULL,false),
('invoice-overdue','invoice.overdue','Follow up overdue invoice {code}','accounts',0,NULL,false),
('approval-waiting','approval.waiting','Review waiting approval {code}','management',0,'approval.decided',false),
('consolidate-suggestion','consolidation.suggested','Consider consolidation for {code}','operations_manager',1440,NULL,true))
INSERT INTO task_rules(code,trigger_event,title_template,owner_role_id,due_minutes,auto_close_event,suggested) SELECT d.code,d.event,d.title,r.id,d.due,d.close_event,d.suggested FROM defaults d JOIN roles r ON r.code=d.role_code;
-- Refuse ambiguous legacy mappings instead of discarding any membership.
DO $$ BEGIN
 IF EXISTS(SELECT customer_id FROM booking_lab_memberships WHERE active=1 GROUP BY customer_id HAVING count(*)>1) THEN RAISE EXCEPTION 'Legacy customers have multiple companies; explicit mapping required'; END IF;
 IF EXISTS(SELECT 1 FROM staff_users s JOIN booking_lab_customers c ON lower(c.email)=lower(s.email)) THEN RAISE EXCEPTION 'A legacy email is both staff and customer; resolve mapping first'; END IF;
END $$;
INSERT INTO users(email,display_name,kind,state,staff_user_id,created_at,updated_at) SELECT lower(email),name,'staff',CASE WHEN active=1 THEN 'active' ELSE 'disabled' END,id,to_timestamp(created_at/1000.0),to_timestamp(created_at/1000.0) FROM staff_users;
INSERT INTO users(email,display_name,kind,state,legacy_customer_id,preferred_language,created_at,updated_at) SELECT lower(email),name,'customer',CASE WHEN active=0 THEN 'disabled' WHEN email_verified=1 THEN 'active' ELSE 'pending' END,id,language,to_timestamp(created_at/1000.0),to_timestamp(created_at/1000.0) FROM booking_lab_customers;
INSERT INTO users(email,display_name,kind,state) VALUES('bayan@ukrshipping.com','Bayan Biri','staff','invited') ON CONFLICT(email) DO NOTHING;
INSERT INTO user_roles(user_id,role_id) SELECT u.id,r.id FROM users u JOIN staff_users s ON s.id=u.staff_user_id JOIN roles r ON r.code=s.role ON CONFLICT(user_id,role_id) DO NOTHING;
INSERT INTO user_roles(user_id,role_id) SELECT u.id,r.id FROM users u CROSS JOIN roles r WHERE u.email='bayan@ukrshipping.com' AND u.kind='staff' AND r.code='super_admin' ON CONFLICT(user_id,role_id) DO NOTHING;
INSERT INTO customers(user_id,status) SELECT id,CASE WHEN state='disabled' THEN 'disabled' ELSE 'pending' END FROM users WHERE kind='customer';
INSERT INTO customer_companies(legal_name,status,legacy_company_id) SELECT name,CASE WHEN active=1 THEN 'pending' ELSE 'disabled' END,id FROM booking_lab_companies;
INSERT INTO customer_memberships(customer_id,customer_company_id,role,status,approved_at)
 SELECT c.id,co.id,'staff',CASE WHEN m.active=1 AND m.approved=1 THEN 'active' WHEN m.active=0 THEN 'disabled' ELSE 'pending' END,CASE WHEN m.approved=1 THEN now() ELSE NULL END
 FROM booking_lab_memberships m JOIN users u ON u.legacy_customer_id=m.customer_id JOIN customers c ON c.user_id=u.id JOIN customer_companies co ON co.legacy_company_id=m.company_id;
UPDATE customer_companies co SET status='approved' WHERE EXISTS(SELECT 1 FROM customer_memberships m WHERE m.customer_company_id=co.id AND m.status='active');
INSERT INTO user_preferences(user_id,theme_id,language) SELECT u.id,t.id,u.preferred_language FROM users u CROSS JOIN themes t WHERE t.code='ukr-blue';
ALTER TABLE ukr_schema_migrations ADD CONSTRAINT migration_actor_fk FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT;
CREATE INDEX ukr_schema_migrations_actor_idx ON ukr_schema_migrations(created_by);
CREATE INDEX ukr_schema_migrations_created_idx ON ukr_schema_migrations(created_at);
CREATE INDEX ukr_schema_migrations_updated_idx ON ukr_schema_migrations(updated_at);
INSERT INTO task_rules(code,trigger_event,title_template,owner_source,owner_role_id,due_minutes,auto_close_event) SELECT 'approval-review','approval.requested','Review approval {code}','event_role',id,1440,'approval.decided' FROM roles WHERE code='management';
