import {id,email,text,uuid,one,all,must,audit,optimistic} from './core.mjs';
import {companyFor,requirePermission} from './rbac.mjs';
import {submitApproval} from './workflow.mjs';
import {publicDomains} from './catalog.mjs';
const cleanDomain=value=>{const d=text(value||'',253).toLowerCase();must(!d||/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,63}$/.test(d));return d;};
const publicDomain=d=>publicDomains.includes(d);
export async function customerProfile(db,actor){must(actor.kind==='customer',403,'access_denied');const company=await companyFor(db,actor);const record=await one(db,'SELECT phone,version FROM customers WHERE user_id=$1 AND deleted_at IS NULL',[actor.id]);const invites=await all(db,"SELECT i.id,i.member_role,c.legal_name FROM customer_invitations i JOIN customer_companies c ON c.id=i.customer_company_id WHERE i.email=$1 AND i.status='pending' AND i.expires_at>now() AND i.deleted_at IS NULL AND c.deleted_at IS NULL AND c.status<>'disabled'",[actor.email]);return {name:actor.display_name,email:actor.email,phone:record?.phone||'',version:record?.version||1,company,invites};}
export async function saveCustomerProfile(db,actor,data){must(actor.kind==='customer',403,'access_denied');const old=await one(db,'SELECT * FROM customers WHERE user_id=$1',[actor.id]);optimistic(old,data.version);const name=text(data.name,100,true),phone=text(data.phone,40,true);await db.query('UPDATE users SET display_name=$1,version=version+1 WHERE id=$2',[name,actor.id]);await db.query('UPDATE customers SET phone=$1,version=version+1 WHERE id=$2',[phone,old.id]);if(actor.legacy_customer_id)await db.query('UPDATE booking_lab_customers SET name=$1 WHERE id=$2',[name,actor.legacy_customer_id]);await audit(db,actor.id,'customer.profile_updated','customers',old.id,{phone:old.phone},{name,phone});return {ok:true};}
export async function requestCompany(db,actor,data,now=Date.now()){must(actor.kind==='customer',403,'access_denied');const current=await companyFor(db,actor);must(current?.customer_id&&!current.id,409,'company_already_linked');const name=text(data.legal_name,200,true),phone=text(data.phone,40,true),address=text(data.address||'',1000),country=text(data.country_code,2,true),tax=text(data.tax_number||'',80),domain=cleanDomain(data.domain);must(/^[A-Z]{2}$/.test(country));
 const legacyId=id();await db.query('INSERT INTO booking_lab_companies(id,name,active,created_at) VALUES($1,$2,1,$3)',[legacyId,name,now]);const company=await one(db,'INSERT INTO customer_companies(legal_name,owner_customer_id,domain,phone,address,country_code,tax_number,legacy_company_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[name,current.customer_id,domain,phone,address,country,tax,legacyId,actor.id]);
 await db.query("INSERT INTO customer_memberships(customer_id,customer_company_id,role,status,created_by) VALUES($1,$2,'owner','active',$3)",[current.customer_id,company.id,actor.id]);await db.query('INSERT INTO booking_lab_memberships(customer_id,company_id,approved,active) SELECT legacy_customer_id,$1,0,1 FROM users WHERE id=$2',[legacyId,actor.id]);
 const role=await one(db,"SELECT id FROM roles WHERE code='management'");await submitApproval(db,actor,{kind:'customer_company',entityType:'customer_company',entityId:company.id,reason:'Customer requests company account approval.',roleId:role.id,payload:{version:company.version}},now);await audit(db,actor.id,'customer.company_requested','customer_companies',company.id,null,{legal_name:name});return {id:company.id,status:'pending'};
}
export async function inviteCompanyMember(db,actor,data,now=Date.now()){const company=await companyFor(db,actor);must(company?.id&&company.role==='owner'&&company.membership_status==='active'&&company.status!=='disabled',403,'access_denied');const address=email(data.email);must(['staff','view_only'].includes(data.role));const existing=await one(db,'SELECT m.customer_company_id FROM users u JOIN customers c ON c.user_id=u.id JOIN customer_memberships m ON m.customer_id=c.id WHERE u.email=$1',[address]);must(!existing||existing.customer_company_id===company.id,409,'account_already_linked');const row=await one(db,"INSERT INTO customer_invitations(customer_company_id,email,member_role,expires_at,created_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(customer_company_id,email) DO UPDATE SET member_role=EXCLUDED.member_role,status='pending',expires_at=EXCLUDED.expires_at,deleted_at=NULL RETURNING id",[company.id,address,data.role,new Date(now+172800000),actor.id]);await audit(db,actor.id,'customer.member_invited','customer_invitations',row.id,null,{email:address,role:data.role});return {id:row.id,emailSent:false};}
export async function acceptCompanyInvite(db,actor,inviteId,now=Date.now()){must(actor.kind==='customer',403,'access_denied');const invite=await one(db,"SELECT * FROM customer_invitations WHERE id=$1 AND email=$2 AND status='pending' AND expires_at>$3 AND deleted_at IS NULL",[uuid(inviteId),actor.email,new Date(now)]);must(invite,404,'not_found');const own=await companyFor(db,actor);must(!own.id,409,'company_already_linked');const company=await one(db,"SELECT * FROM customer_companies WHERE id=$1 AND deleted_at IS NULL AND status<>'disabled'",[invite.customer_company_id]);must(company,404,'not_found');
 const inviter=await one(db,"SELECT m.id FROM users u JOIN customers c ON c.user_id=u.id JOIN customer_memberships m ON m.customer_id=c.id WHERE u.id=$1 AND u.state='active' AND m.customer_company_id=$2 AND m.role='owner' AND m.status='active' AND m.deleted_at IS NULL",[invite.created_by,company.id]);must(inviter,403,'access_denied');
 const domain=actor.email.split('@')[1],automatic=company.status==='approved'&&!!company.domain_verified_at&&company.domain===domain&&!publicDomain(domain);const member=await one(db,'INSERT INTO customer_memberships(customer_id,customer_company_id,role,status,invited_by,created_by,approved_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[own.customer_id,company.id,invite.member_role,automatic?'active':'pending',invite.created_by,actor.id,automatic?new Date(now):null]);await db.query("UPDATE customer_invitations SET status='accepted' WHERE id=$1",[invite.id]);await db.query('INSERT INTO booking_lab_memberships(customer_id,company_id,approved,active) SELECT legacy_customer_id,$1,$2,1 FROM users WHERE id=$3',[company.legacy_company_id,automatic?1:0,actor.id]);
 if(!automatic){const role=await one(db,"SELECT id FROM roles WHERE code='management'");await submitApproval(db,actor,{kind:'customer_membership',entityType:'customer_membership',entityId:member.id,reason:'Company user requires UKR approval.',roleId:role.id,payload:{}},now);}await audit(db,actor.id,'customer.invite_accepted','customer_memberships',member.id,null,{automatic,status:member.status});return {status:member.status};}
export async function companyMembers(db,actor){const company=await companyFor(db,actor);must(company?.role==='owner'&&company.membership_status==='active',403,'access_denied');return all(db,'SELECT m.id,m.role,m.status,m.version,u.email,u.display_name FROM customer_memberships m JOIN customers c ON c.id=m.customer_id JOIN users u ON u.id=c.user_id WHERE m.customer_company_id=$1 AND m.deleted_at IS NULL ORDER BY m.created_at',[company.id]);}
export async function disableCompanyMember(db,actor,memberId,version){const company=await companyFor(db,actor);must(company?.role==='owner'&&company.membership_status==='active',403,'access_denied');const member=await one(db,'SELECT m.*,c.user_id FROM customer_memberships m JOIN customers c ON c.id=m.customer_id WHERE m.id=$1 AND m.customer_company_id=$2 AND m.deleted_at IS NULL',[uuid(memberId),company.id]);optimistic(member,version);must(member.role!=='owner',409,'owner_transfer_required');await db.query("UPDATE customer_memberships SET status='disabled',version=version+1 WHERE id=$1",[member.id]);await db.query('UPDATE users SET auth_version=auth_version+1 WHERE id=$1',[member.user_id]);await db.query('UPDATE booking_lab_memberships SET active=0 WHERE customer_id=(SELECT legacy_customer_id FROM users WHERE id=$1)',[member.user_id]);await audit(db,actor.id,'customer.member_disabled','customer_memberships',member.id,null,{status:'disabled'});return {ok:true};}
export async function applyCustomerApproval(db,actor,approval,status,data,now){const table=approval.kind==='customer_company'?'customer_companies':'customer_memberships';const row=await one(db,`SELECT * FROM ${table} WHERE id=$1 AND deleted_at IS NULL`,[approval.entity_id]);must(row,404,'not_found');
 if(status==='approved'&&table==='customer_companies'){const domain=cleanDomain(data.verified_domain||'');must(!domain||!publicDomain(domain),400,'public_domain');must(!domain||data.domain_evidence_confirmed===true,400,'domain_verification_required');await db.query("UPDATE customer_companies SET status='approved',domain=$1,domain_verified_at=$2,domain_verified_by=$3,version=version+1 WHERE id=$4",[domain,domain?new Date(now):null,domain?actor.id:null,row.id]);await db.query("UPDATE booking_lab_memberships SET approved=1 WHERE company_id=$1 AND customer_id IN (SELECT u.legacy_customer_id FROM users u JOIN customers c ON c.user_id=u.id JOIN customer_memberships m ON m.customer_id=c.id WHERE m.customer_company_id=$2 AND m.status='active')",[row.legacy_company_id,row.id]);}
 else if(status==='approved'){const co=await one(db,"SELECT * FROM customer_companies WHERE id=$1 AND status='approved' AND deleted_at IS NULL",[row.customer_company_id]);must(co,409,'company_not_approved');await db.query("UPDATE customer_memberships SET status='active',approved_by=$1,approved_at=$2,version=version+1 WHERE id=$3",[actor.id,new Date(now),row.id]);await db.query('UPDATE booking_lab_memberships SET approved=1 WHERE customer_id=(SELECT u.legacy_customer_id FROM users u JOIN customers c ON c.user_id=u.id WHERE c.id=$1) AND company_id=$2',[row.customer_id,co.legacy_company_id]);}
 await audit(db,actor.id,'customer.approval_effect',table,row.id,{status:row.status},{status});}
