import {id,token,digest,email,text,uuid,language,one,all,must,fail,audit,optimistic} from './core.mjs';
import {requirePermission,actorFor} from './rbac.mjs';
import {protectedModules,actions} from './catalog.mjs';
import {enqueue} from './mail.mjs';
import {roles as legacyRoles} from '../policy.mjs';
export async function loadLegacyRoleNames(db){for(const role of await all(db,'SELECT code,name,description FROM roles WHERE deleted_at IS NULL'))if(!legacyRoles[role.code])legacyRoles[role.code]={name:role.name,purpose:role.description,grants:{}};}
export async function roleMatrix(db,actor){requirePermission(actor,'roles','view');return {roles:await all(db,'SELECT * FROM roles WHERE deleted_at IS NULL ORDER BY system_role DESC,name'),permissions:await all(db,'SELECT * FROM permissions WHERE deleted_at IS NULL ORDER BY module,action'),grants:await all(db,'SELECT * FROM role_permissions WHERE deleted_at IS NULL')};}
export async function saveRole(db,actor,data,recordId=null){requirePermission(actor,'roles',recordId?'edit':'create');const old=recordId?await one(db,'SELECT * FROM roles WHERE id=$1 AND deleted_at IS NULL',[uuid(recordId)]):null;if(recordId)optimistic(old,data.version);
 const code=old?.code||text(data.code,50,true);must(/^[a-z][a-z0-9_]{1,50}$/.test(code));must(code!=='super_admin',409,'protected_role');const name=text(data.name,100,true),description=text(data.description||'',1000);must(Array.isArray(data.grants)&&data.grants.length<=250);const seen=new Set();
 for(const grant of data.grants){uuid(grant.permission_id);must(['all','assigned','warehouse','self'].includes(grant.scope));must(!seen.has(grant.permission_id),400,'duplicate_permission');seen.add(grant.permission_id);const p=await one(db,'SELECT * FROM permissions WHERE id=$1 AND deleted_at IS NULL',[grant.permission_id]);must(p,400,'invalid_permission');must(!protectedModules.includes(p.module),403,'protected_permission');}
 const role=old?await one(db,'UPDATE roles SET name=$1,description=$2,version=version+1 WHERE id=$3 RETURNING *',[name,description,old.id]):await one(db,'INSERT INTO roles(code,name,description,created_by) VALUES($1,$2,$3,$4) RETURNING *',[code,name,description,actor.id]);
 await db.query('UPDATE role_permissions SET deleted_at=now() WHERE role_id=$1',[role.id]);for(const grant of data.grants)await db.query('INSERT INTO role_permissions(role_id,permission_id,scope,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(role_id,permission_id) DO UPDATE SET scope=EXCLUDED.scope,deleted_at=NULL,updated_at=now()',[role.id,grant.permission_id,grant.scope,actor.id]);
 await db.query('UPDATE users SET auth_version=auth_version+1 WHERE id IN (SELECT user_id FROM user_roles WHERE role_id=$1 AND deleted_at IS NULL)',[role.id]);await audit(db,actor.id,old?'role.updated':'role.created','roles',role.id,old,{...role,grants:data.grants});await loadLegacyRoleNames(db);return role;
}
export async function userList(db,actor){requirePermission(actor,'users','view');return all(db,`SELECT u.id,u.email,u.display_name,u.kind,u.state,u.department,u.country_code,u.preferred_language,u.version,u.created_at,u.last_login_at,
 COALESCE((SELECT jsonb_agg(r.id) FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=u.id AND ur.deleted_at IS NULL AND r.deleted_at IS NULL),'[]') AS role_ids,
 COALESCE((SELECT jsonb_agg(warehouse_id) FROM user_warehouses WHERE user_id=u.id AND deleted_at IS NULL),'[]') AS warehouse_ids,
 COALESCE((SELECT jsonb_agg(currency) FROM user_currencies WHERE user_id=u.id AND deleted_at IS NULL),'[]') AS currencies
 FROM users u WHERE u.kind='staff' AND u.deleted_at IS NULL ORDER BY u.created_at LIMIT 500`);}
async function accessValues(db,data){must(Array.isArray(data.role_ids)&&data.role_ids.length>0&&data.role_ids.length<=18);const roleIds=[...new Set(data.role_ids.map(uuid))];const roles=await all(db,'SELECT id,code FROM roles WHERE id=ANY($1::uuid[]) AND deleted_at IS NULL',[roleIds]);must(roles.length===roleIds.length,400,'invalid_role');
 const warehouses=[...new Set((data.warehouse_ids||[]).map(uuid))];must(warehouses.length<=100);for(const w of warehouses)must(await one(db,'SELECT id FROM warehouses WHERE id=$1 AND active=true AND deleted_at IS NULL',[w]),400,'invalid_warehouse');
 const currencies=[...new Set(data.currencies||[])];must(currencies.length<=50);for(const currency of currencies){must(typeof currency==='string'&&/^[A-Z]{3}$/.test(currency));must(await one(db,'SELECT id FROM currencies WHERE code=$1 AND active=true AND deleted_at IS NULL',[currency]),400,'invalid_currency');}
 const department=text(data.department||'',120),locale=language(data.preferred_language||'en'),country=data.country_code||null;must(country===null||/^[A-Z]{2}$/.test(country));return {roles,warehouses,currencies,department,locale,country};}
async function assign(db,actor,user,values){for(const [table,column,entries]of [['user_roles','role_id',values.roles.map(r=>r.id)],['user_warehouses','warehouse_id',values.warehouses],['user_currencies','currency',values.currencies]]){await db.query(`UPDATE ${table} SET deleted_at=now() WHERE user_id=$1`,[user.id]);for(const value of entries)await db.query(`INSERT INTO ${table}(user_id,${column},created_by) VALUES($1,$2,$3) ON CONFLICT(user_id,${column}) DO UPDATE SET deleted_at=NULL,updated_at=now()`,[user.id,value,actor.id]);}}
function primaryRole(values){return values.roles.find(r=>r.code==='super_admin')?.code||values.roles[0].code;}
export async function inviteUser(db,actor,config,data,now=Date.now()){
 requirePermission(actor,'users','create');const address=email(data.email),name=text(data.display_name,100,true);must(!await one(db,'SELECT id FROM users WHERE email=$1',[address]),409,'account_exists');must(!await one(db,'SELECT id FROM staff_users WHERE email=$1',[address]),409,'account_exists');const values=await accessValues(db,data),raw=token();await loadLegacyRoleNames(db);
 const user=await one(db,"INSERT INTO users(email,display_name,kind,state,department,country_code,preferred_language,created_by) VALUES($1,$2,'staff','invited',$3,$4,$5,$6) RETURNING *",[address,name,values.department,values.country,values.locale,actor.id]);await assign(db,actor,user,values);
 await db.query("INSERT INTO user_preferences(user_id,theme_id,language,created_by) SELECT $1,id,$2,$3 FROM themes WHERE code='ukr-blue'",[user.id,values.locale,actor.id]);
 await db.query('UPDATE staff_invites SET used=1 WHERE email=$1',[address]);await db.query('INSERT INTO staff_invites(token_hash,email,name,role,created_by,expires_at,used) VALUES($1,$2,$3,$4,$5,$6,0)',[digest(raw),address,name,primaryRole(values),actor.staff_user_id,now+172800000]);
 const link=config.origin+'/#invite='+raw;await enqueue(db,config,{code:'staff_invitation',to:address,locale:values.locale,variables:{activation_url:link},sensitive:true,dedupeKey:'staff-invite:'+user.id,actorId:actor.id,expiresAt:new Date(now+172800000)});
 await audit(db,actor.id,'user.invited','users',user.id,null,{email:address,role_ids:values.roles.map(r=>r.id)});return {id:user.id,link,emailSent:false};
}
export async function changeUser(db,actor,userId,data){requirePermission(actor,'users','edit');const old=await one(db,"SELECT * FROM users WHERE id=$1 AND kind='staff' AND deleted_at IS NULL",[uuid(userId)]);optimistic(old,data.version);const values=await accessValues(db,data);must(['active','disabled'].includes(data.state));must(data.state!=='active'||old.staff_user_id,409,'invitation_not_accepted');const name=text(data.display_name,100,true);
 const wasOwner=await one(db,"SELECT ur.id FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=$1 AND ur.deleted_at IS NULL AND r.code='super_admin'",[old.id]);if(wasOwner&&old.state==='active'&&(data.state==='disabled'||!values.roles.some(r=>r.code==='super_admin'))){const other=await one(db,"SELECT u.id FROM users u JOIN staff_users s ON s.id=u.staff_user_id JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.id<>$1 AND u.state='active' AND u.deleted_at IS NULL AND s.active=1 AND ur.deleted_at IS NULL AND r.code='super_admin' LIMIT 1",[old.id]);must(other,409,'last_super_admin');}
 await assign(db,actor,old,values);await db.query('UPDATE users SET display_name=$1,state=$2,department=$3,country_code=$4,preferred_language=$5,auth_version=auth_version+1,version=version+1 WHERE id=$6',[name,data.state,values.department,values.country,values.locale,old.id]);
 if(old.staff_user_id){await db.query('UPDATE staff_users SET name=$1,role=$2,active=$3 WHERE id=$4',[name,primaryRole(values),data.state==='active'?1:0,old.staff_user_id]);await db.query('DELETE FROM staff_sessions WHERE user_id=$1',[old.staff_user_id]);await db.query('UPDATE staff_invites SET used=1 WHERE created_by=$1',[old.staff_user_id]);await db.query('UPDATE staff_resets SET used=1 WHERE user_id=$1 OR created_by=$1',[old.staff_user_id]);}
 await db.query('UPDATE sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL',[old.id]);await db.query('UPDATE otp_codes SET invalidated_at=now() WHERE user_id=$1 AND consumed_at IS NULL AND invalidated_at IS NULL',[old.id]);await db.query('UPDATE staff_invites SET used=1 WHERE email=$1',[old.email]);await db.query('UPDATE user_preferences SET language=$1,version=version+1 WHERE user_id=$2',[values.locale,old.id]);await audit(db,actor.id,'user.access_changed','users',old.id,{state:old.state,department:old.department},{...data},'Access changes revoke every session.');return {ok:true};
}
export async function resetUser(db,actor,config,userId,now=Date.now()){requirePermission(actor,'users','edit');const user=await one(db,"SELECT * FROM users WHERE id=$1 AND kind='staff' AND state='active' AND deleted_at IS NULL",[uuid(userId)]);must(user?.staff_user_id,404,'not_found');const raw=token();await db.query('UPDATE staff_resets SET used=1 WHERE user_id=$1',[user.staff_user_id]);await db.query('INSERT INTO staff_resets(token_hash,user_id,created_by,expires_at,used) VALUES($1,$2,$3,$4,0)',[digest(raw),user.staff_user_id,actor.staff_user_id,now+1800000]);await audit(db,actor.id,'user.recovery_requested','users',user.id);return {link:config.origin+'/#reset='+raw,emailSent:false};}
export async function logs(db,actor,{search='',limit=100}={}){requirePermission(actor,'logs','view');must(Number.isInteger(limit)&&limit>0&&limit<=500);const q='%'+text(search,100)+'%';return all(db,'SELECT a.*,u.display_name AS actor_name FROM audit_log a LEFT JOIN users u ON u.id=a.actor_id WHERE a.action ILIKE $1 OR a.entity_id ILIKE $1 OR a.reason ILIKE $1 ORDER BY a.created_at DESC,a.id DESC LIMIT $2',[q,limit]);}
