import test from 'node:test';
import assert from 'node:assert/strict';
import {openDatabase,migrate} from '../../services/staff/phase1/db.mjs';
import {id,one,all} from '../../services/staff/phase1/core.mjs';
import {actorFor} from '../../services/staff/phase1/rbac.mjs';
import {listBookings,getBooking,submitBooking,updateETA,bookingApi} from '../../services/staff/phase2/bookings.mjs';
const connection=process.env.TEST_DATABASE_URL;
if(!connection||!new URL(connection).pathname.includes('test'))throw Error('A disposable TEST_DATABASE_URL is required.');
const schema='booking_intake_'+id().replaceAll('-','');
const admin=await openDatabase(connection);await admin.query('CREATE SCHEMA '+schema);
const store=await openDatabase(connection,{options:'-c search_path='+schema+',public'});
const tx=fn=>store.tx(fn),code=x=>e=>e.code===x;
const fields={service:'air_ddp',origin:'Guangzhou',destination:'Dubai',origin_country:'CN',destination_country:'AE',phone:'+971000000000',legal_owner_name:'Example test company',cargo_summary:'Synthetic cartons'};
async function addCustomer(address,{companyId=null,role='owner',status='pending'}={}) {
 return tx(async db=>{const u=await one(db,"INSERT INTO users(email,display_name,kind,state) VALUES($1,'Test customer','customer','active') RETURNING id",[address]);const c=await one(db,'INSERT INTO customers(user_id,created_by) VALUES($1,$1) RETURNING id',[u.id]);
 let company=companyId;if(!company){company=(await one(db,'INSERT INTO customer_companies(legal_name,owner_customer_id,status,created_by) VALUES($1,$2,$3,$4) RETURNING id',['Synthetic '+address,c.id,status,u.id])).id;}
 await db.query("INSERT INTO customer_memberships(customer_id,customer_company_id,role,status,created_by) VALUES($1,$2,$3,'active',$4)",[c.id,company,role,u.id]);return {actor:await actorFor(db,u.id),customerId:c.id,companyId:company};});
}
let owner,alice,bob,viewOnly,booking;
await test('Phase 2 booking intake on real PostgreSQL',async t=>{
 try {
 await t.test('additive migration runs twice without duplicating or seeding bookings',async()=>{assert.match((await one(store,'SHOW server_version')).server_version,/^18\./);await migrate(store);await migrate(store);assert.equal((await one(store,'SELECT count(*)::int AS n FROM bookings')).n,0);});
 await t.test('fixtures create only isolated accounts and use database permissions',async()=>{const legacy=id();await store.query("INSERT INTO staff_users(id,email,name,role,password_hash,active,created_at) VALUES($1,'owner@example.test','Test owner','super_admin','test-fixture-not-a-password',1,$2)",[legacy,Date.now()]);const u=await one(store,"INSERT INTO users(email,display_name,kind,state,staff_user_id) VALUES('owner@example.test','Test owner','staff','active',$1) RETURNING id",[legacy]);await store.query("INSERT INTO user_roles(user_id,role_id) SELECT $1,id FROM roles WHERE code='super_admin'",[u.id]);owner=await actorFor(store,u.id);alice=await addCustomer('alice@example.test');bob=await addCustomer('bob@example.test');});
 await t.test('pending customer can submit one own-company request with a task and code',async()=>{const result=await tx(db=>submitBooking(db,alice.actor,fields,'test_request_alice_0001'));booking=result.booking;assert.match(booking.code,/^UKR-\d{4}-\d{8,}$/);assert.equal(booking.source,'customer_portal');assert.equal(booking.status,'submitted');assert.equal(booking.eta,null);assert.equal(result.events.length,1);assert.equal((await one(store,'SELECT count(*)::int AS n FROM tasks WHERE entity_id=$1',[booking.id])).n,1);});
 await t.test('retries return the same booking and conflicting payloads fail',async()=>{const results=await Promise.all(Array.from({length:3},()=>tx(db=>submitBooking(db,alice.actor,fields,'test_request_alice_0001'))));assert.ok(results.every(r=>r.booking.id===booking.id&&r.replayed));await assert.rejects(tx(db=>submitBooking(db,alice.actor,{...fields,cargo_summary:'changed'},'test_request_alice_0001')),code('idempotency_conflict'));assert.equal((await one(store,'SELECT count(*)::int AS n FROM bookings')).n,1);});
 await t.test('another customer cannot list or retrieve the booking even with its UUID',async()=>{assert.equal((await tx(db=>listBookings(db,bob.actor))).total,0);await assert.rejects(tx(db=>getBooking(db,bob.actor,booking.id)),code('not_found'));});
 await t.test('staff can create a linked request without a separate customer-side copy',async()=>{const r=await tx(db=>submitBooking(db,owner,{...fields,customer_id:alice.customerId},'staff_request_alice_0001'));assert.equal(r.booking.source,'staff_booking');const list=await tx(db=>listBookings(db,alice.actor));assert.equal(list.total,2);assert.ok(list.items.some(x=>x.id===r.booking.id));});
 await t.test('ETA update is persisted and reflected in the customer detail with filtered history',async()=>{const eta='2026-11-02T10:00:00.000Z';await tx(db=>updateETA(db,owner,booking.id,{version:1,eta,reason:'Internal: schedule checked'}));const r=await tx(db=>getBooking(db,alice.actor,booking.id));assert.equal(new Date(r.booking.eta).toISOString(),eta);assert.equal(r.events.filter(e=>e.kind==='eta_changed').length,1);assert.ok(!JSON.stringify(r).includes('Internal: schedule checked'));assert.ok(!JSON.stringify(r).includes('created_by'));});
 await t.test('customers cannot update ETA and stale staff edits cannot overwrite data',async()=>{await assert.rejects(tx(db=>updateETA(db,alice.actor,booking.id,{version:2,eta:null,reason:'unauthorised'})),code('access_denied'));await assert.rejects(tx(db=>updateETA(db,owner,booking.id,{version:1,eta:null,reason:'stale'})),code('record_changed'));});
 await t.test('customer DTO never returns agreement costs or staff-only events',async()=>{await store.query('UPDATE bookings SET agreement_snapshot=$1 WHERE id=$2',[JSON.stringify({purchase_rate:'PRIVATE_COST'}),booking.id]);await store.query("INSERT INTO booking_status_events(booking_id,to_status,note,customer_visible,created_by) VALUES($1,'submitted','PRIVATE_NOTE',false,$2)",[booking.id,owner.id]);const r=await tx(db=>getBooking(db,alice.actor,booking.id));assert.ok(!JSON.stringify(r).includes('PRIVATE'));});
 await t.test('approved company view-only member can read but cannot submit',async()=>{await store.query("UPDATE customer_companies SET status='approved' WHERE id=$1",[alice.companyId]);viewOnly=await addCustomer('viewer@example.test',{companyId:alice.companyId,role:'view_only'});assert.equal((await tx(db=>listBookings(db,viewOnly.actor))).total,2);await assert.rejects(tx(db=>submitBooking(db,viewOnly.actor,fields,'read_only_request_0001')),code('read_only_account'));});
 await t.test('membership and user revocation are effective immediately',async()=>{await store.query("UPDATE customer_memberships SET status='disabled' WHERE customer_id=$1",[viewOnly.customerId]);await assert.rejects(tx(db=>getBooking(db,viewOnly.actor,booking.id)),code('access_denied'));await store.query("UPDATE users SET state='disabled' WHERE id=$1",[bob.actor.id]);await assert.rejects(tx(db=>listBookings(db,bob.actor)),code('sign_in_required'));});
 await t.test('transaction rollback removes booking, retry claim, event and task together',async()=>{const before=(await one(store,'SELECT count(*)::int AS n FROM bookings')).n;await assert.rejects(tx(async db=>{await submitBooking(db,alice.actor,fields,'rollback_request_0001');throw Error('Rollback fixture');}),/Rollback fixture/);assert.equal((await one(store,'SELECT count(*)::int AS n FROM bookings')).n,before);const retry=await tx(db=>submitBooking(db,alice.actor,fields,'rollback_request_0001'));assert.equal(retry.replayed,false);});
 await t.test('booking identity is immutable at the SQL boundary',async()=>{await assert.rejects(store.query('UPDATE bookings SET customer_company_id=$1 WHERE id=$2',[bob.companyId,booking.id]),e=>e.code==='23514');await assert.rejects(store.query("UPDATE bookings SET code='rewritten' WHERE id=$1",[booking.id]),e=>e.code==='23514');});
 await t.test('the authenticated API dispatcher reaches the shared booking implementation',async()=>{const r=await tx(db=>bookingApi({db,context:{actor:alice.actor},path:'/bookings',method:'GET',url:new URL('https://portal.example.test/api/portal/bookings?limit=1')}));assert.equal(r.items.length,1);assert.equal(r.total,3);});
 } finally {await store.close();await admin.query('DROP SCHEMA '+schema+' CASCADE');await admin.close();}
});
