'use strict';
async function routesPage(){
  const content=page('Routes & services'),{routes}=await api('/routes');
  const intro=panel('Set your regular service routes','Create each route once. Choose the services you operate and map customer city or country names to your ports. Weekly prices are managed separately.');intro.append(button('＋ Add a route',()=>editRoute(), 'primary'),button('Weekly prices & Excel',ratesPage));content.append(intro);
  if(!routes.length)content.append(element('p','No routes yet. Add your first route, then download its Excel pricing sheet.','empty'));
  for(const r of routes){const card=panel(r.origin+' → '+r.destination,r.active?'Active service route':'Inactive route');card.append(element('p',r.products.map(p=>tariffProducts[p]).join(' · ')),element('p','Loading cities: '+(r.originAliases.join(', ')||r.origin)),element('p','Discharge cities: '+(r.destinationAliases.join(', ')||r.destination)),button('Edit route',()=>editRoute(r)));content.append(card);}
}
function editRoute(r={active:true,products:['AIR','LCL','LCL_DDP','FCL20','FCL40','FCL45']}){
  const content=page(r.id?'Edit route':'Add route');content.append(button('← Routes',routesPage));const form=element('form',undefined,'panel tariff-editor'),grid=element('div',undefined,'tariff-grid');form.append(grid);const fields={};
  for(const [key,label,help] of [['origin','Port of loading / origin hub','e.g. Ningbo, China'],['originCountry','Origin country','e.g. China'],['destination','Port of discharge / destination hub','e.g. Jebel Ali, UAE'],['destinationCountry','Destination country','e.g. UAE'],['airOrigin','Origin airport (optional)','Airport used for this route’s air service'],['airDestination','Destination airport (optional)','e.g. DXB Airport, UAE']]){fields[key]=tariffField(grid,key,label,r[key]||'','text',null,help);fields[key].required=!key.startsWith('air');}
  for(const [key,label,help]of [['originAliases','Origin cities / alternative names','One per line. Add only cities served through this origin.'],['destinationAliases','Destination cities / alternative names','One per line. Example: Dubai then Dubai, UAE on separate lines.']]){fields[key]=tariffField(grid,key,label,(r[key]||[]).join('\n'),'textarea',null,help);fields[key].required=false;}
  form.append(element('h2','Services you regularly operate'));const checks={};const options=element('div',undefined,'service-checks');for(const [key,label]of Object.entries(tariffProducts).filter(([key])=>key!=='FCL40HC')){const wrap=element('label',undefined,'check-row'),box=element('input');box.type='checkbox';box.checked=r.products.includes(key);wrap.append(box,document.createTextNode(label));checks[key]=box;options.append(wrap);}form.append(options);
  const active=element('label',undefined,'check-row'),box=element('input');box.type='checkbox';box.checked=r.active;active.append(box,document.createTextNode('Active route — show its services to customers'));form.append(active,element('p','Customers see a starting price only when a current tariff is published. Otherwise they can request a quotation.','notice'));
  const err=element('p',undefined,'error'),save=element('button','Save route','primary');save.type='submit';form.append(err,save);form.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;try{await api(r.id?'/routes/'+r.id:'/routes',r.id?'PATCH':'POST',{...Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])),products:Object.keys(checks).filter(k=>checks[k].checked),active:box.checked,version:r.version});await routesPage();$('appSuccess').textContent='Route saved. Download Excel to fill its weekly charges.';}catch(e){err.textContent=e.message;}finally{save.disabled=false;}});content.append(form);
}
function addExcelTools(content){
  const p=panel('Update prices with Excel','Download your active routes, fill the buying rates and markup, then upload. Blank buying-rate rows are skipped. You review changes before saving or publishing.');const tools=element('div',undefined,'tariff-actions'),week=element('input');week.type='date';week.value=new Date().toISOString().slice(0,10);week.setAttribute('aria-label','Excel week start');tools.append(week,button('Download Excel',async()=>{const data=await api('/rate-workbook?week='+week.value);const bytes=Uint8Array.from(atob(data.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),link=element('a');link.href=url;link.download=data.filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);},'primary'),button('Manage routes',routesPage));p.append(tools);
  const label=element('label','Upload completed Excel (.xlsx, up to 1 MB)'),file=element('input');file.type='file';file.accept='.xlsx';label.append(file);p.append(label);const status=element('p',undefined,'helper');status.setAttribute('role','status');const preview=element('div',undefined,'import-preview');p.append(status,preview);let revision=0;
  file.addEventListener('change',async()=>{const current=++revision;preview.replaceChildren();if(!file.files[0])return;status.textContent='Checking workbook…';try{const upload=file.files[0];if(upload.size>1024*1024||!upload.name.toLowerCase().endsWith('.xlsx'))throw Error('Choose an .xlsx file no larger than 1 MB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(upload);});const result=await api('/rate-workbook/preview','POST',{base64});if(current!==revision)return;if(result.errors.length){status.textContent='Nothing saved. Correct these rows and upload again.';for(const e of result.errors)preview.append(element('p','Row '+e.row+': '+e.message,'error'));return;}status.textContent=result.rows.length+' valid rate(s). Check the selling prices below.';for(const r of result.rows){const card=element('article',undefined,'tariff-card');card.append(element('h3',`${r.action}: ${r.origin} → ${r.destination}`),element('p',`${tariffProducts[r.product]} · ${r.validFrom} to ${r.validTo}`),element('p',`Buy ${priceText(r.buyRate,r.currency)} + ${r.markupType==='percent'?r.markup+'%':priceText(r.markup,r.currency)} → Sell ${priceText(r.unitPrice,r.currency)} / unit`));if(r.exwFrom!==null)card.append(element('p','EXW pickup + export customs from '+priceText(r.exwFrom,r.currency)+' / shipment'));preview.append(card);}const actions=element('div',undefined,'tariff-actions');const commit=async publish=>{actions.querySelectorAll('button').forEach(b=>b.disabled=true);try{const out=await api('/rate-workbook/commit','POST',{importId:result.importId,publish});await ratesPage();$('appSuccess').textContent=out.saved+' rates '+(out.published?'published. Customer searches now use them.':'saved as drafts.');}catch(e){actions.querySelectorAll('button').forEach(b=>b.disabled=false);status.textContent='Nothing saved. '+e.message;}};actions.append(button('Save all as drafts',()=>commit(false)),button('Publish these rates',()=>commit(true),'primary'));preview.append(actions);}catch(e){if(current===revision)status.textContent=e.message;}});content.append(p);
}
