import {readFile,writeFile} from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const out='preview-dist';
let css=await readFile(`${out}/refinements.css`,'utf8');
css+='\n.kbody{min-width:0}.knowledge-header .wrap{gap:12px}@media(max-width:600px){.knowledge-header img{width:135px}.knowledge-nav{gap:8px}}\n';
await writeFile(`${out}/refinements.css`,css);
let html=await readFile(`${out}/index.html`,'utf8');
html=html.replace('src="/assets/hero.svg"','src="/assets/hero.svg?v=4"').replaceAll('src="/assets/logo.svg"','src="/assets/logo.svg?v=4"').replace("$('brandLogo').src='/assets/logo.svg';","$('brandLogo').src='/assets/logo.svg?v=4';");
html=html.replace('<span class="preview-note">Test preview · No live bookings or payments</span>','<span class="preview-note">Test preview · No live bookings or payments<br><a href="/data/ports-metadata.json">Port data: UNECE UN/LOCODE 2025-1 · CC BY 4.0</a></span>');
await writeFile(`${out}/index.html`,html);
let ui=await readFile(`${out}/ports-ui.js`,'utf8');
ui=ui.replace('return a.countryPriority-b.countryPriority||',"const ac=destination&&!q&&!country&&a.countryCode==='AE'?-1:a.countryPriority,bc=destination&&!q&&!country&&b.countryCode==='AE'?-1:b.countryPriority;return ac-bc||");
await writeFile(`${out}/ports-ui.js`,ui);
for(const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(match[1].trim())new vm.Script(match[1]);
for(const file of ['ports-ui.js','knowledge.js','theme.js','data/ports.js'])new vm.Script(await readFile(`${out}/${file}`,'utf8'),{filename:file});
const data=JSON.parse(await readFile(`${out}/data/ports.json`,'utf8'));
assert.equal(data.metadata.archiveSha256,'ad409fc7149b10f98d61190c34d9daf78b78bb8b31464cc66de1a89d09b01b5d','Official release archive changed; review before updating the pinned source.');
const context={window:{}};vm.createContext(context);vm.runInContext(ui,context);const engine=context.window.UKRPortSearch;
const ports=data.ports.map(p=>({...p,value:`${p.name}, ${p.country} (${p.code})`})),indexed=engine.index(ports,data.countries);
const search=(q,c='',dest=false)=>engine.search(indexed,data.countries,q,c,dest).items;
const checks=[];function check(label,ok){assert.ok(ok,label);checks.push(label);}
check('unique canonical port identifiers',new Set(ports.map(p=>p.code)).size===ports.length);
check('all records carry maritime function',ports.every(p=>p.functions.startsWith('1')));
check('China country search',search('China').length>50&&search('China').every(p=>p.countryCode==='CN'));
check('China major-port priority',/^Shanghai/i.test(search('China')[0].name));
check('Ningbo spelling tolerance',search('Ningboo').some(p=>/^Ningbo/i.test(p.name)));
check('Nansha lookup',search('Nansha').some(p=>p.code==='CNNSA'));
check('familiar Ningbo code is searchable',search('CNNGB').some(p=>/^Ningbo/i.test(p.name)));
check('UAE alias',search('UAE').length>0&&search('UAE').every(p=>p.countryCode==='AE'));
check('Jebel Ali first destination',search('','',true)[0].code==='AEJEA');
check('UAE destination group remains together',search('','',true)[1].countryCode==='AE');
check('UK country alias',search('UK').length>0&&search('UK').every(p=>p.countryCode==='GB'));
check('Canada country search',search('Canada').length>0&&search('Canada').every(p=>p.countryCode==='CA'));
check('country filtering',search('','TR').length>0&&search('','TR').every(p=>p.countryCode==='TR'));
check('unknown port does not become an offer',search('zzzzzzzzzzzz').length===0);
check('headline and legal identity',html.includes('Book &amp; Ship.')&&html.includes('Made Simple.')&&html.includes('UKR SEA Shipping CO LLC'));
for(const path of ['knowledge.html','knowledge/container-sizes.html','knowledge/what-is-cbm.html','knowledge/how-to-calculate-cbm.html','knowledge/cbm-calculator.html'])check('page '+path,(await readFile(`${out}/${path}`,'utf8')).includes('UKR SEA Shipping CO LLC'));
const report={passed:checks.length,checks,portCount:ports.length,countriesWithMaritimePorts:new Set(ports.map(p=>p.countryCode)).size,sourceRelease:data.metadata.release,sourceSha256:data.metadata.archiveSha256,chinaPorts:search('China').length,uaePorts:search('UAE').length,examples:search('China').slice(0,12).map(p=>({code:p.code,name:p.name})),scope:'Build syntax and full-dataset checks. Browser interaction checks are separate.'};
await writeFile(`${out}/build-checks.json`,JSON.stringify(report,null,2));console.log('UKR_VERIFIED_BUILD '+JSON.stringify(report));
