/* Knowledge search and calculator share the same locale, without changing entered measurements. */
(function(){
 'use strict';const $=s=>document.getElementById(s);let category='All';const U=()=>window.UKRTranslate;
 const normalize=s=>s.normalize('NFKD').replace(/\p{M}/gu,'').toLocaleLowerCase().trim();
 function filter(){const q=normalize($('knowledgeSearch')?.value||'');let count=0;document.querySelectorAll('.kcard').forEach(c=>{const haystack=normalize(c.dataset.search+' '+c.textContent);const show=(category==='All'||c.dataset.category===category)&&(!q||haystack.includes(q));c.hidden=!show;if(show)count++;});if($('knowledgeEmpty'))$('knowledgeEmpty').hidden=count>0;}
 $('knowledgeSearch')?.addEventListener('input',filter);window.addEventListener('ukr:translated',filter);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();}));
 if(!$('cbmForm'))return;let serial=0,last=null;
 function invalidate(){$('cbmResult').hidden=true;last=null;}
 function render(){if(!last||!U())return;const {volume,weight,qty,allWeights}=last;U().set($('cbmVolume'),'{n} CBM',{n:U().number(volume,{maximumFractionDigits:6})});
 $('cbmDetails').replaceChildren();const count=document.createElement('span');U().set(count,'{n} packages',{n:qty});$('cbmDetails').append(count,document.createTextNode(' · '));const gross=document.createElement('span');U().set(gross,allWeights?'{n} kg total gross weight':'Gross weight not complete',{n:U().number(weight,{maximumFractionDigits:3})});$('cbmDetails').append(gross);
 const p=new URLSearchParams({service:'lcl',cbm:String(Number(volume.toFixed(6))),lang:U().locale()});if(allWeights)p.set('weight',String(Number(weight.toFixed(3))));$('cbmUse').href='/?'+p.toString();$('cbmUse').hidden=volume>99999||volume<0.01||(allWeights&&weight>999999);
 if($('cbmUse').hidden){const note=document.createElement('span');U().set(note,'This volume or weight needs a manual UKR quote.');$('cbmDetails').append(document.createTextNode(' · '),note);}$('cbmResult').hidden=false;}
 function add(){if(document.querySelectorAll('.cbm-row').length>=50)return;const id=++serial,row=document.createElement('section');row.className='cbm-row';row.innerHTML=`<header><b>Package size ${id}</b><button type="button" class="cbm-remove" aria-label="Remove package size ${id}">Remove</button></header><div class="cbm-fields"><label>Length<input name="length" type="number" min="0.001" max="100000" step="any" required></label><label>Width<input name="width" type="number" min="0.001" max="100000" step="any" required></label><label>Height<input name="height" type="number" min="0.001" max="100000" step="any" required></label><label>Unit<select name="unit"><option value="0.01">cm</option><option value="1">m</option><option value="0.001">mm</option><option value="0.0254">inches</option></select></label><label>Quantity<input name="quantity" type="number" min="1" max="100000" step="1" value="1" required></label><label>Gross kg / package<input name="weight" type="number" min="0.001" max="1000000" step="any" placeholder="Optional"></label></div>`;
 row.querySelector('.cbm-remove').addEventListener('click',()=>{row.remove();if(!document.querySelector('.cbm-row'))add();invalidate();$('cbmAdd').disabled=false;});row.addEventListener('input',invalidate);row.addEventListener('change',invalidate);$('cbmRows').append(row);$('cbmAdd').disabled=document.querySelectorAll('.cbm-row').length>=50;invalidate();}
 $('cbmAdd').addEventListener('click',add);add();window.addEventListener('ukr:languagechange',render);
 $('cbmForm').addEventListener('submit',e=>{e.preventDefault();let volume=0,weight=0,qty=0,allWeights=true;for(const row of document.querySelectorAll('.cbm-row')){const value=n=>Number(row.querySelector('[name="'+n+'"]').value);const q=value('quantity'),u=value('unit');volume+=value('length')*value('width')*value('height')*u*u*u*q;qty+=q;const w=row.querySelector('[name="weight"]').value;if(w==='')allWeights=false;else weight+=Number(w)*q;}if(!Number.isFinite(volume)||volume<=0)return;last={volume,weight,qty,allWeights};render();});
})();
