import {readFile,writeFile,copyFile,readdir} from 'node:fs/promises';
import {buildKnowledge} from './knowledge.mjs';
import {importPorts} from '../database/import-ports.mjs';
const out='preview-dist',legal='UKR SEA Shipping CO LLC';
const directory=await importPorts({out});
let html=await readFile(`${out}/index.html`,'utf8');
const replace=(old,value)=>{if(!html.includes(old))throw Error('Preview structure changed: '+old.slice(0,90));html=html.replace(old,value);};
replace('<h1>Book. Ship.<span>Easy Like Nothing Before.</span></h1>','<h1>Book &amp; Ship.<span>Made Simple.</span></h1>');
html=html.replaceAll('UKR Shipping &amp; Logistics',legal).replaceAll('UKR SEA SHIPPING CO LLC - Dubai',legal).replaceAll('UKR SEA SHIPPING CO LLC',legal);
html=html.replaceAll('Book. Ship. Easy. | UKR Shipping | Homepage draft','Book & Ship. Made Simple. | '+legal);
html=html.replace('>Book shipment</a><details>','>Book &amp; Ship</a><details>');
replace('<div class="dropdown">','<div class="dropdown"><a href="/knowledge.html">Knowledge Centre</a>');
html=html.replace('<h3>Information &amp; tools</h3>','<h3>Information &amp; tools</h3><a href="/knowledge.html">Knowledge Centre</a>');
replace('</head>','<link rel="stylesheet" href="/refinements.css?v=4"></head>');
replace('<script>','<script src="/data/ports.js?v=2025-1"></script><script src="/ports-ui.js?v=4"></script><script>');
if(!/const portGroups=/.test(html))throw Error('Port fixture marker not found');
html=html.replace(/\/\/ Curated preview locations[\s\S]*?const ddpCountries/,`// Shared UNECE maritime directory, kept separate from prices and availability.\nconst ports=window.UKR_PORT_DIRECTORY.ports.map(p=>({...p,value:p.name+', '+p.country+' ('+p.code+')'}));\nconst ddpCountries`);
const portField=`function portField(label,name){return \`<div class="field port-field"><label for="port-\${name}">\${label}</label><input id="port-\${name}" name="\${name}" type="text" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="ports-\${name}-options" autocomplete="off" placeholder="Port, country or code" maxlength="220" required><input name="\${name}Code" type="hidden"><input name="\${name}Country" type="hidden"><div class="combo-list" id="ports-\${name}" hidden><label class="port-country-label">Browse by country<select aria-label="Filter \${name} ports by country"><option value="">All countries</option></select></label><p class="port-status" aria-live="polite"></p><div id="ports-\${name}-options" role="listbox" aria-label="\${label}"></div><button type="button" class="port-more" hidden>Show more ports</button></div></div>\`;}`;
html=html.replace(/function portField\([\s\S]*?\nfunction renderTabs/,portField+'\nfunction renderTabs');
html=html.replace(/function installCombobox\([\s\S]*?\nfunction landDestinations/,`function installCombobox(input){window.UKRPortSearch.install(input,ports,window.UKR_PORT_DIRECTORY.countries);}\nfunction landDestinations`);
replace("$('searchFields').innerHTML=html;",`$('searchFields').innerHTML=html;\nif(['fcl','lcl'].includes(id)){const p=ports.find(p=>p.code==='AEJEA');for(const [k,v]of Object.entries({destination:p.value,destinationCode:p.code,destinationCountry:p.countryCode}))$('searchForm').elements[k].value=v;}`);
html=html.replace('Choose from the preview port directory. Full world-port coverage and live inventory will be connected before launch.',`Search ${directory.ports.length.toLocaleString('en')} maritime locations by port, country or code. Jebel Ali is your starting destination. A listed port does not confirm a shipping service or rate.`);
html=html.replaceAll('Select both ports from the preview directory.','Choose origin and destination from the port directory.');
html=html.replace('state.search={service:state.service,...data};',`state.search={service:state.service,...data,equipment:({'20 FT':'20GP','40 FT':'40GP','40 HC':'40HC','45 FT':'45HC'})[data.container]||null};`);
replace('renderTabs();applyView();',`renderTabs();applyView();\nconst incoming=new URLSearchParams(location.search);if(['fcl','lcl'].includes(incoming.get('service'))){chooseService(incoming.get('service'));for(const key of ['cbm','weight']){const value=Number(incoming.get(key)),field=$('searchForm').elements[key];if(field&&Number.isFinite(value)&&value>=Number(field.min)&&value<=Number(field.max))field.value=String(value);}}`);
const css=html.match(/<style>([\s\S]*?)<\/style>/)?.[1];if(!css)throw Error('Base styles missing');await writeFile(`${out}/base.css`,css);
await writeFile(`${out}/index.html`,html);
for(const name of ['refinements.css','ports-ui.js'])await copyFile(`preview/${name}`,`${out}/${name}`);
let hero=await readFile(`${out}/assets/hero.svg`,'utf8');const patch=(await readFile('preview/tower-patch.svg','utf8')).match(/<image[\s\S]*?\/>/)?.[0];if(!patch)throw Error('Tower patch missing');await writeFile(`${out}/assets/hero.svg`,hero.replace('</svg>',patch+'</svg>'));
let logo=await readFile(`${out}/assets/logo.svg`,'utf8');logo=logo.replace('</svg>',`<rect x="71" y="63" width="153" height="29" fill="white"/><text x="72" y="74" font-family="Arial,Helvetica,sans-serif" font-size="10.1" font-weight="700" fill="#063b66" textLength="149" lengthAdjust="spacingAndGlyphs">SEA SHIPPING CO LLC</text><text x="73" y="87" font-family="Arial,Helvetica,sans-serif" font-size="6.6" letter-spacing="1.1" fill="#16486d">SEA · AIR · ROAD</text></svg>`);await writeFile(`${out}/assets/logo.svg`,logo);
for(const file of await readdir(out)){if(!file.endsWith('.html')||file==='index.html')continue;let body=await readFile(`${out}/${file}`,'utf8');body=body.replaceAll('UKR Shipping &amp; Logistics',legal).replace('</main>',`<p class="legal-company">${legal}</p><a href="/knowledge.html">Visit the Knowledge Centre</a></main>`);await writeFile(`${out}/${file}`,body);}
await buildKnowledge(out);
const version=JSON.parse(await readFile(`${out}/version.json`,'utf8'));Object.assign(version,{revision:4,legalName:legal,portCount:directory.ports.length,portSourceRelease:directory.metadata.release,portSourceSha256:directory.metadata.archiveSha256,knowledgeCentre:true,liveRates:false,liveBookings:false,artworkEdit:'Tower-only overlay; original artwork outside mask preserved.'});await writeFile(`${out}/version.json`,JSON.stringify(version));
if(!html.includes('Book &amp; Ship.')||!html.includes('Made Simple.')||!html.includes('AEJEA')||html.includes('const portGroups='))throw Error('Homepage revision checks failed');
console.log('UKR_REVISION_4_CHECKS headline, legal name, shared ports, default AEJEA, distinct equipment, separate Knowledge Centre: PASS');
