// Published Knowledge Centre content; carrier numbers, source links and formulas are retained.
export default String.raw`
Knowledge Centre|مركز المعرفة|База знаний|Centre de connaissances|معلوماتی مرکز|ज्ञान केंद्र|知识中心
UKR KNOWLEDGE CENTRE|مركز معرفة UKR|БАЗА ЗНАНИЙ UKR|CENTRE DE CONNAISSANCES UKR|UKR معلوماتی مرکز|UKR ज्ञान केंद्र|UKR知识中心
Know your cargo.|تعرّف على شحنتك.|Изучите свой груз.|Connaissez votre fret.|اپنے سامان کو جانیں۔|अपने माल को समझें।|了解您的货物。
Plan your shipment.|خطّط لشحنتك.|Планируйте перевозку.|Planifiez votre expédition.|اپنی شپمنٹ کی منصوبہ بندی کریں۔|अपने शिपमेंट की योजना बनाएँ।|规划您的运输。
Practical shipping guides and easy-to-use calculators. Find what you need, then continue to your shipping search.|أدلة شحن عملية وحاسبات سهلة الاستخدام. اعثر على ما تحتاجه، ثم تابع البحث عن شحنتك.|Практические руководства и простые калькуляторы. Найдите нужную информацию и переходите к поиску перевозки.|Des guides pratiques et des calculateurs simples. Trouvez l’information utile, puis poursuivez votre recherche de transport.|عملی شپنگ رہنما اور آسان کیلکولیٹر۔ اپنی ضرورت کی معلومات تلاش کریں، پھر شپنگ کی تلاش جاری رکھیں۔|व्यावहारिक शिपिंग मार्गदर्शिकाएँ और आसान कैलकुलेटर। ज़रूरी जानकारी पाएँ, फिर शिपिंग की खोज जारी रखें।|实用物流指南与便捷计算工具。查找所需信息，然后继续查询运输方案。
Search guides and tools|ابحث في الأدلة والأدوات|Поиск руководств и инструментов|Rechercher des guides et des outils|رہنما اور ٹولز تلاش کریں|मार्गदर्शिकाएँ और टूल खोजें|搜索指南和工具
Try container sizes, CBM or cartons|جرّب: أحجام الحاويات أو CBM أو الكراتين|Например: размеры контейнеров, CBM, коробки|Essayez : conteneurs, CBM ou cartons|کنٹینر کے سائز، CBM یا کارٹن تلاش کریں|कंटेनर आकार, CBM या कार्टन खोजें|试试箱型尺寸、CBM或纸箱
Filter topics|تصفية المواضيع|Фильтр тем|Filtrer les thèmes|موضوعات فلٹر کریں|विषय फ़िल्टर करें|筛选主题
All|الكل|Все|Tout|سب|सभी|全部
CBM & tools|الحجم والأدوات|Объём и инструменты|CBM et outils|CBM اور ٹولز|CBM और टूल|CBM与工具
Guides|الأدلة|Руководства|Guides|رہنما|मार्गदर्शिकाएँ|指南
Carrier guides|أدلة الناقلين|Справочник перевозчиков|Guides des transporteurs|کیریئر کے رہنما|वाहक मार्गदर्शिकाएँ|承运人指南
Guides and calculators|الأدلة والحاسبات|Руководства и калькуляторы|Guides et calculateurs|رہنما اور کیلکولیٹر|मार्गदर्शिकाएँ और कैलकुलेटर|指南与计算工具
Open calculator|افتح الحاسبة|Открыть калькулятор|Ouvrir le calculateur|کیلکولیٹر کھولیں|कैलकुलेटर खोलें|打开计算器
Read guide|اقرأ الدليل|Читать руководство|Lire le guide|رہنما پڑھیں|मार्गदर्शिका पढ़ें|阅读指南
Shipping line profiles & comparisons|معلومات ومقارنات خطوط الشحن|Профили и сравнения морских линий|Profils et comparaisons des compagnies maritimes|شپنگ لائنوں کا تعارف اور موازنہ|शिपिंग लाइनों का परिचय और तुलना|船公司介绍与比较
Ask UKR about carrier options for your route.|اسأل UKR عن خيارات الناقلين لمسارك.|Спросите UKR о перевозчиках для вашего маршрута.|Demandez à UKR les transporteurs disponibles pour votre itinéraire.|اپنے راستے کے کیریئر آپشنز کے لیے UKR سے پوچھیں۔|अपने मार्ग के वाहक विकल्पों के बारे में UKR से पूछें।|向UKR咨询适合您路线的承运人。
Contact our team|تواصل مع فريقنا|Свяжитесь с командой|Contactez notre équipe|ہماری ٹیم سے رابطہ کریں|हमारी टीम से संपर्क करें|联系我们的团队
No matching guide. Try another topic or clear the search.|لا يوجد دليل مطابق. جرّب موضوعًا آخر أو امسح البحث.|Подходящих руководств нет. Попробуйте другую тему или очистите поиск.|Aucun guide correspondant. Essayez un autre sujet ou effacez la recherche.|کوئی متعلقہ رہنما نہیں ملا۔ دوسرا موضوع آزمائیں یا تلاش صاف کریں۔|कोई उपयुक्त मार्गदर्शिका नहीं मिली। दूसरा विषय खोजें या खोज साफ़ करें।|未找到匹配指南。请尝试其他主题或清空搜索。
On this page|في هذه الصفحة|На этой странице|Sur cette page|اس صفحے پر|इस पृष्ठ पर|本页内容
Back to all guides & tools|العودة إلى جميع الأدلة والأدوات|Ко всем руководствам и инструментам|Retour à tous les guides et outils|تمام رہنما اور ٹولز پر واپس جائیں|सभी मार्गदर्शिकाओं और टूल पर लौटें|返回全部指南和工具
UKR editorial guide · Reviewed 2 October 2026|دليل تحريري من UKR · تمت المراجعة في 2 أكتوبر 2026|Руководство UKR · Проверено 2 октября 2026 г.|Guide éditorial UKR · Revu le 2 octobre 2026|UKR کا مرتب کردہ رہنما · جائزہ: 2 اکتوبر 2026|UKR संपादकीय मार्गदर्शिका · समीक्षा: 2 अक्टूबर 2026|UKR编辑指南 · 审核日期：2026年10月2日
Container sizes: 20 ft, 40 ft, 40 HC and 45 ft|أحجام الحاويات: 20 و40 و40 HC و45 قدمًا|Размеры контейнеров: 20 футов, 40 футов, 40 HC и 45 футов|Dimensions des conteneurs : 20 pieds, 40 pieds, 40 HC et 45 pieds|کنٹینر کے سائز: 20 فٹ، 40 فٹ، 40 HC اور 45 فٹ|कंटेनर आकार: 20 फ़ुट, 40 फ़ुट, 40 HC और 45 फ़ुट|集装箱尺寸：20尺、40尺、40尺高箱和45尺
Compare representative inside dimensions, door openings and volume before choosing equipment.|قارن الأبعاد الداخلية وفتحات الأبواب والسعة النموذجية قبل اختيار الحاوية.|Сравните типовые внутренние размеры, дверные проёмы и объём перед выбором контейнера.|Comparez les dimensions intérieures indicatives, les portes et le volume avant de choisir l’équipement.|کنٹینر منتخب کرنے سے پہلے عمومی اندرونی ابعاد، دروازے اور حجم کا موازنہ کریں۔|कंटेनर चुनने से पहले सामान्य अंदरूनी आयाम, दरवाज़े और आयतन की तुलना करें।|选择箱型前，比较参考内尺寸、门框尺寸及容积。
Compare the four sizes|قارن الأحجام الأربعة|Сравните четыре размера|Comparez les quatre formats|چار سائزوں کا موازنہ کریں|चारों आकारों की तुलना करें|比较四种箱型
Before you book|قبل الحجز|Перед бронированием|Avant de réserver|بکنگ سے پہلے|बुकिंग से पहले|预订前须知
Sources|المصادر|Источники|Sources|ذرائع|स्रोत|资料来源
Container measurement comparison|مقارنة أبعاد الحاويات|Сравнение размеров контейнеров|Comparaison des dimensions des conteneurs|کنٹینر کے ابعاد کا موازنہ|कंटेनर आयामों की तुलना|集装箱尺寸对照
Equipment|نوع الحاوية|Тип контейнера|Équipement|کنٹینر کی قسم|कंटेनर प्रकार|箱型
Inside L × W × H|داخلي: الطول × العرض × الارتفاع|Внутри: Д × Ш × В|Intérieur L × l × H|اندرونی لمبائی × چوڑائی × اونچائی|अंदरूनी लंबाई × चौड़ाई × ऊँचाई|内部长×宽×高
Door W × H|الباب: العرض × الارتفاع|Дверь: Ш × В|Porte l × H|دروازے کی چوڑائی × اونچائی|दरवाज़े की चौड़ाई × ऊँचाई|门框宽×高
Volume|الحجم|Объём|Volume|حجم|आयतन|体积
20 ft GP|20 قدمًا GP|20 футов GP|20 pieds GP|20 فٹ GP|20 फ़ुट GP|20尺普箱
40 ft GP|40 قدمًا GP|40 футов GP|40 pieds GP|40 فٹ GP|40 फ़ुट GP|40尺普箱
40 ft HC|40 قدمًا HC|40 футов HC|40 pieds HC|40 فٹ HC|40 फ़ुट HC|40尺高箱
45 ft HC|45 قدمًا HC|45 футов HC|45 pieds HC|45 فٹ HC|45 फ़ुट HC|45尺高箱
GP means general purpose; HC means high cube. The figures below are representative measurements from Hapag-Lloyd, not guaranteed dimensions for every container. Measurements are metres; volume is cubic metres (CBM).|GP تعني حاوية للأغراض العامة، وHC تعني حاوية مرتفعة. الأرقام أدناه قياسات نموذجية من Hapag-Lloyd، وليست أبعادًا مضمونة لكل حاوية. الأبعاد بالمتر، والحجم بالمتر المكعب (CBM).|GP означает стандартный контейнер, HC: контейнер увеличенной высоты. Ниже приведены типовые размеры Hapag-Lloyd, а не гарантированные размеры каждого контейнера. Размеры указаны в метрах, объём: в кубических метрах (CBM).|GP signifie usage général ; HC désigne un conteneur surélevé. Les chiffres ci-dessous sont des mesures indicatives de Hapag-Lloyd, non des dimensions garanties pour chaque conteneur. Les dimensions sont en mètres et le volume en mètres cubes (CBM).|GP سے مراد عام استعمال اور HC سے مراد زیادہ اونچائی والا کنٹینر ہے۔ نیچے دیے گئے اعداد Hapag-Lloyd کی عمومی پیمائشیں ہیں، ہر کنٹینر کے لیے ضمانت شدہ ابعاد نہیں۔ ابعاد میٹر اور حجم مکعب میٹر (CBM) میں ہیں۔|GP का अर्थ सामान्य उपयोग और HC का अर्थ अधिक ऊँचाई वाला कंटेनर है। नीचे दिए आँकड़े Hapag-Lloyd के सामान्य माप हैं, हर कंटेनर के लिए गारंटीकृत आयाम नहीं। आयाम मीटर में और आयतन घन मीटर (CBM) में हैं।|GP指普通箱，HC指高箱。以下为Hapag-Lloyd提供的参考尺寸，不保证每个集装箱均具有相同尺寸。尺寸单位为米，容积单位为立方米（CBM）。
Inside dimensions are not outside dimensions. Published volume is not a promise that the same volume of cartons will fit. Packaging, stackability, door access, weight distribution and payload limits must also be checked.|الأبعاد الداخلية تختلف عن الخارجية. السعة المنشورة لا تعني ضمان استيعاب الحجم نفسه من الكراتين. يجب أيضًا التحقق من التغليف وقابلية التكديس وفتحة الباب وتوزيع الوزن وحدود الحمولة.|Внутренние размеры отличаются от внешних. Указанный объём не гарантирует размещения такого же объёма коробок. Учитывайте упаковку, возможность штабелирования, дверной проём, распределение веса и допустимую нагрузку.|Les dimensions intérieures diffèrent des dimensions extérieures. Le volume publié ne garantit pas que le même volume de cartons pourra entrer. Il faut aussi vérifier l’emballage, l’empilage, l’accès par la porte, la répartition du poids et la charge utile.|اندرونی ابعاد بیرونی ابعاد سے مختلف ہیں۔ شائع شدہ حجم اتنے ہی حجم کے کارٹن سما جانے کی ضمانت نہیں۔ پیکنگ، تہہ بندی، دروازے سے گزرنے، وزن کی تقسیم اور وزن اٹھانے کی حد بھی جانچیں۔|अंदरूनी और बाहरी आयाम अलग होते हैं। प्रकाशित आयतन उतने ही आयतन के कार्टन समाने की गारंटी नहीं है। पैकिंग, स्टैकिंग, दरवाज़े से प्रवेश, वजन वितरण और भार सीमा भी जाँचें।|内尺寸不等于外尺寸。公布的容积不代表一定能装入相同体积的纸箱，还须核查包装、堆叠性、门框通行空间、重量分布及载重限制。
Measure the outer packed cargo, including pallets and protection. Tell UKR about heavy items, non-stackable cargo and anything requiring special handling. Check the allocated container and its safety plate before loading. A 45 ft option depends on the selected carrier, route and equipment availability.|قِس الأبعاد الخارجية للشحنة المغلّفة، بما فيها الطبليات ومواد الحماية. أبلغ UKR بالأصناف الثقيلة أو غير القابلة للتكديس أو التي تحتاج مناولة خاصة. افحص الحاوية المخصصة ولوحة سلامتها قبل التحميل. توفر حاوية 45 قدمًا يعتمد على الناقل والمسار وتوفر المعدات.|Измерьте груз в упаковке, включая поддоны и защитные материалы. Сообщите UKR о тяжёлых, нештабелируемых грузах и особых требованиях. Перед погрузкой проверьте выделенный контейнер и его табличку безопасности. Контейнер 45 футов доступен в зависимости от перевозчика, маршрута и наличия оборудования.|Mesurez le fret emballé, palettes et protections comprises. Signalez à UKR les objets lourds, non empilables ou nécessitant une manutention spéciale. Vérifiez le conteneur attribué et sa plaque de sécurité avant le chargement. L’option 45 pieds dépend du transporteur, de l’itinéraire et de la disponibilité.|پیک شدہ سامان کے بیرونی ابعاد ناپیں، پیلیٹ اور حفاظتی مواد سمیت۔ بھاری، ایک دوسرے پر نہ رکھے جانے والے یا خصوصی ہینڈلنگ والے سامان کے بارے میں UKR کو بتائیں۔ لوڈنگ سے پہلے مختص کنٹینر اور اس کی حفاظتی پلیٹ دیکھیں۔ 45 فٹ کنٹینر کی دستیابی کیریئر، راستے اور آلات کی دستیابی پر منحصر ہے۔|पैलेट और सुरक्षा सामग्री सहित पैक किए गए माल के बाहरी आयाम मापें। भारी, स्टैक न किए जा सकने वाले या विशेष संभाल वाले माल की जानकारी UKR को दें। लोड करने से पहले आवंटित कंटेनर और उसकी सुरक्षा प्लेट जाँचें। 45 फ़ुट विकल्प वाहक, मार्ग और उपलब्धता पर निर्भर करता है।|测量包装后的外部尺寸，包括托盘和防护材料。请告知UKR重货、不可堆叠货物及特殊装卸要求。装货前检查指定集装箱及其安全铭牌。45尺箱能否提供取决于承运人、路线及设备供应。
The carrier states that specifications vary by manufacturer. The 40 HC width above follows its written inside-dimension table.|يوضح الناقل أن المواصفات تختلف باختلاف المصنّع. عرض حاوية 40 HC أعلاه مأخوذ من جدول أبعاده الداخلية المكتوب.|Перевозчик указывает, что характеристики зависят от производителя. Ширина 40 HC выше взята из его таблицы внутренних размеров.|Le transporteur précise que les caractéristiques varient selon le fabricant. La largeur du 40 HC ci-dessus reprend son tableau écrit des dimensions intérieures.|کیریئر کے مطابق تفصیلات بنانے والے کے لحاظ سے مختلف ہوتی ہیں۔ اوپر 40 HC کی چوڑائی اس کے تحریری اندرونی ابعاد کے جدول سے لی گئی ہے۔|वाहक के अनुसार विनिर्देश निर्माता के अनुसार बदलते हैं। ऊपर 40 HC की चौड़ाई उसकी लिखित अंदरूनी आयाम तालिका से ली गई है।|承运人说明，规格因制造商而异。上方40尺高箱宽度采用其书面内尺寸表的数据。
Find FCL shipping options|ابحث عن شحن الحاويات الكاملة|Найти варианты FCL|Rechercher des options FCL|FCL شپنگ کے آپشنز تلاش کریں|FCL शिपिंग विकल्प खोजें|查找整箱运输方案
Hapag-Lloyd: 20 ft standard specifications|Hapag-Lloyd: مواصفات الحاوية القياسية 20 قدمًا|Hapag-Lloyd: характеристики стандартного 20-футового контейнера|Hapag-Lloyd : caractéristiques du 20 pieds standard|Hapag-Lloyd: 20 فٹ معیاری کنٹینر کی تفصیلات|Hapag-Lloyd: 20 फ़ुट मानक कंटेनर के विनिर्देश|Hapag-Lloyd：20尺普箱规格
Hapag-Lloyd: 40 ft standard specifications|Hapag-Lloyd: مواصفات الحاوية القياسية 40 قدمًا|Hapag-Lloyd: характеристики стандартного 40-футового контейнера|Hapag-Lloyd : caractéristiques du 40 pieds standard|Hapag-Lloyd: 40 فٹ معیاری کنٹینر کی تفصیلات|Hapag-Lloyd: 40 फ़ुट मानक कंटेनर के विनिर्देश|Hapag-Lloyd：40尺普箱规格
Hapag-Lloyd: 40 ft high cube specifications|Hapag-Lloyd: مواصفات الحاوية المرتفعة 40 قدمًا|Hapag-Lloyd: характеристики 40-футового High Cube|Hapag-Lloyd : caractéristiques du 40 pieds High Cube|Hapag-Lloyd: 40 فٹ ہائی کیوب کی تفصیلات|Hapag-Lloyd: 40 फ़ुट हाई क्यूब के विनिर्देश|Hapag-Lloyd：40尺高箱规格
Hapag-Lloyd: 45 ft high cube specifications|Hapag-Lloyd: مواصفات الحاوية المرتفعة 45 قدمًا|Hapag-Lloyd: характеристики 45-футового High Cube|Hapag-Lloyd : caractéristiques du 45 pieds High Cube|Hapag-Lloyd: 45 فٹ ہائی کیوب کی تفصیلات|Hapag-Lloyd: 45 फ़ुट हाई क्यूब के विनिर्देश|Hapag-Lloyd：45尺高箱规格
What is CBM in shipping?|ما معنى CBM في الشحن؟|Что такое CBM в перевозках?|Que signifie CBM en transport ?|شپنگ میں CBM کیا ہے؟|शिपिंग में CBM क्या है?|货运中的CBM是什么？
A simple explanation of cubic metres and the measurements needed for a quote.|شرح مبسط للمتر المكعب والقياسات المطلوبة لعرض السعر.|Простое объяснение кубических метров и измерений для расчёта.|Une explication simple du mètre cube et des mesures nécessaires à un devis.|مکعب میٹر اور کوٹیشن کے لیے ضروری پیمائشوں کی آسان وضاحت۔|घन मीटर और कोटेशन के लिए आवश्यक मापों की सरल व्याख्या।|简明解释立方米及报价所需的尺寸数据。
What CBM means|ماذا تعني CBM؟|Что означает CBM|La signification de CBM|CBM کا مطلب|CBM का अर्थ|CBM的含义
A worked example|مثال عملي|Пример расчёта|Un exemple de calcul|ایک حسابی مثال|गणना का उदाहरण|计算示例
What CBM does not tell you|ما الذي لا توضحه CBM؟|Чего CBM не показывает|Ce que le CBM ne dit pas|CBM کیا نہیں بتاتا|CBM क्या नहीं बताता|CBM无法说明什么
CBM means cubic metre, a unit of volume. For rectangular packed cargo, multiply the outside length, width and height in metres. Multiply again by the number of identical packages.|CBM تعني المتر المكعب، وهو وحدة حجم. للشحنة المغلّفة المستطيلة، اضرب الطول الخارجي في العرض والارتفاع بالأمتار، ثم اضرب الناتج في عدد الطرود المتطابقة.|CBM означает кубический метр, единицу объёма. Для прямоугольного груза в упаковке перемножьте внешнюю длину, ширину и высоту в метрах, затем умножьте на число одинаковых мест.|CBM signifie mètre cube, une unité de volume. Pour du fret emballé rectangulaire, multipliez longueur, largeur et hauteur extérieures en mètres, puis le nombre de colis identiques.|CBM مکعب میٹر، یعنی حجم کی اکائی ہے۔ مستطیل پیک شدہ سامان کی بیرونی لمبائی، چوڑائی اور اونچائی کو میٹر میں ضرب دیں، پھر ایک جیسے پیکجوں کی تعداد سے ضرب دیں۔|CBM का अर्थ घन मीटर है, जो आयतन की इकाई है। आयताकार पैक किए गए माल की बाहरी लंबाई, चौड़ाई और ऊँचाई को मीटर में गुणा करें, फिर समान पैकेजों की संख्या से गुणा करें।|CBM是立方米，即体积单位。对于长方体包装货物，将以米为单位的外部长、宽、高相乘，再乘以相同包装的件数。
CBM = length (m) × width (m) × height (m) × quantity.|الحجم = الطول (م) × العرض (م) × الارتفاع (م) × العدد.|CBM = длина (м) × ширина (м) × высота (м) × количество.|CBM = longueur (m) × largeur (m) × hauteur (m) × quantité.|CBM = لمبائی (میٹر) × چوڑائی (میٹر) × اونچائی (میٹر) × تعداد۔|CBM = लंबाई (मी.) × चौड़ाई (मी.) × ऊँचाई (मी.) × संख्या।|CBM＝长（米）×宽（米）×高（米）×件数。
One carton measuring 60 × 40 × 50 cm occupies 0.60 × 0.40 × 0.50 = 0.12 CBM. Twenty identical cartons total 2.40 CBM. For different sizes, calculate each size separately and add the totals.|كرتونة بأبعاد 60 × 40 × 50 سم تشغل 0.60 × 0.40 × 0.50 = 0.12 م³. عشرون كرتونة متطابقة مجموعها 2.40 م³. للأحجام المختلفة، احسب كل حجم على حدة ثم اجمع النتائج.|Коробка 60 × 40 × 50 см занимает 0,60 × 0,40 × 0,50 = 0,12 м³. Двадцать одинаковых коробок составляют 2,40 м³. Разные размеры считайте отдельно, затем сложите результаты.|Un carton de 60 × 40 × 50 cm occupe 0,60 × 0,40 × 0,50 = 0,12 m³. Vingt cartons identiques totalisent 2,40 m³. Pour des dimensions différentes, calculez chaque format séparément, puis additionnez.|60 × 40 × 50 سینٹی میٹر کا ایک کارٹن 0.60 × 0.40 × 0.50 = 0.12 CBM جگہ لیتا ہے۔ بیس یکساں کارٹنوں کا کل حجم 2.40 CBM ہے۔ مختلف سائز الگ حساب کر کے جمع کریں۔|60 × 40 × 50 सेमी का एक कार्टन 0.60 × 0.40 × 0.50 = 0.12 CBM जगह लेता है। ऐसे बीस कार्टन कुल 2.40 CBM होते हैं। अलग आकारों की अलग गणना करके कुल जोड़ें।|一个60×40×50厘米的纸箱体积为0.60×0.40×0.50＝0.12立方米。20个相同纸箱共2.40立方米。不同尺寸应分别计算后相加。
CBM is volume, not weight, an all-in price or proof that a load will fit. The applicable freight tariff may include minimum charges and weight rules. Keep the gross packed weight ready, and tell UKR about any non-stackable or irregular cargo.|CBM هي حجم، وليست وزنًا أو سعرًا شاملًا أو دليلًا على ملاءمة الحمولة. قد تشمل تعرفة الشحن حدًا أدنى للرسوم وقواعد للوزن. جهّز الوزن الإجمالي للشحنة المغلّفة، وأبلغ UKR بأي بضاعة غير قابلة للتكديس أو غير منتظمة الشكل.|CBM: это объём, а не вес, полная цена или гарантия размещения груза. Тариф может предусматривать минимальную оплату и весовые правила. Подготовьте вес брутто в упаковке и сообщите UKR о нештабелируемом грузе или нестандартной форме.|Le CBM indique un volume, pas un poids, un prix tout compris ni une garantie de chargement. Le tarif peut prévoir un minimum de facturation et des règles de poids. Préparez le poids brut emballé et signalez à UKR tout fret non empilable ou irrégulier.|CBM حجم ہے، وزن، مکمل قیمت یا سامان سما جانے کا ثبوت نہیں۔ متعلقہ نرخ میں کم از کم چارج اور وزن کے اصول شامل ہو سکتے ہیں۔ پیک شدہ مجموعی وزن تیار رکھیں اور ناقابلِ تہہ بندی یا بے قاعدہ سامان کی اطلاع UKR کو دیں۔|CBM आयतन है, वजन, कुल कीमत या माल समाने का प्रमाण नहीं। लागू दर में न्यूनतम शुल्क और वजन संबंधी नियम हो सकते हैं। पैक किए माल का सकल वजन तैयार रखें और गैर-स्टैकेबल या अनियमित माल की जानकारी UKR को दें।|CBM表示体积，不是重量、全包价格，也不能保证货物能装入。运价可能涉及最低收费及重量规则。请备好包装后的毛重，并告知UKR不可堆叠或异形货物。
Open the CBM calculator|افتح حاسبة الحجم|Открыть калькулятор CBM|Ouvrir le calculateur CBM|CBM کیلکولیٹر کھولیں|CBM कैलकुलेटर खोलें|打开CBM计算器
How to calculate CBM correctly|كيف تحسب CBM بشكل صحيح؟|Как правильно рассчитать CBM|Comment calculer correctement le CBM|CBM درست کیسے حساب کریں|CBM की सही गणना कैसे करें|如何正确计算CBM
Measure packed cargo, choose the right unit and add mixed carton sizes without double-counting.|قِس الشحنة بعد التغليف، واختر الوحدة المناسبة، واجمع أحجام الكراتين المختلفة دون تكرار الحساب.|Измерьте упакованный груз, выберите единицы и сложите объёмы разных коробок без двойного учёта.|Mesurez le fret emballé, choisissez l’unité et additionnez les formats sans double comptage.|پیک شدہ سامان ناپیں، درست اکائی منتخب کریں اور مختلف کارٹن سائز دو بار شمار کیے بغیر جمع کریں۔|पैक किए माल को मापें, सही इकाई चुनें और अलग कार्टन आकारों को दोहरा गिने बिना जोड़ें।|测量包装后的货物，选择正确单位，汇总不同箱规并避免重复计算。
Measure the packed cargo|قِس الشحنة بعد التغليف|Измерьте упакованный груз|Mesurez le fret emballé|پیک شدہ سامان ناپیں|पैक किए माल को मापें|测量包装后的货物
Choose your units|اختر وحدات القياس|Выберите единицы измерения|Choisissez les unités|اکائیاں منتخب کریں|इकाइयाँ चुनें|选择计量单位
Add different package sizes|أضف أحجام الطرود المختلفة|Добавьте разные размеры мест|Ajoutez les différents formats|مختلف پیکج سائز شامل کریں|अलग पैकेज आकार जोड़ें|添加不同包装尺寸
Use outer packed length, width and height. Include the pallet and protective packaging. For a rectangular envelope around irregular cargo, use the largest outside dimensions and ask UKR to review the shape and handling needs.|استخدم الطول والعرض والارتفاع الخارجي بعد التغليف، بما فيه الطبليات ومواد الحماية. للبضائع غير المنتظمة، استخدم أكبر أبعاد خارجية لصندوق افتراضي يحيط بها واطلب من UKR مراجعة الشكل ومتطلبات المناولة.|Используйте внешние размеры груза в упаковке, включая поддон и защиту. Для условного прямоугольного объёма вокруг нестандартного груза берите наибольшие габариты и попросите UKR оценить форму и требования к обработке.|Utilisez les dimensions extérieures emballées, palette et protections comprises. Pour l’enveloppe rectangulaire d’un fret irrégulier, retenez les plus grandes dimensions et demandez à UKR d’examiner la forme et les besoins de manutention.|پیک شدہ بیرونی لمبائی، چوڑائی اور اونچائی استعمال کریں، پیلیٹ اور حفاظتی پیکنگ سمیت۔ بے قاعدہ سامان کے گرد مستطیل جگہ ناپنے کے لیے سب سے بڑے بیرونی ابعاد لیں اور شکل و ہینڈلنگ کی ضرورت UKR سے جانچوائیں۔|पैलेट और सुरक्षा पैकिंग सहित बाहरी लंबाई, चौड़ाई और ऊँचाई लें। अनियमित माल के आयताकार घेराव के लिए सबसे बड़े बाहरी आयाम लें और आकार तथा संभाल की ज़रूरत UKR से जँचवाएँ।|使用包装后的外部长、宽、高，包括托盘与防护包装。异形货物按包围它的长方体最大外尺寸计算，并请UKR审核形状及装卸要求。
Centimetres:|بالسنتيمتر:|Сантиметры:|Centimètres :|سینٹی میٹر:|सेंटीमीटर:|厘米：
Metres:|بالأمتار:|Метры:|Mètres :|میٹر:|मीटर:|米：
Millimetres:|بالمليمتر:|Миллиметры:|Millimètres :|ملی میٹر:|मिलीमीटर:|毫米：
L × W × H × quantity ÷ 1,000,000.|الطول × العرض × الارتفاع × العدد ÷ 1,000,000.|Д × Ш × В × количество ÷ 1 000 000.|L × l × H × quantité ÷ 1 000 000.|لمبائی × چوڑائی × اونچائی × تعداد ÷ 1,000,000۔|लंबाई × चौड़ाई × ऊँचाई × संख्या ÷ 1,000,000।|长×宽×高×件数÷1,000,000。
L × W × H × quantity.|الطول × العرض × الارتفاع × العدد.|Д × Ш × В × количество.|L × l × H × quantité.|لمبائی × چوڑائی × اونچائی × تعداد۔|लंबाई × चौड़ाई × ऊँचाई × संख्या।|长×宽×高×件数。
L × W × H × quantity ÷ 1,000,000,000.|الطول × العرض × الارتفاع × العدد ÷ 1,000,000,000.|Д × Ш × В × количество ÷ 1 000 000 000.|L × l × H × quantité ÷ 1 000 000 000.|لمبائی × چوڑائی × اونچائی × تعداد ÷ 1,000,000,000۔|लंबाई × चौड़ाई × ऊँचाई × संख्या ÷ 1,000,000,000।|长×宽×高×件数÷1,000,000,000。
Use the same unit for all three dimensions on each line. Keep fractional values; do not round each carton up to a whole cubic metre.|استخدم الوحدة نفسها للأبعاد الثلاثة في كل سطر. احتفظ بالكسور، ولا تقرّب حجم كل كرتونة إلى متر مكعب كامل.|Для трёх размеров в строке используйте одну единицу. Сохраняйте дробные значения: не округляйте каждую коробку до целого кубометра.|Utilisez la même unité pour les trois dimensions de chaque ligne. Conservez les décimales ; n’arrondissez pas chaque carton au mètre cube entier supérieur.|ہر سطر کے تینوں ابعاد میں ایک ہی اکائی استعمال کریں۔ اعشاری قدریں برقرار رکھیں، ہر کارٹن کو پورا مکعب میٹر نہ بنائیں۔|हर पंक्ति के तीनों आयामों में एक ही इकाई लें। दशमलव मान बनाए रखें; हर कार्टन को पूरे घन मीटर तक ऊपर न गोल करें।|每一行的三个尺寸须使用相同单位。保留小数，不要将每个纸箱向上取整到一个立方米。
Add one calculator line for each package size. Enter quantity only once. If you measure an entire loaded pallet, do not add the cartons on that pallet as additional cargo. The calculator totals your entered rectangular volumes; it does not assess how items can be stacked.|أضف سطرًا لكل حجم طرد وأدخل العدد مرة واحدة فقط. عند قياس طبلية محمّلة بالكامل، لا تضف الكراتين الموجودة عليها كشحنة إضافية. تجمع الحاسبة الأحجام المستطيلة التي تدخلها، ولا تقيّم طريقة تكديس البضائع.|Добавьте строку для каждого размера упаковки. Количество указывайте один раз. Измерив загруженный поддон целиком, не добавляйте его коробки повторно. Калькулятор суммирует прямоугольные объёмы, но не оценивает возможности штабелирования.|Ajoutez une ligne par format et saisissez la quantité une seule fois. Si vous mesurez une palette chargée entière, ne comptez pas ses cartons en plus. Le calculateur additionne les volumes rectangulaires saisis, sans évaluer l’empilage.|ہر پیکج سائز کے لیے الگ سطر شامل کریں۔ تعداد صرف ایک بار درج کریں۔ پورا لوڈ شدہ پیلیٹ ناپنے پر اس کے کارٹن دوبارہ شامل نہ کریں۔ کیلکولیٹر درج شدہ مستطیل حجم جمع کرتا ہے، تہہ بندی کا اندازہ نہیں لگاتا۔|हर पैकेज आकार के लिए एक पंक्ति जोड़ें। संख्या केवल एक बार भरें। पूरा भरा पैलेट मापने पर उसके कार्टन अतिरिक्त माल के रूप में न जोड़ें। कैलकुलेटर दर्ज आयताकार आयतन जोड़ता है, स्टैकिंग का आकलन नहीं करता।|每种包装尺寸添加一行，件数只填一次。如已测量整托货物，请勿再将托盘上的纸箱重复计入。计算器仅汇总输入的长方体体积，不评估货物堆叠方式。
Calculate your cargo|احسب حجم شحنتك|Рассчитать объём груза|Calculez votre fret|اپنے سامان کا حساب کریں|अपने माल की गणना करें|计算货物体积
Multi-package CBM calculator|حاسبة CBM لعدة أحجام طرود|Калькулятор CBM для разных упаковок|Calculateur CBM multicolis|مختلف پیکجوں کا CBM کیلکولیٹر|कई पैकेजों का CBM कैलकुलेटर|多包装CBM计算器
Add carton or pallet sizes. Calculate total volume and pass it to the Sea LCL search.|أضف أحجام الكراتين أو الطبليات، واحسب الحجم الإجمالي ثم استخدمه في بحث الشحن البحري الجزئي.|Добавьте размеры коробок или поддонов, рассчитайте общий объём и передайте его в поиск морского LCL.|Ajoutez les dimensions des cartons ou palettes, calculez le volume total et transférez-le à la recherche maritime LCL.|کارٹن یا پیلیٹ کے سائز شامل کریں، کل حجم حساب کر کے بحری LCL تلاش میں استعمال کریں۔|कार्टन या पैलेट के आकार जोड़ें, कुल आयतन गणना करके समुद्री LCL खोज में भेजें।|添加纸箱或托盘尺寸，计算总体积并带入海运拼箱查询。
Calculate your volume|احسب الحجم|Рассчитайте объём|Calculez votre volume|حجم کا حساب کریں|आयतन की गणना करें|计算体积
How to use the result|كيفية استخدام النتيجة|Как использовать результат|Comment utiliser le résultat|نتیجہ کیسے استعمال کریں|परिणाम का उपयोग कैसे करें|如何使用结果
Enter outer packed dimensions. Add a new line for each different size. Optional weight is the gross weight of one package on that line.|أدخل الأبعاد الخارجية بعد التغليف، وأضف سطرًا جديدًا لكل حجم مختلف. الوزن الاختياري هو الوزن الإجمالي لطرد واحد في ذلك السطر.|Введите внешние размеры упаковки, по строке на каждый размер. Необязательный вес: вес брутто одного места в этой строке.|Saisissez les dimensions extérieures emballées, une ligne par format. Le poids facultatif correspond au poids brut d’un seul colis sur cette ligne.|پیک شدہ بیرونی ابعاد درج کریں۔ ہر مختلف سائز کے لیے نئی سطر شامل کریں۔ اختیاری وزن اس سطر کے ایک پیکج کا مجموعی وزن ہے۔|पैक किए बाहरी आयाम भरें। हर अलग आकार के लिए नई पंक्ति जोड़ें। वैकल्पिक वजन उस पंक्ति के एक पैकेज का सकल वजन है।|输入包装后的外尺寸，每种不同尺寸单独添加一行。可选重量为该行单件包装的毛重。
+ Add another package size|+ إضافة حجم طرد آخر|+ Добавить размер упаковки|+ Ajouter un format de colis|+ مزید پیکج سائز شامل کریں|+ एक और पैकेज आकार जोड़ें|+ 添加另一种包装尺寸
Calculate CBM|احسب الحجم CBM|Рассчитать CBM|Calculer le CBM|CBM حساب کریں|CBM की गणना करें|计算CBM
Total packed volume|الحجم الإجمالي بعد التغليف|Общий объём в упаковке|Volume emballé total|کل پیک شدہ حجم|कुल पैक किया आयतन|包装总体积
Use volume in Sea LCL search|استخدم الحجم في بحث الشحن البحري الجزئي|Использовать объём в поиске LCL|Utiliser le volume pour la recherche LCL|حجم کو بحری LCL تلاش میں استعمال کریں|समुद्री LCL खोज में आयतन इस्तेमाल करें|将体积用于海运拼箱查询
This is a volume calculation, not a freight quotation or a container loading plan. Rates, minimum charges, chargeable weight and cargo acceptance depend on the selected service. Measurements are not sent or saved by this calculator.|هذا حساب حجم، وليس عرض سعر شحن أو خطة تحميل حاوية. تعتمد الأسعار والرسوم الدنيا والوزن المحتسب وقبول الشحنة على الخدمة المختارة. لا تُرسل الحاسبة القياسات ولا تحفظها.|Это расчёт объёма, а не тарифное предложение или план загрузки контейнера. Тарифы, минимальные сборы, расчётный вес и приём груза зависят от услуги. Калькулятор не отправляет и не сохраняет измерения.|Il s’agit d’un calcul de volume, pas d’un devis ni d’un plan de chargement. Tarifs, minima, poids taxable et acceptation dépendent du service choisi. Ce calculateur n’envoie ni ne conserve les mesures.|یہ حجم کا حساب ہے، فریٹ کوٹیشن یا کنٹینر لوڈنگ پلان نہیں۔ نرخ، کم از کم چارج، قابلِ چارج وزن اور سامان کی قبولیت منتخب سروس پر منحصر ہیں۔ یہ کیلکولیٹر پیمائشیں بھیجتا یا محفوظ نہیں کرتا۔|यह आयतन की गणना है, माल ढुलाई कोटेशन या कंटेनर लोडिंग योजना नहीं। दरें, न्यूनतम शुल्क, प्रभार्य वजन और माल की स्वीकृति चुनी सेवा पर निर्भर हैं। कैलकुलेटर माप भेजता या सहेजता नहीं है।|这只是体积计算，并非运价报价或装箱方案。运价、最低收费、计费重量及货物承运条件取决于所选服务。本计算器不会发送或保存尺寸数据。
Package size {n}|حجم الطرد {n}|Размер упаковки {n}|Format de colis {n}|پیکج سائز {n}|पैकेज आकार {n}|包装尺寸 {n}
Remove package size {n}|حذف حجم الطرد {n}|Удалить размер упаковки {n}|Supprimer le format {n}|پیکج سائز {n} ہٹائیں|पैकेज आकार {n} हटाएँ|删除包装尺寸 {n}
Remove|حذف|Удалить|Supprimer|ہٹائیں|हटाएँ|删除
Length|الطول|Длина|Longueur|لمبائی|लंबाई|长度
Width|العرض|Ширина|Largeur|چوڑائی|चौड़ाई|宽度
Height|الارتفاع|Высота|Hauteur|اونچائی|ऊँचाई|高度
Unit|الوحدة|Единица|Unité|اکائی|इकाई|单位
cm|سم|см|cm|سینٹی میٹر|सेमी|厘米
m|م|м|m|میٹر|मी.|米
mm|مم|мм|mm|ملی میٹر|मिमी|毫米
inches|بوصة|дюймы|pouces|انچ|इंच|英寸
Gross kg / package|الوزن الإجمالي كغ / طرد|Брутто, кг / место|Kg brut / colis|مجموعی کلوگرام / پیکج|सकल किग्रा / पैकेज|单件毛重／千克
Optional|اختياري|Необязательно|Facultatif|اختیاری|वैकल्पिक|选填
{n} packages|عدد الطرود: {n}|Грузовых мест: {n}|Nombre de colis : {n}|پیکجوں کی تعداد: {n}|पैकेजों की संख्या: {n}|件数：{n}
{n} kg total gross weight|الوزن الإجمالي: {n} كغ|Общий вес брутто: {n} кг|Poids brut total : {n} kg|کل مجموعی وزن: {n} کلوگرام|कुल सकल वजन: {n} किग्रा|总毛重：{n}千克
Gross weight not complete|بيانات الوزن الإجمالي غير مكتملة|Вес брутто указан не полностью|Poids brut incomplet|مجموعی وزن کی معلومات نامکمل ہیں|सकल वजन अधूरा है|毛重信息不完整
This volume or weight needs a manual UKR quote.|هذا الحجم أو الوزن يحتاج عرض سعر من فريق UKR.|Для этого объёма или веса нужен расчёт UKR.|Ce volume ou poids nécessite un devis UKR personnalisé.|اس حجم یا وزن کے لیے UKR سے الگ کوٹیشن درکار ہے۔|इस आयतन या वजन के लिए UKR का व्यक्तिगत कोटेशन चाहिए।|该体积或重量需要UKR人工报价。
`;
