// Search, safety disclosures and dynamic messages. Variables in braces are data, not translations.
export default String.raw`
Rates and bookings require UKR confirmation.|الأسعار والحجوزات تتطلب تأكيد UKR.|Тарифы и бронирования требуют подтверждения UKR.|Les tarifs et réservations nécessitent la confirmation d’UKR.|نرخوں اور بکنگ کے لیے UKR کی تصدیق ضروری ہے۔|दरों और बुकिंग के लिए UKR की पुष्टि आवश्यक है।|运价与预订须经UKR确认。
CONTACT UKR FOR BOOKING|تواصل مع UKR للحجز|БРОНИРОВАНИЕ ЧЕРЕЗ UKR|CONTACTEZ UKR POUR RÉSERVER|بکنگ کے لیے UKR سے رابطہ کریں|बुकिंग के लिए UKR से संपर्क करें|联系UKR办理预订
UKR SHIPPING · SEA · AIR · ROAD|UKR SHIPPING · بحر · جو · بر|UKR SHIPPING · МОРЕ · ВОЗДУХ · АВТО|UKR SHIPPING · MER · AIR · ROUTE|UKR SHIPPING · بحری · فضائی · زمینی|UKR SHIPPING · समुद्र · हवाई · सड़क|UKR SHIPPING · 海运 · 空运 · 陆运
Enable JavaScript to use the search and language selector. For a quote, email freight.dxb@ukrshipping.com.|فعّل JavaScript لاستخدام البحث واختيار اللغة. لطلب عرض سعر، راسل freight.dxb@ukrshipping.com.|Включите JavaScript для поиска и выбора языка. Для расчёта напишите на freight.dxb@ukrshipping.com.|Activez JavaScript pour la recherche et le choix de langue. Pour un devis : freight.dxb@ukrshipping.com.|تلاش اور زبان کے انتخاب کے لیے JavaScript فعال کریں۔ کوٹیشن کے لیے freight.dxb@ukrshipping.com پر ای میل کریں۔|खोज और भाषा चयन के लिए JavaScript सक्षम करें। कोटेशन के लिए freight.dxb@ukrshipping.com पर ईमेल करें।|请启用JavaScript以使用查询和语言选择。报价咨询：freight.dxb@ukrshipping.com。
Booking information.|معلومات الحجز.|Информация о бронировании.|Informations de réservation.|بکنگ کی معلومات۔|बुकिंग की जानकारी।|预订说明。
Displayed options are not confirmed offers. Contact UKR for current rates, schedules, space and payment terms.|الخيارات المعروضة ليست عروضًا مؤكدة. تواصل مع UKR للأسعار والمواعيد والمساحة وشروط الدفع الحالية.|Показанные варианты не являются подтверждёнными предложениями. Уточните в UKR тарифы, расписание, места и условия оплаты.|Les options affichées ne sont pas des offres confirmées. Contactez UKR pour les tarifs, horaires, places et conditions de paiement actuels.|دکھائے گئے اختیارات تصدیق شدہ آفرز نہیں ہیں۔ موجودہ نرخ، شیڈول، جگہ اور ادائیگی کی شرائط کے لیے UKR سے رابطہ کریں۔|दिखाए गए विकल्प पुष्ट प्रस्ताव नहीं हैं। वर्तमान दरों, समय-सारणी, जगह और भुगतान शर्तों के लिए UKR से संपर्क करें।|所示方案并非已确认报价。请联系UKR获取当前运价、船期、舱位及付款条件。
unconfirmed options|خيارات غير مؤكدة|неподтверждённых варианта|options non confirmées|غیر مصدقہ اختیارات|अपुष्ट विकल्प|个待确认方案
Review request|راجع الطلب|Проверить запрос|Vérifier la demande|درخواست کا جائزہ لیں|अनुरोध की समीक्षा करें|核对申请
Request rate|اطلب السعر|Запросить тариф|Demander un tarif|نرخ طلب کریں|दर माँगें|询价
Review your details before contacting UKR.|راجع تفاصيلك قبل التواصل مع UKR.|Проверьте данные перед обращением в UKR.|Vérifiez vos informations avant de contacter UKR.|UKR سے رابطے سے پہلے اپنی تفصیلات دیکھیں۔|UKR से संपर्क करने से पहले विवरण जाँचें।|联系UKR前请核对信息。
Information stays in this page. It is not sent or saved.|تبقى المعلومات في هذه الصفحة فقط، ولا تُرسل أو تُحفظ.|Данные остаются на этой странице, не отправляются и не сохраняются.|Les informations restent sur cette page, sans être envoyées ni enregistrées.|معلومات صرف اس صفحے پر رہتی ہیں، بھیجی یا محفوظ نہیں کی جاتیں۔|जानकारी इस पृष्ठ पर रहती है, भेजी या सहेजी नहीं जाती।|信息仅保留在当前页面，不会发送或保存。
03 Finish|03 الانتهاء|03 Завершение|03 Terminer|03 مکمل کریں|03 समाप्त करें|03 完成
File selection only; files are not uploaded. Maximum 5 files, 10 MB each.|اختيار ملفات فقط، دون رفعها. الحد الأقصى 5 ملفات، 10 ميغابايت لكل ملف.|Только выбор файлов, без загрузки. Не более 5 файлов, до 10 МБ каждый.|Sélection uniquement, sans téléversement. Maximum 5 fichiers de 10 Mo chacun.|صرف فائلوں کا انتخاب، اپ لوڈ نہیں ہوگا۔ زیادہ سے زیادہ 5 فائلیں، ہر ایک 10 MB تک۔|केवल फ़ाइल चयन, अपलोड नहीं होगा। अधिकतम 5 फ़ाइलें, प्रत्येक 10 MB तक।|仅选择文件，不会上传。最多5个文件，每个不超过10MB。
Cancellation, payment on arrival, online payment and instalments are available only when stated in a confirmed UKR offer.|الإلغاء والدفع عند الوصول والدفع الإلكتروني والتقسيط متاحة فقط إذا نصّ عليها عرض UKR المؤكد.|Отмена, оплата по прибытии, онлайн-оплата и рассрочка доступны только при их указании в подтверждённом предложении UKR.|Annulation, paiement à l’arrivée, paiement en ligne et échelonnement ne s’appliquent que s’ils figurent dans une offre UKR confirmée.|منسوخی، آمد پر ادائیگی، آن لائن ادائیگی اور اقساط صرف UKR کی تصدیق شدہ آفر میں درج ہونے پر دستیاب ہیں۔|रद्दीकरण, आगमन पर भुगतान, ऑनलाइन भुगतान और किस्तें केवल पुष्ट UKR प्रस्ताव में उल्लिखित होने पर उपलब्ध हैं।|取消、到付、在线支付及分期付款仅在UKR确认的报价明确列出时适用。
I understand this form does not submit a booking. UKR must confirm the rate, space and terms.|أفهم أن هذا النموذج لا يرسل حجزًا. يجب أن تؤكد UKR السعر والمساحة والشروط.|Я понимаю, что эта форма не отправляет бронирование. UKR должна подтвердить тариф, место и условия.|Je comprends que ce formulaire n’envoie pas de réservation. UKR doit confirmer le tarif, la place et les conditions.|میں سمجھتا ہوں کہ یہ فارم بکنگ جمع نہیں کرتا۔ UKR کو نرخ، جگہ اور شرائط کی تصدیق کرنی ہوگی۔|मैं समझता/समझती हूँ कि यह फ़ॉर्म बुकिंग जमा नहीं करता। UKR को दर, जगह और शर्तों की पुष्टि करनी होगी।|我知悉此表单不会提交预订。运价、舱位及条款须经UKR确认。
Finish review|إنهاء المراجعة|Завершить проверку|Terminer la vérification|جائزہ مکمل کریں|समीक्षा समाप्त करें|完成核对
Your review is complete|اكتملت مراجعتك|Проверка завершена|Votre vérification est terminée|آپ کا جائزہ مکمل ہے|आपकी समीक्षा पूरी है|信息核对完成
Review complete|اكتملت المراجعة|Проверка завершена|Vérification terminée|جائزہ مکمل|समीक्षा पूरी|核对完成
No booking has been submitted, no email sent and no payment taken. Contact UKR to place your booking.|لم يُرسل حجز أو بريد إلكتروني ولم يُحصّل أي مبلغ. تواصل مع UKR لإتمام حجزك.|Бронирование не отправлено, письмо не отправлено, оплата не списана. Для оформления свяжитесь с UKR.|Aucune réservation ni aucun e-mail n’ont été envoyés et aucun paiement n’a été prélevé. Contactez UKR pour réserver.|نہ بکنگ جمع ہوئی، نہ ای میل بھیجا گیا، نہ ادائیگی لی گئی۔ بکنگ کے لیے UKR سے رابطہ کریں۔|कोई बुकिंग जमा नहीं हुई, ईमेल नहीं भेजा गया और भुगतान नहीं लिया गया। बुकिंग के लिए UKR से संपर्क करें।|尚未提交预订、发送邮件或收取款项。请联系UKR办理预订。
Send your booking request to UKR by phone or email.|أرسل طلب حجزك إلى UKR عبر الهاتف أو البريد الإلكتروني.|Передайте запрос UKR по телефону или электронной почте.|Transmettez votre demande à UKR par téléphone ou e-mail.|اپنی بکنگ کی درخواست فون یا ای میل کے ذریعے UKR کو دیں۔|अपना बुकिंग अनुरोध फ़ोन या ईमेल से UKR को भेजें।|请通过电话或邮件向UKR发送预订申请。
Online tracking is unavailable. No shipment status has been retrieved. Contact UKR for an update.|التتبّع الإلكتروني غير متاح. لم يتم جلب حالة الشحنة. تواصل مع UKR لمعرفة آخر المستجدات.|Онлайн-отслеживание недоступно. Статус груза не получен. Уточните его у UKR.|Le suivi en ligne est indisponible. Aucun statut n’a été récupéré. Contactez UKR pour une mise à jour.|آن لائن ٹریکنگ دستیاب نہیں۔ شپمنٹ کی حالت حاصل نہیں کی گئی۔ تازہ معلومات کے لیے UKR سے رابطہ کریں۔|ऑनलाइन ट्रैकिंग उपलब्ध नहीं है। शिपमेंट की स्थिति प्राप्त नहीं की गई। अपडेट के लिए UKR से संपर्क करें।|在线追踪暂不可用，尚未获取货物状态。请联系UKR查询进度。
For an official quotation, send your company details and shipment documents to UKR. Validity is 48 hours, subject to final UKR approval. Online quotation generation is unavailable.|للحصول على عرض رسمي، أرسل بيانات شركتك ومستندات الشحنة إلى UKR. الصلاحية 48 ساعة، رهن موافقة UKR النهائية. إصدار العروض إلكترونيًا غير متاح.|Для официального предложения отправьте UKR данные компании и документы на груз. Срок действия: 48 часов, при окончательном одобрении UKR. Онлайн-формирование предложения недоступно.|Pour un devis officiel, envoyez les coordonnées de l’entreprise et les documents du fret à UKR. Validité : 48 heures, sous réserve d’approbation finale d’UKR. La génération en ligne est indisponible.|باضابطہ کوٹیشن کے لیے کمپنی کی تفصیلات اور شپمنٹ کی دستاویزات UKR کو بھیجیں۔ مدت 48 گھنٹے، UKR کی حتمی منظوری سے مشروط ہے۔ آن لائن کوٹیشن بنانا دستیاب نہیں۔|आधिकारिक कोटेशन के लिए कंपनी का विवरण और शिपमेंट दस्तावेज़ UKR को भेजें। वैधता 48 घंटे है, UKR की अंतिम मंज़ूरी के अधीन। ऑनलाइन कोटेशन बनाना उपलब्ध नहीं है।|请向UKR发送公司资料及货运文件以获取正式报价。有效期为48小时，须经UKR最终批准。目前不提供在线报价生成。
A PDF estimate requires an approved UKR rate. Contact our team to obtain the estimate; no price document has been generated.|يتطلب تقدير PDF سعرًا معتمدًا من UKR. تواصل مع فريقنا للحصول عليه، فلم يتم إصدار مستند سعر.|Для расчёта в PDF нужен одобренный тариф UKR. Обратитесь к команде: ценовой документ не сформирован.|Une estimation PDF nécessite un tarif approuvé par UKR. Contactez notre équipe ; aucun document tarifaire n’a été généré.|PDF تخمینے کے لیے UKR کا منظور شدہ نرخ ضروری ہے۔ تخمینہ حاصل کرنے کے لیے ٹیم سے رابطہ کریں؛ قیمت کا کوئی دستاویز نہیں بنایا گیا۔|PDF अनुमान के लिए UKR की अनुमोदित दर चाहिए। अनुमान के लिए टीम से संपर्क करें; कोई मूल्य दस्तावेज़ नहीं बनाया गया है।|PDF估价须有UKR审核的运价。请联系团队获取估价，目前未生成价格文件。
Please contact our team for information about this service.|يرجى التواصل مع فريقنا لمعلومات عن هذه الخدمة.|Обратитесь к нашей команде за информацией об услуге.|Contactez notre équipe pour des informations sur ce service.|اس سروس کی معلومات کے لیے ہماری ٹیم سے رابطہ کریں۔|इस सेवा की जानकारी के लिए हमारी टीम से संपर्क करें।|请联系团队了解该服务。
Contact UKR for assistance.|تواصل مع UKR للمساعدة.|Обратитесь в UKR за помощью.|Contactez UKR pour obtenir de l’aide.|مدد کے لیے UKR سے رابطہ کریں۔|सहायता के लिए UKR से संपर्क करें।|请联系UKR获取帮助。
Back to shipping search|العودة إلى بحث الشحن|К поиску перевозки|Retour à la recherche de transport|شپنگ کی تلاش پر واپس جائیں|शिपिंग खोज पर लौटें|返回货运查询
Online account access is unavailable. Please contact UKR for assistance.|الدخول الإلكتروني إلى الحساب غير متاح. يرجى التواصل مع UKR للمساعدة.|Вход в аккаунт недоступен. Обратитесь за помощью в UKR.|L’accès au compte est indisponible. Contactez UKR pour obtenir de l’aide.|آن لائن اکاؤنٹ رسائی دستیاب نہیں۔ مدد کے لیے UKR سے رابطہ کریں۔|ऑनलाइन खाते का उपयोग उपलब्ध नहीं है। सहायता के लिए UKR से संपर्क करें।|在线账户暂不可用，请联系UKR获取帮助。
Customer dashboard|لوحة العميل|Кабинет клиента|Espace client|صارف کا ڈیش بورڈ|ग्राहक डैशबोर्ड|客户中心
Staff dashboard|لوحة الموظفين|Кабинет сотрудника|Espace du personnel|عملے کا ڈیش بورڈ|कर्मचारी डैशबोर्ड|员工工作台
Privacy information|معلومات الخصوصية|Информация о конфиденциальности|Informations de confidentialité|رازداری کی معلومات|गोपनीयता की जानकारी|隐私信息
Booking terms|شروط الحجز|Условия бронирования|Conditions de réservation|بکنگ کی شرائط|बुकिंग की शर्तें|预订条款
Visit the Knowledge Centre|زر مركز المعرفة|Открыть базу знаний|Consultez le centre de connaissances|معلوماتی مرکز دیکھیں|ज्ञान केंद्र देखें|访问知识中心
Quick quote:|عرض سعر سريع:|Быстрый расчёт:|Devis rapide :|فوری کوٹیشن:|त्वरित कोटेशन:|快速报价：
Contact UKR for bookings, documents and payments.|تواصل مع UKR للحجوزات والمستندات والمدفوعات.|По бронированиям, документам и оплате обращайтесь в UKR.|Contactez UKR pour les réservations, documents et paiements.|بکنگ، دستاویزات اور ادائیگی کے لیے UKR سے رابطہ کریں۔|बुकिंग, दस्तावेज़ और भुगतान के लिए UKR से संपर्क करें।|预订、文件及付款事宜请联系UKR。
Enter the total volume and gross weight. Final LCL rating follows the approved tariff and minimum charges.|أدخل الحجم والوزن الإجمالي. يعتمد سعر الشحن الجزئي النهائي على التعرفة المعتمدة والرسوم الدنيا.|Укажите общий объём и вес брутто. Итоговый тариф LCL зависит от утверждённых ставок и минимальных сборов.|Indiquez le volume total et le poids brut. Le prix LCL final suit le tarif approuvé et les minima de facturation.|کل حجم اور مجموعی وزن درج کریں۔ حتمی LCL نرخ منظور شدہ ٹیرف اور کم از کم چارج کے مطابق ہوگا۔|कुल आयतन और सकल वजन भरें। अंतिम LCL दर अनुमोदित टैरिफ़ और न्यूनतम शुल्क के अनुसार होगी।|请输入总体积与毛重，最终拼箱价格按审核的运价及最低收费计算。
China is the origin. Warehouse receiving details follow booking review. Sea DDP volume bands and starting prices use UKR-approved rates.|نقطة الانطلاق الصين. تُحدّد تفاصيل استلام المستودع بعد مراجعة الطلب. تعتمد شرائح حجم الشحن البحري DDP والأسعار الابتدائية على أسعار UKR المعتمدة.|Отправление из Китая. Складские инструкции предоставляются после проверки запроса. Объёмные диапазоны и начальные цены морского DDP основаны на одобренных UKR тарифах.|Le départ est en Chine. Les consignes de réception suivent la vérification de la demande. Les tranches de volume et prix de départ DDP maritime utilisent les tarifs approuvés par UKR.|روانگی چین سے ہے۔ بکنگ کے جائزے کے بعد گودام کی وصولی کی تفصیلات دی جائیں گی۔ بحری DDP کے حجمی درجے اور ابتدائی قیمتیں UKR کے منظور شدہ نرخوں پر مبنی ہیں۔|प्रस्थान चीन से है। अनुरोध की समीक्षा के बाद गोदाम प्राप्ति निर्देश मिलेंगे। समुद्री DDP के आयतन स्तर और शुरुआती कीमतें UKR की अनुमोदित दरों पर आधारित हैं।|始发地为中国，申请审核后提供仓库收货说明。海运DDP体积档位及起价采用UKR审核的运价。
China is the origin. Air DDP prices depend on chargeable weight and the approved tariff; sea-volume price bands do not apply.|نقطة الانطلاق الصين. تعتمد أسعار DDP الجوي على الوزن المحتسب والتعرفة المعتمدة، ولا تنطبق شرائح التسعير الحجمي البحري.|Отправление из Китая. Цены авиа-DDP зависят от расчётного веса и одобренного тарифа; морские объёмные диапазоны не применяются.|Le départ est en Chine. Le prix DDP aérien dépend du poids taxable et du tarif approuvé ; les tranches maritimes de volume ne s’appliquent pas.|روانگی چین سے ہے۔ فضائی DDP کی قیمت قابلِ چارج وزن اور منظور شدہ نرخ پر منحصر ہے؛ بحری حجمی درجے لاگو نہیں ہوتے۔|प्रस्थान चीन से है। हवाई DDP कीमत प्रभार्य वजन और अनुमोदित दर पर निर्भर है; समुद्री आयतन दरें लागू नहीं होतीं।|始发地为中国，空运DDP价格依据计费重量及审核运价，海运体积档位不适用。
Contact UKR for express rates, dimensional-weight rules and applicable surcharges.|تواصل مع UKR لأسعار الشحن السريع وقواعد الوزن الحجمي والرسوم الإضافية.|Уточните в UKR экспресс-тарифы, правила объёмного веса и доплаты.|Contactez UKR pour les tarifs express, les règles de poids volumétrique et les suppléments.|ایکسپریس نرخ، حجمی وزن کے قواعد اور اضافی چارج کے لیے UKR سے رابطہ کریں۔|एक्सप्रेस दरों, आयतन-आधारित वजन नियमों और अधिभार के लिए UKR से संपर्क करें।|请联系UKR了解快递运价、体积重量规则及附加费。
UAE ↔ GCC, Turkey → UAE, and UAE → Syria / Jordan / Iraq. Availability is subject to route and cargo approval.|بين الإمارات ودول الخليج، ومن تركيا إلى الإمارات، ومن الإمارات إلى سوريا / الأردن / العراق. التوفر رهن الموافقة على المسار والشحنة.|ОАЭ ↔ страны ССАГПЗ, Турция → ОАЭ, ОАЭ → Сирия / Иордания / Ирак. Доступность зависит от одобрения маршрута и груза.|Émirats ↔ CCG, Turquie → Émirats et Émirats → Syrie / Jordanie / Irak. Disponibilité sous réserve d’acceptation de l’itinéraire et du fret.|امارات اور خلیجی ممالک کے درمیان، ترکی سے امارات، اور امارات سے شام / اردن / عراق۔ دستیابی راستے اور سامان کی منظوری سے مشروط ہے۔|यूएई ↔ खाड़ी देश, तुर्की → यूएई, यूएई → सीरिया / जॉर्डन / इराक। उपलब्धता मार्ग और माल की मंज़ूरी पर निर्भर है।|阿联酋↔海湾国家、土耳其→阿联酋，以及阿联酋→叙利亚／约旦／伊拉克。是否承运取决于路线及货物审核。
Local handling, documents and cargo acceptance are reviewed by UKR before a clearance quotation is confirmed.|تراجع UKR المناولة المحلية والمستندات وقبول الشحنة قبل تأكيد عرض التخليص.|UKR проверяет местную обработку, документы и допустимость груза до подтверждения цены оформления.|UKR examine la manutention locale, les documents et l’acceptation du fret avant de confirmer le devis de dédouanement.|کلیئرنس کوٹیشن کی تصدیق سے پہلے UKR مقامی ہینڈلنگ، دستاویزات اور سامان کی قبولیت کا جائزہ لیتا ہے۔|निकासी कोटेशन की पुष्टि से पहले UKR स्थानीय हैंडलिंग, दस्तावेज़ और माल की स्वीकृति जाँचता है।|UKR确认清关报价前，会审核当地操作、文件及货物承运条件。
★ Space is subject to carrier confirmation. When selected space is unavailable, UKR proposes an alternative for your approval. No substitution is automatically accepted.|★ المساحة رهن تأكيد الناقل. عند عدم توفرها، تقترح UKR بديلًا لموافقتك، ولا يُعتمد أي بديل تلقائيًا.|★ Место требует подтверждения перевозчика. Если его нет, UKR предложит альтернативу для вашего согласования. Автоматической замены не будет.|★ La place reste soumise à confirmation du transporteur. Si elle est indisponible, UKR propose une alternative à votre approbation. Aucune substitution n’est acceptée automatiquement.|★ جگہ کیریئر کی تصدیق سے مشروط ہے۔ منتخب جگہ نہ ہونے پر UKR آپ کی منظوری کے لیے متبادل دے گا۔ کوئی متبادل خودکار طور پر قبول نہیں ہوگا۔|★ जगह वाहक की पुष्टि के अधीन है। उपलब्ध न होने पर UKR आपकी मंज़ूरी के लिए विकल्प देगा। कोई बदलाव अपने-आप स्वीकार नहीं होगा।|★ 舱位以承运人确认为准。如所选舱位不可用，UKR将提出替代方案供您批准，不会自动接受替换。
Browse by country|تصفّح حسب الدولة|Поиск по стране|Parcourir par pays|ملک کے لحاظ سے دیکھیں|देश के अनुसार देखें|按国家浏览
All countries|جميع الدول|Все страны|Tous les pays|تمام ممالک|सभी देश|所有国家
Port, country or code|ميناء أو دولة أو رمز|Порт, страна или код|Port, pays ou code|بندرگاہ، ملک یا کوڈ|बंदरगाह, देश या कोड|港口、国家或代码
Filter origin ports by country|تصفية موانئ الانطلاق حسب الدولة|Фильтр портов отправления по стране|Filtrer les ports de départ par pays|روانگی کی بندرگاہیں ملک کے لحاظ سے فلٹر کریں|प्रस्थान बंदरगाह देश से फ़िल्टर करें|按国家筛选起运港
Filter destination ports by country|تصفية موانئ الوجهة حسب الدولة|Фильтр портов назначения по стране|Filtrer les ports d’arrivée par pays|منزل کی بندرگاہیں ملک کے لحاظ سے فلٹر کریں|गंतव्य बंदरगाह देश से फ़िल्टर करें|按国家筛选目的港
Show more ports|عرض موانئ إضافية|Показать ещё порты|Afficher plus de ports|مزید بندرگاہیں دکھائیں|और बंदरगाह दिखाएँ|显示更多港口
Show more ports ({n} remaining)|عرض موانئ إضافية (المتبقي: {n})|Показать ещё порты (осталось {n})|Afficher plus de ports ({n} restants)|مزید بندرگاہیں دکھائیں ({n} باقی)|और बंदरगाह दिखाएँ ({n} शेष)|显示更多港口（剩余{n}个）
Major port|ميناء رئيسي|Основной порт|Port principal|اہم بندرگاہ|प्रमुख बंदरगाह|主要港口
{n} ports. Major ports first; remaining ports alphabetical.|عدد الموانئ: {n}. الموانئ الرئيسية أولًا، ثم البقية أبجديًا.|Портов: {n}. Основные порты первыми, остальные по алфавиту.|{n} ports. Ports principaux en premier, puis ordre alphabétique.|{n} بندرگاہیں۔ اہم بندرگاہیں پہلے، باقی حروفِ تہجی کے مطابق۔|{n} बंदरगाह। प्रमुख पहले, बाकी वर्णानुक्रम में।|共{n}个港口。主要港口优先，其余按字母顺序。
{n} ports in this country. Major ports first; remaining ports alphabetical.|عدد الموانئ في هذه الدولة: {n}. الرئيسية أولًا، ثم البقية أبجديًا.|Портов в этой стране: {n}. Основные первыми, остальные по алфавиту.|{n} ports dans ce pays. Principaux en premier, puis ordre alphabétique.|اس ملک میں {n} بندرگاہیں۔ اہم پہلے، باقی حروفِ تہجی کے مطابق۔|इस देश में {n} बंदरगाह। प्रमुख पहले, बाकी वर्णानुक्रम में।|该国共{n}个港口。主要港口优先，其余按字母顺序。
Possible spelling matches|نتائج محتملة لتصحيح التهجئة|Возможные совпадения по написанию|Correspondances orthographiques possibles|ممکنہ ہجائی نتائج|संभावित वर्तनी मिलान|可能的拼写匹配
No maritime port matches. Try the country, another spelling or a UN/LOCODE. Contact UKR for unlisted locations.|لا توجد موانئ بحرية مطابقة. جرّب الدولة أو تهجئة أخرى أو رمز UN/LOCODE. تواصل مع UKR للمواقع غير المدرجة.|Морских портов не найдено. Попробуйте страну, другое написание или UN/LOCODE. Для отсутствующих пунктов обратитесь в UKR.|Aucun port maritime correspondant. Essayez le pays, une autre orthographe ou un UN/LOCODE. Contactez UKR pour un lieu non répertorié.|کوئی سمندری بندرگاہ نہیں ملی۔ ملک، دوسرے ہجے یا UN/LOCODE آزمائیں۔ غیر درج مقامات کے لیے UKR سے رابطہ کریں۔|कोई समुद्री बंदरगाह नहीं मिला। देश, दूसरी वर्तनी या UN/LOCODE आज़माएँ। सूची से बाहर स्थानों के लिए UKR से संपर्क करें।|未找到匹配海港。请尝试国家名、其他拼写或UN/LOCODE。未列出的地点请咨询UKR。
Search {n} maritime locations by port, country or code. Jebel Ali is your starting destination. A listed port does not confirm a shipping service or rate.|ابحث في {n} موقعًا بحريًا حسب الميناء أو الدولة أو الرمز. جبل علي هو الوجهة الافتراضية. إدراج الميناء لا يؤكد توفر خدمة أو سعر.|Поиск по {n} морским пунктам: порт, страна или код. Начальное назначение: Джебель-Али. Наличие порта в списке не подтверждает услугу или тариф.|Recherchez parmi {n} lieux maritimes par port, pays ou code. Jebel Ali est la destination initiale. Un port répertorié ne confirme ni service ni tarif.|بندرگاہ، ملک یا کوڈ سے {n} سمندری مقامات تلاش کریں۔ جبل علی ابتدائی منزل ہے۔ بندرگاہ کا درج ہونا سروس یا نرخ کی تصدیق نہیں۔|बंदरगाह, देश या कोड से {n} समुद्री स्थान खोजें। जेबेल अली आरंभिक गंतव्य है। सूची में बंदरगाह होना सेवा या दर की पुष्टि नहीं है।|按港口、国家或代码搜索{n}个海运地点。默认目的地为杰贝阿里。列出港口并不代表已确认服务或运价。
Choose origin and destination from the port directory.|اختر ميناء الانطلاق والوجهة من دليل الموانئ.|Выберите отправление и назначение из справочника портов.|Choisissez les ports de départ et d’arrivée dans le répertoire.|بندرگاہوں کی فہرست سے روانگی اور منزل منتخب کریں۔|बंदरगाह सूची से प्रस्थान और गंतव्य चुनें।|请从港口目录选择起运港和目的港。
Origin and destination must be different.|يجب أن تختلف نقطة الانطلاق عن الوجهة.|Пункты отправления и назначения должны различаться.|Le départ et l’arrivée doivent être différents.|روانگی اور منزل مختلف ہونی چاہئیں۔|प्रस्थान और गंतव्य अलग होने चाहिए।|起点和终点不能相同。
Select a supported land-transport route.|اختر مسار نقل بري مدعومًا.|Выберите поддерживаемый автомобильный маршрут.|Choisissez un itinéraire routier pris en charge.|دستیاب زمینی راستہ منتخب کریں۔|समर्थित सड़क मार्ग चुनें।|请选择支持的陆运路线。
Enter the same email address in both fields.|أدخل البريد الإلكتروني نفسه في الحقلين.|Введите одинаковый адрес в обоих полях.|Saisissez la même adresse e-mail dans les deux champs.|دونوں خانوں میں ایک ہی ای میل درج کریں۔|दोनों फ़ील्ड में एक ही ईमेल भरें।|请在两处填写相同的邮箱地址。
Choose up to 5 PDF, image or spreadsheet files, maximum 10 MB each.|اختر حتى 5 ملفات PDF أو صور أو جداول، بحد أقصى 10 ميغابايت لكل ملف.|Выберите до 5 файлов PDF, изображений или таблиц, до 10 МБ каждый.|Choisissez jusqu’à 5 PDF, images ou tableaux de 10 Mo maximum chacun.|زیادہ سے زیادہ 5 PDF، تصویر یا اسپریڈشیٹ فائلیں منتخب کریں، ہر ایک 10 MB تک۔|अधिकतम 5 PDF, चित्र या स्प्रेडशीट चुनें, प्रत्येक 10 MB तक।|最多选择5个PDF、图片或表格文件，每个不超过10MB。
Complete this field.|أكمل هذا الحقل.|Заполните это поле.|Remplissez ce champ.|یہ خانہ مکمل کریں۔|यह फ़ील्ड भरें।|请填写此项。
Enter a valid email address.|أدخل بريدًا إلكترونيًا صحيحًا.|Введите корректный e-mail.|Saisissez une adresse e-mail valide.|درست ای میل درج کریں۔|मान्य ईमेल भरें।|请输入有效邮箱。
Enter a valid number.|أدخل رقمًا صحيحًا.|Введите корректное число.|Saisissez un nombre valide.|درست عدد درج کریں۔|मान्य संख्या भरें।|请输入有效数字。
Enter {min} or more.|أدخل {min} أو أكثر.|Введите не менее {min}.|Saisissez au moins {min}.|{min} یا زیادہ درج کریں۔|{min} या अधिक भरें।|请输入不小于{min}的数值。
Enter {max} or less.|أدخل {max} أو أقل.|Введите не более {max}.|Saisissez au plus {max}.|{max} یا کم درج کریں۔|{max} या कम भरें।|请输入不大于{max}的数值。
Use increments of {step}.|استخدم زيادات مقدارها {step}.|Используйте шаг {step}.|Utilisez un pas de {step}.|{step} کے اضافے استعمال کریں۔|{step} की वृद्धि का उपयोग करें।|请按{step}递增。
Check the value in this field.|تحقق من قيمة هذا الحقل.|Проверьте значение поля.|Vérifiez la valeur de ce champ.|اس خانے کی قدر دیکھیں۔|इस फ़ील्ड का मान जाँचें।|请检查此项数值。
Choose files|اختر الملفات|Выбрать файлы|Choisir des fichiers|فائلیں منتخب کریں|फ़ाइलें चुनें|选择文件
No files selected|لم تُحدد ملفات|Файлы не выбраны|Aucun fichier sélectionné|کوئی فائل منتخب نہیں|कोई फ़ाइल नहीं चुनी गई|未选择文件
{n} files selected|عدد الملفات المحددة: {n}|Выбрано файлов: {n}|Fichiers sélectionnés : {n}|منتخب فائلیں: {n}|चुनी गई फ़ाइलें: {n}|已选择{n}个文件
Cargo ready: {date}|جاهزية الشحنة: {date}|Груз готов: {date}|Fret disponible : {date}|سامان تیار: {date}|माल तैयार: {date}|货妥日期：{date}
Port data: UNECE UN/LOCODE 2025-1 · CC BY 4.0|بيانات الموانئ: UNECE UN/LOCODE 2025-1 · CC BY 4.0|Данные портов: UNECE UN/LOCODE 2025-1 · CC BY 4.0|Données portuaires : UNECE UN/LOCODE 2025-1 · CC BY 4.0|بندرگاہوں کے اعداد: UNECE UN/LOCODE 2025-1 · CC BY 4.0|बंदरगाह डेटा: UNECE UN/LOCODE 2025-1 · CC BY 4.0|港口数据：UNECE UN/LOCODE 2025-1 · CC BY 4.0
`;
